src/pretix/control/views/orders.py
In the order overview the total of "paid orders" is the same as the total number of "ordered items". By using the right variable, we can easily fix that ;)
=> Show the correct number of paid items

.gitignore, src/pretix/base/forms/auth.py, src/pretix/base/forms/user.py, src/pretix/control/views/auth.py, src/pretix/settings.py, src/tests/control/test_auth.py, src/tests/control/test_user.py
Partially fixes #113. Do let me know if there are any issues with the code.
=> Added basic Django password validations

doc/development/setup.rst, src/pretix/presale/middleware.py, src/pretix/presale/utils.py
This simplifies providing an `event_view` method which works as
decorator for presale/ views (e.g. for plugins), providing passing
requests with event and organizer context if possible, and re-routing or
failing appropriately otherwise.
=> Move middleware functionality to utils.py

doc/development/setup.rst, src/pretix/base/services/mail.py
As per #164 
Can be either committed as-is, or I could add error-handling to all `mail()` calls. Not sure how useful this would be, especially since mail errors will be logged regardless. I probably should at least do this for the sendmail plugin?
=> Make mail() raise an exception on obvious failures

src/pretix/base/exporters/json.py
This might be required for various depending services; knowing a price without the included tax isn't useful in a lot of places.
=> Export an item's tax_rate in the JSON export

src/pretix/base/models/invoices.py, src/pretix/base/models/orders.py, src/pretix/base/models/vouchers.py, src/pretix/plugins/pretixdroid/views.py
Django's get_random_string tries really hard to either use sysrandom or
be otherwise as unpredictable as possible.
=> Use get_random_string everywhere

src/pretix/control/templates/pretixcontrol/attendees/index.html, src/pretix/control/templates/pretixcontrol/events/index.html, src/pretix/control/templates/pretixcontrol/orders/index.html, src/pretix/control/templates/pretixcontrol/pagination.html
Also, add a second, upper pagination element to orders and attendees
list sites as those tend to get long.
=> Add a count of elements to pagination elements

src/pretix/base/models/vouchers.py, src/pretix/base/services/orders.py, src/pretix/presale/views/order.py, src/tests/base/test_models.py
As discussed in #165, I added a second commit disallowing cancelling expired orders to avoid weird edge cases (and because it makes sense). Supersedes/continues #183.
=> Reactivate voucher on cancelled orders (#165)

src/pretix/presale/templates/pretixpresale/event/order_modify.html, src/pretix/presale/views/order.py
Adds messages both pre- and post-update explaining to the user that the
invoice itself will not be automatically regenerated and that support
interaction is required for this step. Might reduce user frustration. (re: #195)
What this doesn't do
- it will display "please contact us at None" if no contact email is configured
- it doesn't display the email as mailto: link
I wasn't sure how to do *both* of these things idiomatically while using translation. Any help appreciated.
=> Add message explaining invoice address updating process (#195)

src/pretix/base/services/mail.py, src/pretix/base/settings.py, src/pretix/presale/forms/user.py, src/pretix/presale/templates/pretixpresale/event/resend_link.html, src/pretix/presale/urls.py, src/pretix/presale/views/user.py, src/tests/presale/test_event.py
If the provided mail address has not ordered anything, there will still
be a mail generated and sent to an invalid mail address, to avoid
obvious timing attacks to determine active users. (#122)
TODO:
From review:
=> Allow users to re-send order links (#122)

src/pretix/plugins/statistics/static/pretixplugins/statistics/statistics.js
Alternative would be to set xLabelMargin to something low - but this
would just cause new problems with very, very long names.
=> Tilt Ordered/Paid Statistics Labels in order to show them all

.gitattributes
Some external libraries that are bundled in this repository (fontawesome, lightbox, typeahead, moment.js) are not treated as vendored by the github stats. This can be fixed by adding a .gitattributes file. See [Linguist](https://github.com/github/linguist) for details.
Before change
```
50.79%  Python
29.35%  JavaScript
13.43%  HTML
6.23%   CSS
0.10%   Shell
0.08%   Nginx
0.02%   Makefile
```
After change:
```
74.76%  Python
19.77%  HTML
3.45%   CSS
1.74%   JavaScript
0.14%   Shell
0.12%   Nginx
0.03%   Makefile
```
=> remove bundled code from github stats

src/pretix/base/models/vouchers.py
Voucher tags were not documented in the help text at the beginning
of the voucher class.
Related to #228
=> Add documentation for voucher tags

src/pretix/base/services/mail.py
`"-- "` on a single line as a signature-delimiter is noticed by a lot of mail programs out there as an actual signature separator and the text below may be marked that way, e.g. is greyed out a little in Mozilla Thunderbird.
This change should leverage that behavior for e-mails sent by pretix.
=> Change signature-delimiter for e-mails

doc/development/implementation/logging.rst, doc/images/order_states.puml, src/pretix/base/models/invoices.py, src/pretix/base/models/items.py, src/pretix/base/models/orders.py, src/pretix/base/services/orders.py, src/pretix/base/services/stats.py, src/pretix/control/logdisplay.py, src/pretix/control/templates/pretixcontrol/attendees/index.html, src/pretix/control/templates/pretixcontrol/items/question.html, src/pretix/control/templates/pretixcontrol/orders/fragment_order_status.html, src/pretix/control/templates/pretixcontrol/orders/index.html, src/pretix/control/templates/pretixcontrol/orders/overview.html, src/pretix/control/views/orders.py, src/pretix/locale/de/LC_MESSAGES/django.po, src/pretix/locale/de_Informal/LC_MESSAGES/django.po, src/pretix/plugins/banktransfer/tasks.py, src/pretix/plugins/banktransfer/views.py, src/pretix/plugins/paypal/views.py, src/pretix/plugins/reports/exporters.py, src/pretix/presale/templates/pretixpresale/event/fragment_order_status.html, src/pretix/presale/views/order.py, src/tests/control/test_orders.py, src/tests/plugins/banktransfer/test_import.py, src/tests/presale/test_orders.py
Switching 'cancelled' (double 'L') to 'canceled' (single 'L') across all files.
#187
I skipped all `src/pretix/base/migrations/*` files (I understand that these files are overwritten when new migrations are done, but I'm not sure about this :confused: ). Please let me know if they need to be included.
=> Unify spelling of 'canceled' - #187

src/requirements/dev.txt
Thanks to @flaviabastos for reporting this in #259.
I think the issue is solved by higher versions of sqlparse in general,
but without further testing, version pinning is probably the safest
option.
Tested both with python 3.4 and 3.5, fixes the issue successfully.
=> Fix incompatibility with sqlparse and debug-toolbar

src/pretix/plugins/paypal/payment.py, src/pretix/plugins/stripe/payment.py, src/pretix/plugins/stripe/views.py
Except when triggered by a webhook. Closes #275
=> Pass request's user when refunding (for logging)

doc/admin/config.rst, src/pretix/base/metrics.py, src/pretix/base/views/metrics.py, src/pretix/settings.py, src/pretix/urls.py, src/tests/base/test_metrics.py
This PR adds the necessary datatypes to provide prometheus-like instrumentation natively to pretix.
Currently supported by this PR are Counters and Gauges.
=> add basic instrumentation possibilities to pretix

src/pretix/plugins/banktransfer/views.py
Leads to having the most recent unresolved transfers on top instead of
in between.
=> Order Bankimports by their job's date

doc/development/setup.rst
Improved documentation by adding some requirements that where needed to install from a clean Debian 8.6 installation.
Before the ```$ pip3 install -r requirements.txt -r requirements/dev.txt``` installation step would succeed I needed to add the following dependencies:
```$ sudo aptitude install libxml2-dev```
```$ sudo aptitude install libxslt1-dev```
The Error without the dependencies ended with:
```
In file included from src/lxml/lxml.etree.c:515:0:
src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
#include "libxml/xmlversion.h"
^
compilation terminated.
Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
creating tmp
cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitm_7rr3ky.c -o tmp/xmlXPathInitm_7rr3ky.o …
```
=> Improved documentation by adding missing requirements

src/.gitignore, src/pretix/base/models/log.py, src/pretix/control/templates/pretixcontrol/event/base.html, src/pretix/plugins/sendmail/signals.py, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/history.html, src/pretix/plugins/sendmail/urls.py, src/pretix/plugins/sendmail/views.py, src/tests/control/test_items.py
This logs to the database emails sent with sendmail plugin and displays them in the control backend
Also adds support to second-level nav to plugins
As I previously mentioned, I'm confused about *event*-level and *order*-level logs so I don't know if I am logging/displaying the right thing (probably not). I appreciate feedback. 
I'm displaying raw (uggly) data but 1- I wasn't sure I had the right thing and 2- I didn't know how to display it prettier. 
I didn't remove the code for the new Model either. Let me know if it needs to go.
=> Log emails sent with sendmail plugin #307

src/pretix/presale/views/organizer.py
...to show more than one event per page. Maybe this value should become a configurable value in the future.
=> Changed pagination of organizer page

doc/admin/installation/docker_smallscale.rst, doc/admin/installation/manual_smallscale.rst
The example configs list `psycopg2` as the name for the Django postgres database module, but it's actually `postgresql_psycopg2`: https://github.com/django/django/tree/master/django/db/backends/postgresql_psycopg2
=> Correct wrong module name for Postgres in example configs

src/pretix/plugins/sendmail/views.py
This fixes issue #409
Add check to confirm if there are no orders with that status. In this case, display error message and keep form populated. Doesn't log any info.
=> Fix false success message on sendmail plugin

src/pretix/base/models/items.py, src/pretix/base/models/orders.py, src/pretix/base/services/cart.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/forms/orders.py, src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/control/templates/pretixcontrol/order/change.html, src/pretix/control/templates/pretixcontrol/order/index.html, src/pretix/control/views/orders.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/event/voucher.html, src/pretix/presale/views/__init__.py, src/pretix/presale/views/cart.py, src/pretix/presale/views/event.py
This shows net prices everywhere in the frontend, e.g. in the product list and in the cart:
=> Introduce a setting to show net prices

src/pretix/control/forms/event.py, src/pretix/control/views/event.py, src/tests/control/test_events.py
Hi, this is the PR for fixing #428 .
**event creation**
This has been fixed by adding timezone to date related values in `clean` method in `EventWizardBasicsForm`.
**event update**
I still have no idea how I can fix it. (Sorry I'm pretty new to django..)
>From the top of my head, I would go neither for option 1 nor for option 2. EventWizard and EventUpdate are views, which are rather to high-level for this kind of thing and Event is a model which is rather to low-level for this. In my opinion, the golden middle road would be the forms involved, which are EventWizardBasicsForm and EventUpdateForm. We could do it in the save() methods there but I think an even better way might be the clean() method in Django's validation cycle.
@raphaelm I just learnt the django's validation cycle you …
=> fix #428: ignore timezone when saving event

src/pretix/base/models/event.py, src/pretix/settings.py, src/requirements/production.txt, src/setup.py, src/tests/control/test_events.py
Fixes #446 
Uses a choice attribute so the event currency will be a 3 character ISO currency. Also, adds pycountry to the requirements which provide the list of countries and currencies.
=> Change event currency to use a choice attribute

deployment/docker/nginx.conf, doc/admin/installation/manual_smallscale.rst
This change adds the following security headers:
* X-Content-Type-Options to prevent content type sniffing
* Referrer-Policy to prevent leaking referrer information when navigating away from the instance
=> Include some missing security headers

deployment/docker/nginx.conf
...which results in docker container setup not starting properly.
You can see the log message setting up the container and entering
`docker exec -it --user root pretix.service cat /var/log/nginx/error.log`
=> Added missing semicolon to docker nginx config

.gitattributes
`.gitattributes` is used in the cloning process for, among other things, determining if a file is text, and needs to have line-endings converted. Doing this to the binary webfont files will cause issues with using them.
When merged, fixes #486.
=> Marked webfonts as binary files

src/pretix/base/settings.py, src/pretix/base/ticketoutput.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/tickets.html, src/pretix/plugins/ticketoutputpdf/ticketoutput.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/views/order.py
Per #456, allow products designated as non-admission to be excluded from ticket generation.
Includes the following:  
* Events setting `ticket_generation_nonadm` for generating tickets for non-admission products (defaults to true for backwards compatibility)  
* Logic to remove download button for non-relevant line items in order view  
* Error for non-admission items (if not allowed) in single ticket download and multi-ticket download.
Thanks to @raphaelm with https://github.com/pretix/pretix/issues/456#issuecomment-298421117 for assistance on what needed to be done here.
Closes #456.
=> Allow products to be excluded from ticket-generation

src/pretix/base/services/mail.py, src/pretix/base/settings.py, src/pretix/base/templates/pretixbase/email/plainwrapper.html, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/mail.html, src/tests/base/test_mail.py
Added mail signature functionality.
=> Mail signature

src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/history.html, src/pretix/plugins/sendmail/views.py
Hi @raphaelm ,
I am sticked at how to add the mail content to the new form. I used the initial but it said there was an error at the __init__() of the mail form. It supposed to accept the message argument and add the content when init right?
Another question, is this[pull request](https://github.com/pretix/pretix/pull/455) created correctly? I used `git push origin feature/new-send-mail` but it said there was no branch as provided.
Thanks in advance :)
=> [WIP] Fix #447 -- Sendmail plugin: Create new mail based on an old one

src/pretix/helpers/daterange.py, src/tests/helpers/test_daterange.py
Hey,
in this commit I fixed a bug in `daterange.py`. `daterange(df,dt)` now does what it should if the two dates are equal: It returns the string for one day.
I also added a (probably _slightly_ overkill) unit test.
Cheers
Marvin
=> fixed bug for same dates, added unit check for daterange

src/pretix/base/templatetags/rich_text.py, src/pretix/control/forms/organizer.py, src/pretix/control/templates/pretixcontrol/organizers/edit.html, src/pretix/presale/context.py, src/pretix/presale/templates/pretixpresale/organizers/index.html
This PR adds a configurable text that can be displayed under an organizer's name on the corresponding page. Things to follow in near future:
- organizers might be given language options (overwritten by events' language options) allowing language selection at an organizer's front end page
- unit tests will be added after some more work on the organizer page
- `rich_text` filter tag should recognize single newlines
=> Added configurable text for organizer page

src/pretix/locale/de/LC_MESSAGES/django.po, src/pretix/locale/de_Informal/LC_MESSAGES/django.po
There was a space missing in de and de_informal in the description for the quota edit.
Hopefully this is the right way to send you guys my edit.
Best regards.
=> added missing spaces in DE and DE_informal

src/make_testdata.py
Test data creation was broken as t was a tuple instead of a Team object.
=> Fix calling of object attribute on tuple

doc/development/setup.rst
Document outdated with year of test data still at 2017 in url, leading to 404
=> Minor update to setup documentation

src/pretix/plugins/banktransfer/mt940import.py, src/pretix/plugins/banktransfer/tasks.py, src/setup.py
Payment details from raiffaisen.ch are only available in non-SWIFT (NS) tags. Thus added support for these tags in mt940. Now use the newer version and also parse these fields when available.
=> Read payment details from MT940 NS tags too

src/pretix/base/forms/user.py
This is a fix for issue #454.
The email field has now been set to required on the admin user account settings page.
=> fix for #454 - made email field required on admin user settings page

src/pretix/base/models/vouchers.py
Useful in plugins if you don't want to replicate the uniqueness loop.
=> Allow to pass prefix to generate_code, too

src/pretix/base/models/vouchers.py
Due to:
```
/home/rixx/.virtualenvs/pretix-c3/lib/python3.6/site-packages/django/views/generic/list.py:100: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list
```
=> Order vouchers by code by default

src/pretix/control/templates/pretixcontrol/event/plugins.html, src/pretix/static/pretixcontrol/scss/main.scss
Use flexbox to fix misalignment when column height is imbalanced.
=> Fix #516 -- Prevent gaps in plugin list

src/pretix/presale/forms/checkout.py, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html, src/pretix/static/pretixpresale/scss/_forms.scss
This adds a new css class `required` to all form-groups that correspond to a required field. I then added a piece of CSS that adds a purple asterisk to the end of the labels in these fields.
=> Fix #130: Mark required question fields at checkout

src/setup.py
When installing pretix from pip, stripe integration fails. This happens because [setup.py wants to install stripe==1.22.*](https://github.com/pretix/pretix/blob/5f607cc03409160437f6490032b04a463b4205ee/src/setup.py#L100) while [requirements/production.txt wants stripe==1.62.*](https://github.com/pretix/pretix/blob/5f607cc03409160437f6490032b04a463b4205ee/src/requirements/production.txt#L35) – the former is incorrect. Installing stripe 1.22.* causes [this line](https://github.com/pretix/pretix/blob/5f607cc03409160437f6490032b04a463b4205ee/src/pretix/plugins/stripe/payment.py#L384) to fail with `AttributeError: module 'stripe' has no attribute 'Source'`.
This commit updates the setup.py to require the correct version of the stripe bindings.
=> fix wrong stripe version in setup.py

src/pretix/plugins/stripe/payment.py, src/tests/plugins/stripe/test_settings.py
This checks if the publishable and secret keys given in the stripe settings survive a basic sanity check: do they start with `pk_` and `sk_`? The goal is to prevent users from swapping the keys accidentally.
Please let me know what you think about this solution as well as the tests. If you would like anything in the PR to be solved differently, just let me know and I am happy to adapt the code. Thanks!
Fixes #619.
=> Check format of stripe API keys in settings 

src/pretix/plugins/banktransfer/static/pretixplugins/banktransfer/ui.js, src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/transaction_list.html, src/pretix/plugins/banktransfer/views.py
This commit allows transaction comments to display newlines and URLs in
a useful way, helping when additional data (such as a reference to a
ticket system or a longer discussion) is required.
This PR also prevents pretix from having to bring its own chat system ;)
=> Allow markdown rendering in transaction comments.

src/pretix/control/forms/organizer.py, src/pretix/control/templates/pretixcontrol/event/base.html, src/pretix/control/templates/pretixcontrol/event/display.html, src/pretix/control/templates/pretixcontrol/organizers/base.html, src/pretix/control/templates/pretixcontrol/organizers/display.html, src/pretix/control/templates/pretixcontrol/organizers/edit.html, src/pretix/control/templatetags/hierarkey_form.py, src/pretix/control/urls.py, src/pretix/control/views/event.py, src/pretix/control/views/organizer.py, src/pretix/presale/context.py, src/pretix/presale/style.py, src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixcontrol/scss/_forms.scss, src/tests/control/test_events.py, src/tests/control/test_organizer.py, src/tests/control/test_permissions.py, src/tests/presale/test_style.py
Added a "primary color option" for organizer pages (cf. event).
The selected color will not yet be set as default value for the organizers' events, because I still have to figure out an elegant way to do so.
I will continue working on the organizer page adding a language selector and restructuring the control interface in order to replicate the workflow for editing events. In the process I will deal with the default value issue.
Also, there will be unit tests for the new features.
=> Organizer color & settings propagation

src/pretix/base/services/mail.py, src/pretix/plugins/sendmail/forms.py, src/pretix/plugins/sendmail/views.py, src/tests/base/test_mail.py, src/tests/plugins/test_sendmail.py
Placeholders in subject were not being replaced because there was
no `.format()` called on the subject.
This commit creates a context dict that is used for both the body
and the subject. It is then replaced using `.format_map()`
Fixes https://github.com/pretix/pretix/issues/531
=> Make placeholders replace in subject

src/pretix/control/logdisplay.py, src/pretix/control/templates/pretixcontrol/checkin/index.html, src/pretix/control/views/checkin.py, src/tests/control/test_checkins.py
This enables manual check-in of attendees.  The post-code was heavily
copied from the APIRedeemView of the pretixdroid, thus so far this seems
to be working, but I have a few questions:
The checkin-Objects generated by the pretixdroid-app have a nonce.
Should the checkin object generated here have a nonce, too?
Should the result of the check-in be noted in any other way than by the
change of the status?
=> Fix #630 -- manual check-in of attendees

src/pretix/static/pretixcontrol/scss/main.scss
Small style change that fixes long word overflow in .panel-body elements
in admin interface.
Fix #611
=> Fix #611 -- Fix overflow in payment information

src/pretix/base/services/orders.py, src/pretix/base/signals.py, src/pretix/control/forms/orders.py, src/pretix/control/logdisplay.py, src/pretix/control/templates/pretixcontrol/order/change.html, src/pretix/control/views/orders.py, src/tests/base/test_orders.py
=> Fix #339 -- Allow to split orders

src/pretix/control/templates/pretixcontrol/order/index.html
Changes template to show "View order as user" and "View email history"
buttons on orders in refunded or cancelled status in control backend.
Fix #641.
=> Fix #641 -- Show Buttons on Cancelled or Refunded Order

src/pretix/locale/de/LC_MESSAGES/django.po
I think the only "critical" fix here is the change from "Zahlmethoden"
to "Zahlungsmethoden", but that is the word used in the rest of the
translations, so I figured it should be changed here as well.
=> correct typos in formal german translation

src/pretix/presale/checkoutflow.py, src/pretix/presale/templates/pretixpresale/event/checkout_base.html, src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html, src/pretix/presale/templates/pretixpresale/event/fragment_checkoutflow.html, src/pretix/presale/views/checkout.py, src/pretix/static/pretixpresale/scss/_checkout.scss, src/pretix/static/pretixpresale/scss/main.scss
as part of a reaction to #670 
Minimal case:
Maximal case:
On Mobile:
What do you all think? 
@rixx @stapelberg @breunigs @janx2 opinions on this? :)
=> Implement progress indicator during checkout

doc/admin/installation/manual_smallscale.rst
this header was probably meant - at least it's the one that's actually used in the wild.
=> fix "typo" Referrer-Options -> Referrer-Options

README.rst
According to the discussion in #689, the Code of Conduct gets directly
referenced in the README-file, instead of linking to the CODE_OF_CONDUCT-file.
=> mention CoC in README.md

src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
[This commit](https://github.com/pretix/pretix/commit/a62fbd54d4a1eba5cf243a449a20ac4610d478c4) removes the typo-checking for e-mail-adresses. Therefore, this box isn't needed either. Just running the shop from the current master leads to 
This might be because of my inability to work with pretix correctly, but I think this is the right thing to do ;)
=> remove alert since mail-typo-checking is disabled

doc/api/resources/checkinlists.rst, doc/api/resources/orders.rst, doc/checkin_filter.py, doc/conf.py, doc/plugins/pretixdroid.rst, doc/spelling_wordlist.txt, src/pretix/base/models/checkin.py, src/pretix/base/models/items.py
The main problem here is, that for readability, variables used in code should be spelled without dash, e.g. the variable `checkin_count` should not be spelled `check-in_count`. When documenting these variables, pyenchant seems to tokenize them on the `_`, and the `checkin`-part gets spell-checked and marked as wrong. 
To overcome this, we implement a custom filter, accepting words that start with `checkin_`. The problem here is, that then the `count`-part of `checkin_count` doesn't get spell-checked. 
I'm currently looking into solving this, but my inability to non-yakshave makes this hard ;)
=> standardize use of check-in

src/pretix/presale/templates/pretixpresale/event/checkout_payment.html
This was the nicest version I could think of. 😄 
This is how it looks like:
=> Fix #731 -- Display negative payment method fees correctly

doc/development/setup.rst
When using the test data generation script, the demo conference no longer has the URL ``/bigevents/2018``, but is now moved to ``/bigevents/2019`` . This confused me in the beginning.
=> Update development documentation, update demo URL

doc/user/markdown.rst
I settled for using `*`, since that's how you do italics in rst.
=> Fix italics underscores in markdown doc (Fix #748)

src/pretix/base/services/orders.py, src/pretix/plugins/stripe/views.py, src/tests/base/test_orders.py
Is there a way to make this 'more robust'?
=> Fix #751 -- calculate payment fees in OrderChangeManager

doc/development/api/exporter.rst
The signal is defined at 
https://github.com/pretix/pretix/blob/353dce789d5dfe6c0ebf6e98257999325b6958f1/src/pretix/base/signals.py#L143
and ends with an s.
=> Fix register exporter signal name in doc

src/pretix/settings.py
Given the following configuration:
[metrics]
enabled=False
Using config.get results in a METRICS_ENABLED value that always
evaluates to True. This PR switches to config.getboolean so that metrics
can be disabled without deleting the configuration values.
=> Use config.getboolean to get metrics enabled value

src/pretix/base/services/orders.py
While this is a simple fix, it at least makes it possible again to add products without tax rules.
=> Refs #754 -- check item tax_rule is not none

src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/views/event.py
This reworks the condition on when the voucher input field should be shown in the presale event page.
Now, not only do vouchers need to exists, but if subevents exists, one must be selected for the input field to show up.
=> Refs #757: show voucher input for subevents only if subevent is selected

src/pretix/control/templates/pretixcontrol/subevents/detail.html, src/pretix/control/views/subevents.py
This was easier than I thought it would be, although I had to guess a bit...
=> Fix #779: add form field for unpaid option of checkin lists in subevent detail view

src/pretix/multidomain/maindomain_urlconf.py, src/tests/base/test_urls.py
This PR can be split:  the first commit fixes a bug, and the second commit provides a unit test to prevent the bug from resurfacing.
The site index page failed to load with metrics collection enabled because the default URL did not have a name.  This caused the following:
```
ERROR 2018-02-23 02:10:03,916 django.request exception Internal Server Error: /
Traceback (most recent call last):
File "/home/tim/src/pretix/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/home/tim/src/pretix/pretix/src/pretix/helpers/metrics/middleware.py", line 34, in __call__
url_name=url.namespace + ':' + url.url_name)
TypeError: must be str, not NoneType
```
Adding a name to the index url and a test to ensure that all urls are …
=> Name presale index + unit test for URL names

src/pretix/presale/forms/checkout.py
This is a very basic approach to address the request of Issue #798 .  
Probably this is not really what you want to see here, since it really looks awkward. Please don't blame me for it :relaxed: 
It's currently showing at https://pretix.460.kif.rocks/sandbox/kif-sandbox/
This is a sandbox shop, so feel free to put something in the cart to see the addon page.
=> Fix #798 -- Show availability for addon products

src/pretix/base/notifications.py
As there are already notifcations for order placed, paid, cancelled and refunded, why not add the only missing order expired notifcation type?
=> Add order expired notification

src/pretix/base/notifications.py
This adds the event name to admin notifications. Without this, it is not possible to distinguish between different event, if you have notifications enabled for multiple accounts (exept from the url).
=> Fix #861 -- Add event name to admin notification email

src/pretix/presale/templates/pretixpresale/base.html
At the moment, the top level container div carries all of the content html, except the footer. This moves the footer into the container to make styling the document easier. (See #871)
I'm unsure about the above block. I only saw it used for the "This shop is only visible to you" banner, which I did not move.
=> Fix #871 -- move footer to main container

src/pretix/control/forms/event.py
probably due to copypasta the event deletion form says "new password". This changes it to "Your password" to be in line with the data shredder pw confirmation field.
=> fix placeholder for event deletion password

src/pretix/presale/forms/checkout.py
Just like #828, I'd like to change the email field description in the presale to be more general.
=> Presale: change email field help text

src/pretix/presale/templates/pretixpresale/event/order.html
Hide download tickets message when no download date is specified.
=> Fix #908 -- Fix display of ticket download message

src/pretix/control/views/item.py
As you can see, the table and graph data is messed up. Aggregation is not correct and links don't point to the correct filtered list:
I streamlined the code and it's showing correct results now. Also, I changed the ordering for date/time questions.
=> Fix bug in date/time question stats

src/pretix/control/templates/pretixcontrol/vouchers/index.html, src/pretix/control/urls.py, src/pretix/control/views/vouchers.py
In regards to the issue #357 (Search orders/go to voucher):
It seems that partial search works for Orders.
And this PR is about adding Go input to the Vouchers page.
But I also have a couple questions:
1_ I haven't used Djnango translation systems before and my question is about that. The text I added ("There is no voucher with the given voucher code."), even though is passed to the _ugettext_lazy_ function does not appear in the _.po_ file. How is that being added?
2_ As you can see in the images below, the filter section of the Vouchers page is getting cluttered and I'm wondering what you think should be done here.
Order list:
Vouchers list:
This is my first PR to this repo, and I think my code conforms to the guidelines. But please let me know if there is something I'm missing.
Thank …
=> Fix #357 -- Implement go to for vouchers

src/pretix/presale/views/widget.py, src/pretix/static/pretixpresale/js/widget/widget.js, src/tests/presale/test_widget.py
I think this makes sense as it is already done in the normal purchase flow outside the widget (since 8f2adf0a).
Was requested by internal support ticket # 2336058.
=> Widget: set default number to 1 if there is only one product

src/pretix/base/templates/error.html
```
</body>
<script src="/static/pretixbase/js/errors.4db07680b709.js"></script>
</html>
```
The script tag is after the body tag. This merge request switches the corresponding lines.
=> Fix outside of body script element

src/pretix/multidomain/middlewares.py
http_date is deprecated as of Django 2.1
=> Use http_date instead of cookie_date

src/pretix/control/views/orders.py, src/pretix/presale/views/__init__.py
While plugin developers are supposed to return an empty dictionary, it's
conceivable that they might just put in a `return` if their field is not
needed, and pretix being generous about this would be cool.
=> Allow empty plugin responses

src/pretix/plugins/paypal/payment.py, src/pretix/plugins/paypal/signals.py, src/pretix/plugins/paypal/urls.py, src/pretix/plugins/paypal/views.py
New feature to offer something similar to Stripe Connect.
As of now, the eMail-Address of the payee is transmitted instead of the MerchantID. For a later iteration, it might be interesting to use that one instead as it should be less volatile than an email-address. However - for the time being - I was unable to get the MerchantID using the REST API.
=> Fix #369 -- Connect with PayPal

src/pretix/base/middleware.py
As of now, pretix does not have any default Content-Security-Policy for `media-src`es.
This PR will take care of this - and help me for a future plugin development :)
=> Add media-src CSP to middleware

src/requirements/dev.txt, src/setup.py
Following the setup instructions resulted in the following error message:
```
pip3 install -r requirements.txt -r requirements/dev.txt
[...]
flake8 3.6.0 has requirement pyflakes<2.1.0,>=2.0.0, but you'll have pyflakes 1.1.0 which is incompatible.
```
**Fix:**
Pretix doesn't version pin flake8, but it's two requirements pep8 and pyflakes.
The current release flake8 3.6.0 (http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html#new-dependency-information) updates the version requirements for pyflakes and pycodestyle (former pep8).
I've transfered the version range into setup.py and requirements/dev.txt.
I am now able to rerun the dev-setup tutorial without errors.
=> Updates the dependency versions for flake8

src/pretix/base/payment.py
Hi there!
Thanks for the awesome project - coming from conftool, pretix is a joy to use. We encountered one issue where manual payment instructions were not displayed because ManualPayment still implements the pretix 1.x API. This PR should rectify this. 😃
=> Fix payment instruction display.

src/pretix/base/templatetags/rich_text.py, src/pretix/presale/templates/pretixpresale/event/index.html
The frontpage text is already markdown, and will receive its formatting via the rich_text filter.
When applying the additional linebreaksbr filter, it will add unnecessary blank lines.
I'm using the hosted pretix version. 
Test for frontpage text: 
````
Test 
* test1
* test2
````
Before (screenshot): 
---
----
After (screenshot): 
----
----
=> Enable nl2br plugin for Markdown rendering

src/pretix/control/logdisplay.py, src/pretix/control/templates/pretixcontrol/organizers/team_members.html, src/pretix/control/views/organizer.py, src/pretix/static/pretixbase/scss/_theme.scss, src/tests/control/test_teams.py
The functionality is working, but it currently looks horrible, because the button gets rendered as a button (without any styling). It should be possible to remove the button styling, but that would probably require custom CSS for that single case. I thought it would be nice to have the resend functionality close to the envelope icon indicating, that an invite is still pending. Alternatively one could embrace the button being a button and style it like the "remove" button on the right and also move it to the right.
=> Fix #1247 -- Allow team invites to be resent

src/pretix/api/serializers/order.py, src/pretix/api/views/order.py, src/pretix/base/services/orders.py, src/pretix/control/forms/orders.py, src/pretix/control/templates/pretixcontrol/base.html, src/pretix/control/templates/pretixcontrol/order/change.html, src/pretix/control/views/orders.py, src/pretix/static/pretixcontrol/js/ui/orderchange.js, src/pretix/static/pretixcontrol/scss/_forms.scss, src/tests/api/test_orders.py, src/tests/api/test_permissions.py, src/tests/base/test_orders.py, src/tests/control/test_orders.py
This basically does two things to the "Change products" view of orders and the
OrderChangeManager program API:
1) It decouples changing items or subevents from changing prices.
OrderChangeManager.change_item() and .change_subevent() no longer
touch the price of a position. Instead .change_price() needs to be
called explicitly. However, a client-side JavaScript component now
*proposes* a new price based on the changed item or subevent.
2) The user interface now exposes the possibility of doing multiple
things at the same time, i.e. changing the item, subevent and price
in the same operation. OrderChangeManager already allowed this
before.
(1) is basically a consequence of (2), while (2) is a prerequesite for
e.g. the `seating` branch, where changing the subevent will always
require …
=> Change semantics of changing orders

doc/development/setup.rst
otherwise in the next step I get
```
$ python3 -m venv env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
apt-get install python3-venv
```
=> Document Debian dependency python-venv

doc/development/setup.rst
otherwise I get
```
ERROR: Complete output from command python setup.py egg_info:
ERROR: Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-jq5wwsqg/pyenchant/setup.py", line 212, in <module>
import enchant
File "/tmp/pip-install-jq5wwsqg/pyenchant/enchant/__init__.py", line 92, in <module>
from enchant import _enchant as _e
File "/tmp/pip-install-jq5wwsqg/pyenchant/enchant/_enchant.py", line 145, in <module>
raise ImportError(msg)
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jq5wwsqg/pyenchant/
```
when running
` pip3 …
=> Add external dependency libenchant1c2a

src/pretix/presale/templates/pretixpresale/event/index.html
in templates/pretixpresale/events/index.html
Hey there!
I noticed that this closing anchor tag is not necessary and probably left over from some template refactor. 
So I thought I'll remove it :)
Thanks for working on pretix, it's really cool!
=> rm superfluous closing anchor

doc/admin/config.rst, src/pretix/control/middleware.py, src/pretix/control/templates/pretixcontrol/user/2fa_main.html, src/pretix/settings.py, src/tests/control/test_auth.py
This is a very quick hack for enforcing the usage of 2FA for backend-users.
I burried the setting in the pretix.cfg, as most users probably won't ever have a need to turn this on.
This hooks into the middleware and basically disallows access to any URL other than the 2FA-related ones, login and logout, if obligatory 2FA is set and the user hasn't enabled it yet.
=> Add setting for enforcing 2FA

doc/development/setup.rst
The script to generate the test data and the instructions how to import it were removed in `e55f0cdf11f914b31a51f5a7ddffbde4b7394237`.
=> Remove obsolete reference to test data

src/pretix/plugins/stripe/views.py
In our logs, I found regular errors like these:
```
File "/src/pretix/src/pretix/plugins/stripe/views.py" in webhook
170.         rso = ReferencedStripeObject.objects.select_related('order', 'order__event').get(reference=objid)
File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py" in get
408.                 self.model._meta.object_name
During handling of the above exception (ReferencedStripeObject matching query does not exist.), another exception occurred:
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
34.             response = get_response(request)
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
115.                 response = self.process_exception_by_middleware(e, request)
File …
```
=> Fix issue on old-style webhook URLs

doc/development/api/shredder.rst
The `BaseDataShredder` documentation contains two references to `BaseInvoiceRenderer`, probably due to a minor copy/paste mistake from `doc/development/api/invoice.html`.
See https://docs.pretix.eu/en/latest/development/api/shredder.html#pretix.base.shredder.BaseDataShredder
=> Fix BaseDataShredder class documentation

Dockerfile
The Dockerfile does not actually install pretix into the python system-site-packages, which causes problems when trying to subsequently install plugins which depend on pretix.
=> Install pretix into system-site-packages in Docker image

src/pretix/base/exporter.py
The file type suffix is appended here
https://github.com/pretix/pretix/blob/9fca3188b29df9b79e3adaa3aa20af3101231338/src/pretix/base/exporter.py#L121
so at the moment there are filenames like `export.csv.csv`.
=> remove .csv from default filename in List Exporter

doc/development/api/general.rst, src/pretix/base/models/orders.py, src/pretix/base/signals.py
Since we are starting to have more and more plugins which have reference orders and can thus inhibit deletion of test-mode orders, I'd like to propose a new `order_gracefully_delete` signal.
It will get send out as part of the `gracefully_delete()` and gives plugins an opportunity to remove all external dependencies when necessary.
This is probably cleaner than having a bunch of checks in `gracefully_delete()` to see if a specific plugin is installed/enabled.
Thoughts?
=> Add order_gracefully_delete signal

src/pretix/plugins/sendmail/forms.py, src/pretix/plugins/sendmail/tasks.py, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/history.html, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/send_form.html, src/pretix/plugins/sendmail/views.py, src/pretix/static/pretixcontrol/js/ui/main.js, src/tests/plugins/test_sendmail.py
This PR adds the ability to send mass emails to all attendees who have checked in (with the ability to filter for specific checkin lists). This is sort-of what was asked in #1369 (It is not possible to filter for users who never checked in)
=> Sendmail plugin: Allow filtering for check-ins

src/pretix/control/views/typeahead.py
Whitespace is often added when you copy/paste order or voucher codes
=> Ignore whitespace on typeahead queries

src/pretix/base/services/invoices.py, src/pretix/plugins/paypal/payment.py
This is a PoC for displaying the PaymentID on paid invoices for PayPal.
Technically, this is just calling the `render_invoice_text` also on paid invoices, which we didn't before.
If this change is any good, we should probably also look into implementing similar printouts for Stripe and Mollie.
=> PayPal: Show payment ID on paid invoices

doc/admin/installation/docker_smallscale.rst
There is a missing dot in the docker command to create a custom build with plugins. Inserted that missing dot.
Should be `docker build . -t mypretix` instead of `docker build -t mypretix`
=> missing dot in docker command

src/pretix/base/channels.py, src/pretix/base/payment.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/payment.html, src/pretix/control/views/event.py, src/pretix/presale/checkoutflow.py, src/tests/control/test_events.py
This adds a Sales-Channels Multi-Select to each Payment Provider, allowing the user to restrict the usage of said Payment Provider to specific sales channels.
Backwards compatibility:
If no setting is saved, the system assumes the `web`-sales channel as enabled, not breaking anything for existing events.
However, upon next editing of the Payment Provider Settings by the user, the field is required, forcing the user to actively select which sales channels the payment provider should be enabled for. (Positive?) side effect: The user cannot configure a payment provider to be enabled but not approved for any sales channel.
Also changes `is_implicit` from a property to a method which gets the `request` passed. Legacy-compatibility should be provided by the changes.
=> Restrict Payment Providers to Sales Channels

doc/development/api/general.rst, src/pretix/base/signals.py, src/pretix/plugins/ticketoutputpdf/signals.py, src/pretix/plugins/ticketoutputpdf/ticketoutput.py
New signal that allows plugins to override the layout that the PDF-ticketoutput is using.
=> New signal: ticketoutput_override_layout

src/pretix/static/pretixpresale/js/widget/widget.js
Currently the waiting list button of the widget does not send the widget_data to the server. Meaning that after successfully registering in the waitinglist, the cart session will not contain the widget data.
We'd like the widget data to be available, as this is the way we pass meta data of the user to the pretix application. Our plugin will save additional information in the database depending on the widget data in the cart session.
=> Send widget_data when opening waiting list

src/pretix/api/serializers/voucher.py, src/pretix/base/models/items.py, src/pretix/base/models/vouchers.py, src/pretix/control/forms/vouchers.py, src/tests/api/test_permissions.py, src/tests/api/test_vouchers.py, src/tests/base/test_models.py
This was requested to allow e.g. a global 20% discount across all (sub)events. Of course, it's not really useful once you have products that require a voucher, but there are enough people using pretix without this constraint.
=> Allow to create vouchers for *all* products

src/pretix/base/forms/auth.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/delete.html, src/pretix/control/templates/pretixcontrol/shredder/download.html, src/pretix/control/templates/pretixcontrol/user/reauth.html, src/pretix/control/views/event.py, src/pretix/control/views/shredder.py, src/tests/control/test_events.py, src/tests/control/test_permissions.py, src/tests/control/test_shredders.py
Adds possibility for reauthenticating backends with authentication_url auth method. Additionally replaces all seperate password checks with recent authentication required.
=> Fix #1521 -- External authenticated users cannot delete events

doc/api/resources/questions.rst, src/pretix/api/serializers/item.py, src/tests/api/test_items.py
Hi there! We are using the API to show the list of questions and I notice that the help text is missing, this PR adds that and adds a test for it as well :)
=> Expose help texts on questions' API

src/requirements/production.txt, src/setup.py, src/tests/api/test_oauth.py
Over the holidays, I (very dirtily) hacked together a google oauth login backend (which, although secure, is not ready for release yet). To use the python libraries provided by google to handle the oauth flow, I needed to bump the oauthlib version.
As far as I can tell, this should not introduce any logic changes; however within the tests I noticed that newer oauthlibs return 400 Bad Request instead of 401 Unauthorized. I don't really know if the tests use the library wrong or if this behavior change is intentional. I fixed the tests to expect 400 Bad Request in a second commit, but somebody should probably look at that further. It should have no impact on the flow that's being tested here.
=> Bumped oauthlib to ==3.1.*

src/pretix/base/pdf.py, src/pretix/control/templates/pretixcontrol/pdf/index.html, src/pretix/static/pretixcontrol/js/ui/editor.js
=> Improve text rendering options in PDF editor

src/pretix/control/forms/event.py
When no payment term is required, some users set this field to a very high value. This produces an "internal error" when a customer creates an order (`timedeltas` can only store up to 999999999 days, `date(time)s` only store until the year 9999). This PR limits the field to 1 million days which is still more than 2700 years.
=> Limit Payment Term Days Field

src/pretix/base/pdf.py
We want unescaped values for the checkin apps.
=> Force-escape all PDF values on the renderer level

deployment/docker/nginx.conf, doc/admin/installation/docker_smallscale.rst
Currently the first Scaling Problem you run into while hosting the Small Scale Docker Setup is the sysctl Setting of maximum parallel Socket Connections which defaults to 128.
This means after 128 parallel connections the nginx starts replying with 502 Errors.
If you increate this Limit the next Problem will be the 768 Worker Connections of nginx.
To solve both of these Issues this Pullrequest sets them both to a Value of 4096.
=> Solve some Docker Setup scaling issues

src/pretix/base/models/orders.py, src/pretix/control/forms/__init__.py, src/pretix/control/views/orderimport.py
This takes care for situations when buyers upload files with capital letters in the extension (like .JPG); I suppose this is common on Windows OS.
I found this first when buyers uploaded images to questions that ended with .JPG. I browsed the code and found that this is in orders.py
I looked further and found two other places that looked similar. 
As I currently don't have a working python setup I was unable to test this change locally. I would be grateful if a reviewer could test it. 
If this is not possible, please let me know and I'll setup a VM with a python environment.
=> Comparison for file extensions should be case insensitive

doc/development/api/general.rst, src/pretix/base/services/checkin.py, src/pretix/base/signals.py, src/pretix/control/views/checkin.py
Plugins might need this signal to trigger own processes when a user is checked in. One example might be sending a greeting email or activating features on-site. This PR sends a signal when creating a new checkin.
I have two questions regarding this change:
1. Do you think the signal should also be send if a user is force-checked-in? (https://github.com/pretix/pretix/blob/master/src/pretix/base/services/checkin.py#L152)
2. Does the signal need to be added to the documentation on other places?
=> Send signal on checkin

src/pretix/api/serializers/event.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/organizers/index.html
When enabled, the date-block will be completely removed from the ticketshop start page and the (public) organizer list view.
In the backend, the date-block is always displayed, no matter the setting.
=> Option to hide date-block on frontpage

src/pretix/api/serializers/item.py, src/tests/api/test_items.py
When creating a new question via the API and sending
```
"dependency_question": null,
```
which even the pretix documentation does[1], the API responded with a 400 Bad Request error. This was caused by the serializer checking that the dependency value is not the same as `self.instance`. However `self.instance` is `None` is the object is created not updated[2]. I moved the check inside the section that checked that `value` is not `None` and added recursion tests.
[1]: https://docs.pretix.eu/en/latest/api/resources/questions.html#post--api-v1-organizers-(organizer)-events-(event)-questions-
[2]: https://www.django-rest-framework.org/api-guide/serializers/#accessing-the-initial-data-and-instance
=> Allow creating question with dependency_question=None

src/pretix/static/pretixpresale/js/widget/widget.js
When the checkout process on mobile starts with redeeming a voucher the widget data is not sent. This change adds a hidden field which sends adds the widget data in de GET request, similar to the pretix-button variant of the widget. See [src/pretix/static/pretixpresale/js/widget/widget.js#1047](https://github.com/pretix/pretix/blob/359c46b8e28c8c5e61bedceb6c1723f5ce313b79/src/pretix/static/pretixpresale/js/widget/widget.js#L1047) for reference.
=> Send widget_data in voucher redeem request.

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html
If the "items per order" limit is 1 but the items to not have a limit set a number input field is shown instead of a checkbox. The new code is identical to that is already done in the `voucher.html`-template
=> Show checkbox if items per order limit is 1

src/pretix/control/templates/pretixcontrol/events/create_base.html
`django-formtool`s `SessionWizardView`does not store the entered form if "wizard_goto_step" is used[1]. Therefore it is not needed to validate the data, which currently lead to confusion when we tried to create an event but wanted to change things in the previous step.
[1]: https://django-formtools.readthedocs.io/en/latest/wizard.html#formtools.wizard.views.WizardView.render_goto_step
=> Do not validate event creation form on back button

src/pretix/api/serializers/fields.py, src/pretix/base/settings.py, src/tests/api/test_events.py
The rest frameworks `serializers.MultipleChoiceField` `to_internal_value` functions returns a set instance[¹]. hierarkey did not like that which lead to internal server errors. Since the code generally assumes that the value of those fields is a list I subclassed MultipleChoiceField so that it now returns a `list` and added a test for that
[¹]: https://www.django-rest-framework.org/api-guide/fields/#multiplechoicefield
=> Subclass MultipleChoiceField to serialize to list

src/pretix/base/auth.py, src/pretix/control/views/auth.py, src/pretix/control/views/user.py, src/tests/control/test_auth.py, src/tests/testdummy/auth.py
This is a proposal for a fixing #1586. Pretix ever only checks the 'next' GET parameter, however redirect based authentication methods like OAuth use custom named parameters. In case of OAuth this `state`.
I've added additionally functionality to the authentication backend to select the next URL based on the backend used. The default backend and thus all other backends still uses 'next', however my custom backend will be able to implement it using a different parameter name.
=> Make next url authentication backend dependent

doc/admin/installation/docker_smallscale.rst
Add missing "\" to sample for service configuration when using docker as deployment strategy
=> Fix sample service config

src/pretix/plugins/badges/exporters.py, src/tests/plugins/badges/test_pdf.py
When the number of badges was not a multiple of the badges per page, the last few badges were not rendered. This PR produces badge pdfs where the last page has some empty slots.
=> Render remaining badges onto new page even if it doesn't fill the page

src/pretix/base/models/event.py, src/pretix/base/signals.py
The signal already sends a map of tax, category, item etc ids to their new items but not for checkin lists.
=> Send checkin list mapping in event_copy_data signal

src/pretix/base/services/cancelevent.py, src/pretix/control/forms/orders.py, src/pretix/control/templates/pretixcontrol/orders/cancel.html, src/pretix/control/views/orders.py
Also fixes missing `manual_refund`-property in call to cancellation-task.
=> Allow to issue gift card refunds when cancelling whole events

src/pretix/plugins/stripe/urls.py
- Expose `apple-developer-merchantid-domain-association` on `event_patterns`: Since we now also have event-specific domains, Stripe needs to be able to access the ApplePay domain assoociation verification file at that domain.
- ~Add testmode-functionality for non-connect users~ On second thought: nah... not today
=> Expose apple-developer-merchantid-domain-association on event_patterns

src/pretix/control/forms/filter.py, src/pretix/control/templates/pretixcontrol/search/orders.html, src/pretix/control/views/search.py
Basically, copy/paste from the order search.
Perhaps just pay specifically attention if this works as intended (`.using()`-statement in conjunction with the annotation: 
https://github.com/pretix/pretix/blob/4b01c42f3193f8083d106139c56e20798b7bef1b/src/pretix/control/views/search.py#L33-L34
=> Improve global order filters

src/pretix/api/views/item.py, src/pretix/base/exporters/orderlist.py, src/pretix/base/models/event.py, src/pretix/base/models/items.py, src/pretix/base/services/cart.py, src/pretix/base/services/orders.py, src/pretix/base/services/quotas.py, src/pretix/control/templates/pretixcontrol/items/quotas.html, src/pretix/control/views/dashboards.py, src/pretix/control/views/item.py, src/pretix/control/views/main.py, src/pretix/control/views/subevents.py, src/pretix/presale/views/event.py, src/pretix/presale/views/organizer.py, src/tests/base/test_models.py
This PR refactors quota computation. Instead of methods on the ``Quota`` method, there's now a dedicated ``QuotaAvailability`` for this task. The difference is that the new code is designed to calculate the capacity for multiple quotas *at once*.
Simply speaking, instead of a ``SELECT COUNT(*) FROM orders WHERE event = x AND item = y``, the code now does a ``SELECT COUNT(*), event, item FROM orders GROUP BY event, item`` and then interprets the result Python-side.
This is intended to **massively** speed up many of our critical code paths that are currently slow for some relevant edge cases, such as:
- The list of (sub)events in the shop
- The list of products in an event on the shop frontpage
- The list of (sub)events in the backend
- The list of quotas in the backend
- The backend …
=> Refactor quota calculation

src/pretix/plugins/badges/exporters.py
https://www.herma.de/buero-zuhause/produkt/textil-namensetiketten-a4-special-4412/
I couldn't test it on real paper, but the output aligns perfectly with the template provided by HERMA: https://www.herma.de/fileadmin/Buero-Zuhause/downloads/Stanzvorlagen/4412_SV.pdf
=> Support HERMA Namensetiketten 50x80mm (4412)

src/pretix/base/forms/questions.py, src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/urls.py
To avoid confusion in a reverse charge setting we don't want to ask companies that are not in the European Union for the VAD ID. Maybe it would be better, to make this a setting, but I don't have a good idea how to do it.
=> Ask only for VAT ID if company is inside EU

doc/admin/installation/docker_smallscale.rst, doc/admin/installation/manual_smallscale.rst
Django dropped support for postgres 9.4 in Django 3.0 [1]. Operating pretix with a postgres 9.4 or smaller leads to internal server errors.
[1]: https://code.djangoproject.com/wiki/SupportedDatabaseVersions#PostgreSQL
=> Add minimum postgres version to docs

src/pretix/base/views/mixins.py, src/pretix/control/templates/pretixcontrol/item/include_addons.html, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html, src/pretix/static/pretixpresale/js/ui/main.js
I added data attributes to make it easy to get the correct source and target inputs. It works the following now:
* For products, the "copy answer" button copies answers from the first products answers down to the product and addon questions where the button is positioned.
* For addon products, the "copy answer" button copies answers from the addon's main product down to the addon.
It's somewhat sensible in the way that it is hierarchical, but I don't love that they behave differently. What do you think? 
TODO:
=> Copy answers button for addon products

src/pretix/base/services/orders.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/mail.html
Z#2361977 requires a dedicated approval email for free orders, as they cannot repurpose the existing "Free Order" eMail-template.
I don't expect any issues merging this for a function POV.
However, in order to not annoy our hosted customers from Germany, we should probably deploy it only once the German translations for this have been merged, too.
Casus Knacksus @raphaelm: Is this something, we can merge and deploy without writing a migration, which duplicates the existing `mail_text_order_free` into the new `mail_text_order_approved_free` for existing events in order to conserve the current mail templates?
=> Add eMail-Template for free approval orders

src/pretix/base/email.py, src/pretix/base/services/notifications.py, src/pretix/base/settings.py, src/pretix/settings.py
Thought about making it a variable for `pretix.cfg`, but as the color would need to be changed in many CSS places, too, I considered it more of a constant.
=> Refactor primary color to settings variable

src/pretix/base/services/mail.py
When building a plugin, people might want to use the already existing mail infrastructure to send mails.
Currently, it is not possible to send attachments using pretix' mail system. This PR tries to solve that by allowing callers to attach cached files, which might need to be created solely for attaching a file to a mail. This is necessary, because pretix uses distributed celery workers, so we cannot just give plain file/content (also mail_send task's arguments are JSON-serialized).
=> Mail service: Allow to attach arbitrary cached files

doc/admin/config.rst, src/pretix/settings.py
Introduce [pretix]:loglevel configuration option. This allows the loglevel to be set. Valid values are: DEBUG, INFO, WARNING, ERROR and CRITICAL.
Fixes #1127
=> Fix #1127 -- Set loglevel from configfile

src/requirements/production.txt, src/setup.py
libsass 0.19.2 fails to install under latest OS X Catalina. As https://github.com/sass/libsass/issues/3053 seems to be fixed, bump to current version 0.20.*
=> Bump libsass-version to 0.20.*

src/pretix/base/services/mail.py, src/pretix/plugins/sendmail/forms.py, src/pretix/plugins/sendmail/tasks.py, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/send_form.html, src/pretix/plugins/sendmail/views.py
This allows to attach a file to emails send out by the sendmail plugin.
Current limitations:
- only allows for 1 attachment
- the attachment is the same for all languages
=> Sendmail plugin: Allow to attach a file to emails

src/pretix/base/models/items.py
Fix a small typo in the help text of `allow_waitinglist`
=> Small typo in help text

src/pretix/presale/ical.py, src/tests/presale/test_event.py
in pretix, end-date is inclusive (last day) whereas in ics end-date is non-inclusive. Add 1 day to end-date for full-day events in ical-export
=> Fix iCal export for full-day events (DTEND is non-inclusive)

src/pretix/base/exporters/__init__.py, src/pretix/base/exporters/waitinglist.py
I copied the basic queryset for the WaitingList from `pretix/control/views/waitinglist.py:113`. I am not sure whether I really need to `prefetch_related`. It worked without, so it should probably be removed.
=> Added export of WaitingList for single and mutliple events with filter for voucher-status

src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/settings.html
This is a UI/UX variant for the event settings. For each combination of _asked and _required fields, one ChoiceField is created and set. The more I look at it, I am torn and not so sure, whether this is the better UX – for me, the settings are easier to grasp with the table of checkboxes. But setting it to „Do not ask“ is more clear and understandable with the <select> than with unticking both boxes. Also one select is easier in the front-end as no logic is needed to keep the checkboxes in sync.
Currently the combined ChoiceField uses the label and help_text of its _asked-field. I am not sure, whether this is the best solution.
=> Added combined radiob uttons for <name>_asked and <name>_required fields

doc/admin/installation/docker_smallscale.rst, doc/development/api/customview.rst, doc/development/api/email.rst, doc/development/api/exporter.rst, doc/development/api/invoice.rst, doc/development/api/payment.rst, doc/development/api/placeholder.rst, doc/development/api/plugins.rst, doc/development/api/shredder.rst, doc/development/api/ticketoutput.rst, doc/development/implementation/background.rst, doc/development/implementation/i18n.rst, doc/development/implementation/logging.rst, doc/development/implementation/permissions.rst, doc/development/implementation/settings.rst
I enabled syntax highlighting in the docs and fixed some small typo errors
=> Docs: Enabling Syntax Highlighting

src/pretix/control/urls.py, src/tests/control/test_events.py
Calling https://pretix.eu/control/event/uberspace/ (obtained by stripping the event name off) currently yields a 404. This implementes a redirect to https://pretix.eu/control/organizer/uberspace/ instead.
=> Add convenience redirect …/event/(org)/ => …/organizer/(org)/

src/pretix/control/templates/pretixcontrol/event/live.html
Using the `event_live_issues` we can prevent an event from going live with all kinds of checks. However once it is set live, these issues are no longer showing. When changes are made to settings of the event, new live issues could arise. I'd like to show these live issues on the live page, so users can see them:
In our plugin we have added a custom `event_dashboard_widgets` based on the `shop_state_widget`, I've not included the widget in this MR, as I wasn't sure on whether you'd want to have it for all events. Let me know if you'd like for me to add the widget as well:
=> Show "live issues" when event is already live

src/pretix/base/services/shredder.py, src/pretix/base/shredder.py, src/pretix/control/templates/pretixcontrol/shredder/download.html, src/pretix/control/views/shredder.py
Using this PR, I'd like to start the discussion on a potential solution to #1758. At our association we process a lot of personal data in Pretix, which is done by many volunteers. We try to take good care of personal data of our members, however when executing the data shred process all this personal data has to be downloaded to personal computers, resulting in a loss of control.
I've currently left the download file generating in, depending on how we'd like this to work I can adjust and expand the implementation.
Please let me know what you think.
=> Shredder: Only force download for tax-relevant data

src/pretix/base/exporters/orderlist.py, src/tests/api/test_exporters.py
Currently, the export of orderlines creates one column per possible answer of a mulitple choice question containing Yes/No.
This pull request introduces a new optional checkbox field to choose grouping these answers in a single column of the order line instead. It will use the question title as column header (instead of question title followed by the answer like it is done in the existing export) and all selected answers for each row as comma-separated list (each comma is followed by a blank as this export format is mainly intended for manual parsing/reading).
The feature is introduced as code change instead of a separate plugin to prevent large amounts of code duplications.
Additionally, one API test was slightly adjusted to support the new option.
=> Add option to export multiple choice answers in orderlists grouped

src/pretix/base/models/orders.py, src/pretix/control/forms/orders.py
There is a typo in the documentation of OrderRefund.done(user, auth). It is written "param user" twice, where in the second it should be "param auth".
UPD: There is another typo in the label.
=> Documentation typo fix

src/pretix/presale/forms/renderers.py, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
As the * is added via CSS-content, which is not visible to screen readers, and also is mainly a visual indicator, that when read aloud is distracting, I added the text „required“ to the label of required inputs in presale-checkout.
See here for reasoning: https://www.a11y-101.com/development/required
Copied and adapted from src/pretix/control/forms/renderers.py
=> [a11y] Add text "required" to label of required inputs

src/pretix/control/templates/pretixcontrol/subevents/index.html, src/pretix/static/pretixcontrol/js/ui/main.js
This adds several improvements to bulk-select:
- buttons are now colored, especially the delete button has a .danger-class
- added icons to buttons
- buttons are disabled, if no row is selected
- checkbox to select all results on all pages is only available if results span more than one page
=> Bulk action improvements: buttons (wording, color, icons, disabled-state), hide select-on-all-pages if only one results-page

src/pretix/control/templates/pretixcontrol/event/fragment_geodata.html, src/pretix/control/templates/pretixcontrol/event/fragment_geodata_autoupdate.html, src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/control/templates/pretixcontrol/events/create_basics.html, src/pretix/control/templates/pretixcontrol/subevents/bulk.html, src/pretix/control/templates/pretixcontrol/subevents/bulk_edit.html, src/pretix/control/templates/pretixcontrol/subevents/detail.html, src/pretix/static/pretixcontrol/js/ui/geo.js, src/pretix/static/pretixcontrol/scss/_forms.scss
This changes the current behavior, that overwrites geo coordinates automatically as long as the coordinates were empty at some point during the edit process and haven’t been changed manually since. If manual changes to the coordinates have been made and the location is changed later on, this now shows a message asking to overwrite the existing/manually adjusted geo coordinates.
It’s currently a bit _jumpy_ as, when the message is shown, it pushes down the rest of the form below. Not sure if we should add slideDown/slideUp-animation.
=> Geo fields: Allow overriding existing values

src/pretix/base/payment.py
When I use manual payment, I would like to show texts to my customers with the pending amount rather than the total of the entire order, e.g., "Please transfer {amount} to account XXX", which was not previously possible because pretix only provided placeholder for the total of the order.
This would be useful for customers who redeem gift card for partial payment to the order, and then choose manual payment to pay for the rest of the order.
However, I have one failed test [located at this line](https://github.com/pretix/pretix/blob/master/src/tests/control/test_mail_settings_preview.py#L317) I would like you guys to take a look at, because I'm not sure why it failed.
=> Manual payment: Add amount placeholder

src/pretix/presale/forms/renderers.py, src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/templates/pretixpresale/event/order.html, src/pretix/static/pretixpresale/js/ui/main.js
This PR adds the following:
- form errors are linked to input with aria-describedby
- add validation-hints to labels with text (e.g. "… has errors" or ".. is valid")
- makes toggle-link for "view other date" focusable
- toggle text "required" on labels when input dependencies change via JavaScript
- make "modify"-links in checkout more descriptive
=> [a11y] Improved form error messages, descriptive labels, focusable toggle-link

src/pretix/base/forms/questions.py, src/pretix/presale/forms/renderers.py
This fixes some accessibility problems regarding form widgets with multiple inputs (input groups).
- group inputs from `CheckboxSelectMultiple`, `RadioSelect` and `MultiWidget` with more than 1 widget together with `role=group` and `aria-labelledby` as described here: https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria
- add aria-label to every sub-input in `NamePartsWidget` and `WrappedPhoneNumberPrefixWidget`
=> A11y: add role=group and labels to multi-widgets

src/pretix/plugins/checkinlists/exporters.py
I was getting this formatting error when exporting a checkin list as pdf for a single subevent.
[Blame](https://github.com/pretix/pretix/blame/master/src/pretix/plugins/checkinlists/exporters.py#L279)
=> Fix checkin-list pdf export subevent time formatting

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/static/pretixpresale/scss/_event.scss
Ok, so this alignment issue on the frontpage (eg text of "resend email" not aligned with its headline) has been bugging me for YEARS, but I thought there was no clean way out: Removing the padding from the "resend email" section would mis-align the button with the cart button, and removing the padding from everywhere would screw with the responsiveness. After a new customer just got pretty annoyed about this on a call, I decided to try again.
I needed some CSS hacks with ::before and ::after to make all borders look good, but I think the end result is pretty okay.
=> Clean up alignment on shop page

deployment/docker/nginx.conf
Small change to remove warning noise from logs:
```sh
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/nginx.conf:43
```
http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types 
```sh
Enables gzipping of responses for the specified MIME types in addition to “text/html”. The special value “*” matches any MIME type (0.8.29). Responses with the “text/html” type are always compressed.
```
=> Remove redundant mime-type from nginx config

src/pretix/control/views/global_settings.py
The license finder assumes that installed packages are in `.egg` or `.egg-info` format and does not consider `.dist-info` packages, which uses the `METADATA` field for package info. See [pkg_resources.DistInfoDistribution](https://github.com/pypa/pip/blob/main/src/pip/_vendor/pkg_resources/__init__.py#L3000) for reference.
=> License check: improve license detection for DistInfoDistribution packages.

doc/api/resources/checkinlists.rst, src/pretix/api/views/checkin.py, src/pretix/base/models/checkin.py, src/pretix/base/services/checkin.py, src/pretix/helpers/jsonlogic_boolalg.py, src/tests/base/test_checkin.py, src/tests/helpers/test_jsonlogic_boolalg.py
While our custom check-in logic is very flexible, its main problem is that is is pretty intransparent during execution. If the logic causes an entry to be forbidden, the result of the logic evaluation is just a simple ``False``, which is very unhelpful to explain to attendees why they don't get into the event.
The main problem with fixing this is that there is no correct answer for this, it is always up for interpretation. A good example is the following set of rules:
- Attendees with a regular ticket can enter the venue between 09:00 and 17:00 on three days 
- Attendees with a VIP ticket can enter the venue between 08:00 and 18:00 on three days
If an attendee with a regular ticket now shows up at 17:30 on the first day, there are three possible error messages:
a) You do not have a VIP …
=> Check-in rules: Make logic results understandable

src/pretix/control/views/typeahead.py
The first commit should fix PRETIXEU-46C.
The second commit is up for debate - I just stumbled upon this and figured that if we are working with variations, this should probably reflect the variations state and not the items state.
=> Add missing "deactivated"-property for items-typeahead

src/pretix/base/models/event.py, src/pretix/control/views/event.py, src/pretix/control/views/main.py
Use the `event.set_active_plugins` to set the plugins to make sure that the installed function gets called for all plugin enable routes.
Note that in this commit all calls are made with `allow_restricted`, as there may be existing restricted plugins enabled for the copied event.  This is fine these locations do not accept user input to select plugins, they come from existing events or from the system configured django settings.
Fixes #2087
=> Call plugin's installed() method upon event creation

doc/admin/installation/manual_smallscale.rst
Debian 10 is shipping with Python 3.7 so the Debian 10 based and tested guide should use Python 3.7 in the nginx config.
=> Docs: Update Python Version in Nginx Config

doc/api/resources/events.rst, src/pretix/api/views/event.py, src/tests/api/test_events.py
The events API is paginated with 50 events. When searching for a specific event within a large Pretix installations UX becomes very bad. Using this filter users are able to quickly find their event by name.
=> Event API: Add search parameter

src/pretix/control/views/subevents.py
Previous fix was in the wrong spot – instead of heckin-lists it had to go into quotas.
=> fix ignore_for_event_availability for batch edit of subevents

doc/admin/config.rst, src/pretix/settings.py
Adds the `enabled` setting to the `[languages]` table in the pretix.cfg.
If left empty, or  omitted all languages are enabled.
Updates #2105
=> i18n: add config for enabling a set of languages

src/pretix/control/templates/pretixcontrol/waitinglist/index.html, src/pretix/control/views/waitinglist.py
Batch selection of waitinglist entries was not working due to missing entry-ids. Download of a waitinglist used a generic name waitinglist.csv – changed to reflect the behaviour when using the export functionality.
=> Fix waitinglist batch selection, add event.slug to download-filename

src/pretix/control/views/orders.py
This should fix error 49419. When exporting orders aysnc, the key „exporter“ is not available in `POST` (as the check-url is called via `GET`). Add exporter-identifier to check-url and make `@cachedproperty exporter` look for it based on `request.method`.
Please note: I could not figure out how to test this fix. Any hint how to force async behaviour for export would be appreciated.
=> Exporters: Fix crash in error url determination

src/.gitignore, src/pretix/api/serializers/settings.py, src/pretix/base/email.py, src/pretix/base/services/mail.py, src/pretix/base/services/notifications.py, src/pretix/settings.py, src/setup.cfg, src/setup.py
* This adds drf-ujson for faster JSON serializing/deserializing in the API. The effect on a single request is so little I couldn't measured it. The effect on production in total could still be significant and there's barely any cost in complexity.
* This replaces ``inlinestyler`` with ``css_inline``. In my very non-scientific tests I can confirm that this *significantly* improves email rendering. The benchmarks in the css_inline README claim a speedup of ~x100, which seems plausible. This could significantly reduce load on our email sending threads. The cost is that it makes us depend on a rust toolchain. There's no change for most users, since there are pre-built wheels on PyPI, but everyone running pretix on e.g. arm architectures will need a rust compiler and build it themselves.
=> Performance: Replace inlinestyler with css_inline; Add drf-ujson

src/pretix/control/forms/event.py, src/pretix/control/views/main.py
With b260cca412df43d6e47d4d574cb2e5132399c2c0, team provisioning has been disabled for users that are staff. However, this leads to strange UX, as a new event created by a staff member, not currently in a staff session, resulted in a 404 directly after creation.
This PR updates this requirement to not need to select a team, only when a staff session is active.
=> Event setup: do not create new team when staff session active

src/pretix/control/views/main.py
With #2089, PluginConfig.installed() is also called for newly created events. However, the passed event argument is still not committed. The plugins cannot use the event to insert or select objects, as it does not have an ID yet.
=> Event creation: call plugin installed() after persisting event

src/pretix/base/context.py, src/pretix/presale/views/widget.py
When the `<pretix-widget>` was hosted on a separate domain, the source code URL was pointing to the wrong page. This updates the URL to always point to the Pretix installation.
=> Widget: Use absolute URL for poweredby URL

src/pretix/base/services/mail.py, src/pretix/base/templates/pretixbase/email/simple_logo.html, src/pretix/helpers/thumb.py, src/tests/helpers/test_thumb.py
Email-Template simple_logo.html had a mso-specific comment, which basically removed the header image in MS Outlook clients. I also optimized the html header to the settings recommended on [campaignmonitor](https://www.campaignmonitor.com/blog/email-marketing/correct-doctype-to-use-in-html-email/) and [emailonacid](https://www.emailonacid.com/blog/article/email-development/which-code-should-i-include-in-every-email/).
To make the HTML-email more robust and responsive (ie not that small on smartphones when using a full-width header image), I changed the header-image to always have 600px width – for this to work with smaller images, they need to be padded to 600px width. Therefore I added a new scaling operator: `_` for the size-argument of the thumb-filter in django-templates. …
=> Email: make responsive and show header image in MS Outlook

src/pretix/plugins/paypal/payment.py
Z#2378438
This PR addresses the following issues:
- Adding a postfix-field in addition to the already existing prefix-field
- Passing the `{prefix}{event}-{code}{postfix}`-construct to PayPal's `transaction.custom`-field for use in settlement reports.
- Rework all transfer reason fields and similar to also include the postfix
Semi-Breaking changes:
- So far, when a prefix was defined, the resulting string would have been 'PREFIX Order for...'. With this change, we are eliminating the whitespaces/moving the responsibility for whitespaces to the the prefix-setup. I'd be willing to ship it like this, or - if requested - to add a migration to add a whitespace to existing set up prefixes.
I'd also be open to remove the prefixes (and by extension postfixes) from all user-facing fields and only …
=> PayPal: Add postfix-field and pass information to custom-field

src/pretix/presale/templates/pretixpresale/event/order_modify.html
When editing an order in the frontend, addon-products show the internal name, if provided. This should be the public name.
=> Fix #2150 -- Do not expose internal product names in modify view

src/pretix/base/models/items.py
The label was „Number“, which is rather ambiguous. Mini-change as PR for tests to run.
=> Bundled items: improve label for quantity

src/pretix/control/views/subevents.py
I sometimes get a failed test run for this code path:
https://github.com/pretix/pretix/runs/3278779442?check_suite_focus=true
`self.list_formset` is `None` if `self.sampled_lists` is `None` – see https://github.com/pretix/pretix/blob/master/src/pretix/control/views/subevents.py#L1154
I therefore changed to if statement in `save_list_formset` to first check `self.sampled_lists`. Furthermore I changed to double negation logic in https://github.com/pretix/pretix/blob/master/src/pretix/control/views/subevents.py#L1154 because I always stuble upon double negation.
=> Subevent bulk edit: check if list formset has changed only if not None

src/pretix/base/payment.py
When limiting payment methods by country and no invoice adress is given, the check should be ignored/passed instead of returning True as checks later in the code path such as `order.sales_channel` as well as `self._is_still_available` might limit the current payment method.
=> Payment availability-check: ignore country if no invoice address given

src/pretix/base/models/orders.py
Fixes the property `ticket_download_date` which could return `None` what is not handled correctly later on and results in type errors:
```
Aug 11 05:00:51 kulturkosmos-prod gunicorn[4458]: ERROR 2021-08-11 05:00:51,536 django.request log Internal Server Error: /Kuko/<redacted>/order/<redacted>/<redacted>/
Aug 11 05:00:51 kulturkosmos-prod gunicorn[4458]: Traceback (most recent call last):
Aug 11 05:00:51 kulturkosmos-prod gunicorn[4458]: File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
Aug 11 05:00:51 kulturkosmos-prod gunicorn[4458]: response = get_response(request)
Aug 11 05:00:51 kulturkosmos-prod gunicorn[4458]: File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
Aug 11 …
```
=> Fix TypeError in Order.ticket_download_available on "empty" orders

src/pretix/control/forms/__init__.py, src/pretix/plugins/sendmail/forms.py, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/send_form.html, src/pretix/plugins/sendmail/views.py, src/tests/plugins/sendmail/test_sendmail.py
Yesterday, a customer accidentally sent thousands of emails instead of a few.
This PR proposes to force mass emails to go through the "preview" step and showing the number of matching orders on the "send" button. It also makes the button red :rotating_light:
=> Sendmail: Force preview and show number of orders

src/pretix/base/models/event.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/static/pretixpresale/js/ui/cart.js, src/pretix/static/pretixpresale/scss/_cart.scss
This is an attempt to fix two customer complaints:
- End time not being shown in cart (but we'll still only show it for events <24h, otherwise things get confusing)
- Location not being shown in cart / order confirmation
**Before**:
**End**:
I'm still a little unsatisfied with how full this gets when there's attendee names and addresses and questions and stuff, but there's probably little room to fix that.
=> Display subevent location and end time in cart

src/pretix/base/email.py, src/pretix/base/management/commands/makemigrations.py, src/pretix/base/models/waitinglist.py, src/pretix/base/services/waitinglist.py, src/pretix/base/settings.py, src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/control/views/waitinglist.py, src/pretix/presale/forms/waitinglist.py, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/event/waitinglist.html, src/pretix/presale/templates/pretixpresale/event/waitinglist_remove.html, src/pretix/presale/urls.py, src/pretix/presale/views/event.py, src/pretix/presale/views/waiting.py, src/tests/base/test_waitinglist.py, src/tests/presale/test_event.py
This PR bundles three new features for the waiting list.
"Good" seating support for the waiting list is hard or impossible for a variety of reasons. For example, in a seated event people usually just want any seat, not just from a specific category, which is entirely incompatible with the way our waiting list mechanism works. Additionally, the waiting list is based on quotas, while seated events not necessarily are. The hardest problem though is probably the "minimum distance" feature because it makes it unpredictable "how much space" a single voucher will use.
However, there is a series of simple use cases where the minimum distance is not in use and it's feasible to focus on specific use cases, such as usage of pretix in public libraries. In these cases it's also possible to equate …
=> Improvements around the waiting list

src/pretix/static/pretixpresale/js/ui/questions.js
=> WIP: improve customer profiles

src/pretix/base/templates/pretixbase/email/simple_logo.html
Outlook 2010/2013 cut off header images. I guess it is due to some issue with dynamic sizing the image and line-height and maybe even mso-line-height-rule.
This PR got a bit bigger as it improved and simplified the HTML-newsletter-template.
Among the improvements are:
- align text to the left; fully centered text is hard to read
- remove mso cellpadding-tables as they double up the spacing
- additionally add background-color to a table with width=100% for broader support (e.g. Yahoo and AOL)
=> Fix Outlook >= 2010 trimming header image

src/pretix/static/pretixpresale/scss/_theme.scss
Open questions:
- Is 25 a good value? Our paddings are usually 15px or 30px, but 30px looked to much.
- Previously, the container width for content was constant for every desktop screen size. Now it will be inconsistent between ticket shops which *could* make it harder to work on future layout stuff. Possible courses of action:
1. Accept that fact
2. Increase the padding regardless of background color, making shops on white background narrower as well
3. Increase container width
I think (iii) is too hard since that would require messing up bootstrap's breakpoints which could have all sorts of unintended consequences. (ii) is interesting since white background is no longer the default or preferred option anyways, however it's a waste of space in some cases and it might look weird depending …
=> Increase padding if background color is set

src/setup.py
Latest macOS throws an error on setup with django-hijack==2.1.10, allow 2.2.x
=> Setup: Allow django-hijack v2.2

src/pretix/base/middleware.py
When adding/merging domains for CSP-header it could happen that empty lists were added, which resulted in faulty CSP-Headers which resulted in an exception when parsing such a CSP-header.
=> CSP: Strip keys with empty values from header

src/pretix/static/pretixpresale/js/ui/main.js
The recent fix for Chrome broke the current-time-bar for all browsers that support CSS-calc-division in CSS-grid.
=> Day calendar: Fix missing current-time-bar back for all browsers

src/pretix/base/templates/pretixbase/email/base.html, src/pretix/base/templates/pretixbase/email/simple_logo.html
This PR also removes the `p:last-child` margin-bottom: 0; rule – which interestingly did not have any effect as the CSS-inliner somehow mixed up specifity and first inlined margin-bottom:0; from `p:last-child`, but then inlined `margin: 0 0 10px;` from `p`
Closes #2363
=> Fix #2363 – Email: change text-alignment from center to left (right for rtl)

src/pretix/base/email.py, src/pretix/base/models/event.py, src/pretix/base/models/organizer.py, src/pretix/control/views/event.py, src/pretix/control/views/organizer.py, src/pretix/settings.py, src/pretix/testutils/settings.py, src/tests/base/test_mail.py, src/tests/control/test_events.py, src/tests/control/test_organizer.py
Whenever we specify a backend in the django settings, there is no
control over the backend used with custom SMTP settings. This change
reuses the e-mail backend configured.
Our SMTP EmailBackend is a custom class, subclassed of the `'django.core.mail.backends.smtp.EmailBackend'`, however with a local fix implemented for a long standing django bug. With the custom backend we are able to use correct use SMTP-relaying with EHLO authentication.
Context:
- https://github.com/django/django/pull/13728
- https://code.djangoproject.com/ticket/6989#no1.
=> Email: Allow to override backend for custom SMTP connections

src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar.html, src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar_week.html, src/pretix/presale/templates/pretixpresale/fragment_calendar_nav.html, src/pretix/presale/templates/pretixpresale/organizers/calendar.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_day.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_week.html, src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/presale/views/event.py, src/pretix/presale/views/organizer.py, src/pretix/static/pretixcontrol/scss/_forms.scss, src/pretix/static/pretixpresale/scss/_forms.scss, src/pretix/static/pretixpresale/scss/main.scss, src/tests/presale/test_event.py, src/tests/presale/test_organizer_page.py
This PR adds several  improvements to the calendar navigation on organizers pages:
- unify GET-parameters to `date` instead of a mix of `week`, `month`, `year` and `date`
- remove calendar-type icons as they do not add distinction. This brings the +iCal button back on the same line most of the time
- move „show upcoming/past events“ links to their corresponding notification texts instead of in the navigation
- on month view, change month/year-selects to a single select
- on week view, change week/year-selects to a single select
=> Organizer: improve calender navigation on organizer page (Z#177488)

src/pretix/presale/checkoutflow.py, src/pretix/presale/templates/pretixpresale/fragment_login_status.html, src/pretix/presale/utils.py, src/pretix/presale/views/cart.py, src/pretix/presale/views/customer.py, src/tests/presale/test_checkout.py, src/tests/presale/test_customer.py
Customer account login is an organizer-level thing. Specifically, we offer the login and profile management views as part of the organizer URLs, e.g. ``https://pretix.eu/org/account/login``. However, one can also log in or sign up during checkout. This is all fun while both organizer URLs as well as event URLs are on the same domain, e.g. ``https://pretix.eu/org/`` and ``https://pretix.eu/org/event/`` or ``https://tickets.org.com/`` and ``https://tickets.org.com/event/``.
However, once you use event-specific domains, this becomes incredibly confusing. If you visit ``https://tickets.eventdomain.com`` and click on the "login" button, you will be taken to ``https://tickets.org.com/account/login`` and after you logged in, you will see your profile on …
=> Reduce confusion about customer login with event level domains

src/pretix/base/reldate.py, src/pretix/control/forms/event.py, src/tests/control/test_events.py
As discussed, when not having changed anything in the event settings form, pretix still creates a LogEntry that a change has been made, even though there is code to prevent that.
I found a way to correct that for a use of `RelativeDateTime`, but `has_changed()` is still True for the field `checkout_email_helptext`. That's an I18nText, so maybe @raphaelm can have a look at that?! :innocent:
=> Fix event settings form considered changed even if unchanged

src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar.html, src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar_week.html, src/pretix/presale/templates/pretixpresale/organizers/calendar.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_day.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_week.html, src/pretix/static/pretixpresale/js/ui/main.js
This was suggested from a customer when navigating the calendar-views. It adds a bit of JavaScript that listens to navigation-events in the top-calendar-navigation (prev/next and date-dropdown) and records the scrollposition. When the next page is loaded it will scroll/jump to the same position. If loading is fast enough (most of the time) it makes for a seamless navigation in the calendar.
=> Add fixed scroll position when navigating calendar views (Z#177488)

doc/admin/config.rst, src/pretix/base/models/orders.py, src/pretix/base/services/mail.py, src/pretix/base/services/orders.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/mail.html, src/pretix/helpers/hierarkey.py, src/pretix/settings.py
This feature has been requested by users hundreds of times. So far, I always refused. I think it is generally a bad idea, as it will hurt email deliverability of the most important email we send and it will lead to users misusing the feature.
However, after many years, I'm now breaking under the recent pressure applied by multiple customers and implementing it. The two intended use cases are:
* Many customers want to send their terms of service and similar documents, since there might be a legal requirement to do so. Hard to argue with that
* One customer wants to send a 1-page FAQ sheet on the booked event to avoid lots of support overhead
To keep the misuse of this feature small, I applied two restrictions:
* I only added one setting. If we wanted symmetry with the email texts we would …
=> Allow to attach files to order confirmation email

src/pretix/helpers/formats/fr/__init__.py, src/pretix/helpers/formats/fr/formats.py, src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar_week.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_week.html, src/pretix/presale/views/organizer.py
Calendar week-views use `WEEK_FORMAT` to format the date as a week of the year. If the chosen language did not have a `WEEK_FORMAT` set, `WEEK_FORMAT` was used literally as the format-string, which created very long, strange date-formatting.
Also added a french `WEEK_FORMAT`.
=> Fix: WEEK_FORMAT fallback in calender week-views

src/pretix/base/models/orders.py, src/pretix/base/models/tax.py, src/pretix/base/services/orders.py, src/pretix/control/forms/event.py, src/pretix/control/views/organizer.py, src/pretix/presale/checkoutflow.py, src/tests/presale/test_checkout.py
This change adds a new action that can be triggered by tax rules for specific customer groups (defined by country and type of customer). You can now set e.g. that all customers from non-EU countries will be placed in the order review process:
This is useful e.g. if you have a specific situation where you want to handle taxation of unknown countries manually.
=> Allow tax rules to trigger approval requirement

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/_event.scss
When having products with a max. quantity of one per order, we render a checkbox instead of a number-input to mark an item to be added to the cart. This checkbox on its own can easily be overlooked, especially combined with a free-price input next to it.
This PR adds an auto-check to the checkbox, when the free-price input is changed as well adds an icon next to the checkbox.
=> Improve add-to-cart checkbox for items with max. 1 per order (Z#178704)

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html
If an item contains a single add-on that is also required to be selected, this change autoselects the corresponding checkbox, so users don't have to click it themselves.
TODO:
=> Fix #555 -- Preselect a single required add-on

src/pretix/base/forms/widgets.py
Having the attrs manipulation in the `__init__` leaves this open to additional manipulation after the Widget was created. This would happen when the question was dependent on another question's answers.
Moving the manipulation to `get_context` as done in other places in Pretix solves this issue.
Fixes #2320
=> Fix #2320 - Move file upload "required" attrs manipulation from init to rendering

src/pretix/base/services/mail.py
I'm guessing this is a typo as `logger` is not used in the condition body.
=> Fix guard in mail service

src/pretix/base/services/mail.py
In the [recent email settings](https://github.com/pretix/pretix/commit/e3c7cd7c6d239a1cf775ec30825f61b670cbb829#diff-1a5a0dc016008f7685381afc98b270c69bb4066d5f510fdc0f46fa88647256dfL220) change the reply-to header was broken.
=> Fix default reply-to header in emails

src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixcontrol/js/ui/variations.js
If Intl.NumberFormat is available, try to format price with locale and currency – all in try-block, in case formatting fails due to unknown currency or locale.
=> Fix #2449 -- Format variation-price with Intl.NumberFormat

src/pretix/base/forms/__init__.py
When entering `*****` in a SecretKeySettingsField pretix will throw an error when no initial value is set for that SecretKeySettingsField.
=> Fix #2434 -- Disallow manually setting SecretKeySettingsField to *****

src/pretix/base/models/customers.py
Due to a circular reference, I cannot import `from pretix.base.email import get_name_parts_localized` in the header area but had to import in the method `get_email_context`. Any other idea?
=> Localize customer name_parts in email-context (Z#179923)

src/pretix/presale/templates/pretixpresale/event/order_change.html
**Describe the bug**
When changing an order, the date field is not displayed correctly.
**Expected behavior**
Date field is shown
_pos_ has to be replaced by _position_
=> Fix subevent not shown correctly in order change view

src/pretix/static/pretixpresale/scss/main.scss
At least on Safari the details/summary in privacy-modal show the marker/chevron twice. This PR updates the CSS to always hide it.
=> Fix details/summary marker on privacy-modal being shown twice

src/pretix/base/models/items.py, src/pretix/control/forms/item.py
This fixes a bug where min_per_order/max_per_order on an item can be set < 0. The fix is in the widget, alternatively we might migrate from `models.IntegerField` to `models.PositiveIntegerField`.
=> Fix #2452 -- Disallow invalid values in min_per_order/max_per_order

src/pretix/base/email.py, src/pretix/base/models/orders.py, src/pretix/base/templates/pretixbase/email/order_details.html, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/views/__init__.py, src/pretix/static/pretixpresale/scss/_cart.scss
This is an attempt to give a nicer view in the cart if someone buys the exact same addon 5x for the same top-level product, while at the same time keeping all other important properties of the grouping and sorting intact. @wiffbi can you check if you think this breaks anything?
=> Group identical add-ons in cart

src/pretix/presale/templates/pretixpresale/base.html
This PR fixes some favicon URLs not using the custom favicon.
Furthermore it removes the unnecessary 194x194-size, which makes only sense, if a custom favicon for e.g. Android Chrome with e.g. a drop-shadow were designed, that we do not expect to be shown anywhere else. As this is not the case with neither default pretix-icons nor the generated custom icons, we can safely remove this icon size.
The same with mask-icon, as Safari >12 can use a normal favicon instead – even apple.com does not use the mask-icon anymore.
If we at some point drop support for older IEs, we could also drop the `<link rel="shortcut icon"` line. IMHO it currently does not hurt much to keep it in for now.
=> Fix -- Custom favicon not showing correctly in Safari (#Z181607)

src/pretix/plugins/banktransfer/views.py
Volksbank's in Germany are exporting MT940-Documents with the file extension ".mta" instead of ".sta". While the format is valid, pretix would mark those files as invalid, as long the user does not rename it to one of the allowed.
This PR adds the .mta file to the list of recognized file extensions in the banktransfer plugin.
=> Add the .mta file extension for Volksbank's MT940

src/pretix/base/services/orders.py, src/pretix/control/forms/orders.py, src/pretix/control/templates/pretixcontrol/order/change.html, src/pretix/control/views/orders.py, src/tests/base/test_orders.py
Currently, when splitting orders, you can split a position without its addons, which leads to real weird effects with cross-order-relationships between positions :o This fixes it :)
=> Fix order split with add-ons involved

src/pretix/base/services/cancelevent.py, src/pretix/base/services/orders.py, src/pretix/control/forms/orders.py, src/tests/base/test_cancelevent.py
Implementation as discussed in #2522
Note that the diff is a little larger, however the refund creation using `proposals` just has been indented. This is because I've simplified the control flow a little bit. The giftcard senario guarded by `refund_as_giftcard` was not using the `proposals` at all, so I've move the loop into the else clause. This means `can_auto_refund` is no longer needed.
=> Event cancellation: Allow allow creating manual refunds for all orders

src/pretix/control/views/user.py
As we currently do not use attestation in 2FA-device registration, we can safely remove it. This circumvents a bug in webkit when registering Touch-ID as 2FA-device on M1 Macs. See https://bugs.webkit.org/show_bug.cgi?id=224042
For more info on why we do not use attestation, see https://fidoalliance.org/fido-technotes-the-truth-about-attestation/
=> Fix #2556 -- Remove attestation from 2FA-device registration

src/pretix/base/pdf.py, src/pretix/control/templates/pretixcontrol/pdf/index.html, src/pretix/control/templates/pretixcontrol/pdf/placeholders.html, src/pretix/control/views/pdf.py, src/pretix/static/pretixcontrol/js/ui/editor.js
We recently introduced placeholders for PDF texts, i.e. you can now use {attendee_name_full_name} as part of a custom text on your ticket.
This PR actually makes that usable:
- It adds a dynamic documentation page listing all placeholders available for an event
- It moves question placeholders from including the question's primary key to including the question's identifier. This has long been a pain point that we need to carefully rewrite the layout JSON when we copy the layout to a new event, since question primary keys are not stable between events. This patch basically adds the new fields and "hides" the old ones, while still retaining full functionality of the old ones. The downside is that for the forseeable future, the API will now expose *both* options to the devices, which seems …
=> Improvements to PDF text placeholders

src/pretix/control/forms/orders.py
The initial value for the mail subject were not using `LazyI18nString`s, causing only one field to be filled with the logged in user's current language, which may not correspond (example puts English string in Dutch field):
I'm not familiar with `django-i18nfield`, but I based this patch on the e-mail content fields code directly below, which seem to work.
=> Event cancellation: Fix default email subject translations

src/pretix/control/templates/pretixcontrol/checkin/list_edit.html, src/pretix/control/views/checkin.py, src/pretix/helpers/jsonlogic_boolalg.py, src/pretix/static/pretixcontrol/js/ui/checkinrules.js, src/pretix/static/pretixcontrol/js/ui/checkinrules/jsonlogic-boolalg.js, src/pretix/static/pretixcontrol/js/ui/checkinrules/viz-node.vue
When working with a large number of products and product-dependent logic in the check-in rules, it is easy to forget about one of your many products. For example if you have products A, B, C, D, E, and F, and the rule
```
(product in (A, B) AND date after event start) OR (product in (C, D, E) AND time after 7am)
```
tickets with product F will be rejected, even though they are on the correct check-in list.
This patch introduces a "little" bit of JavaScript performing static analysis of the rule within the editor. The boolean logic of the rule will be first converted to disjunctive normal form (i.e. ``(… AND …) OR (… AND …)`` with no further levels of nesting allowed, and then we walk through all operands of the top-level OR and check if all branches contain a product/variation filter …
=> Analyze check-in rules for missing products

src/pretix/static/pretixpresale/scss/_calendar.scss
In calendar week-view due to margin-collapsing for smooth foldup of week-days, ul.events had a overflow:hidden, which caused the focus-outline to mostly disappear. This changes the margins from top to bottom, so that no overflow:hidden is needed for smooth fold-up of week-days.
=> Calendar view: make focus-outline visible

src/pretix/presale/templates/pretixpresale/fragment_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_week_calendar.html, src/pretix/static/pretixpresale/scss/_calendar.scss
In calendar view it was hard to distinguish the availability state of events on a first glance especially with some type of color blindness. This tries to fix this by:
- make unavailable events background/border even lighter
- remove ticket-icon (or any icon at all) from unavailable events to make the distinction for „book now“ links with a ticket-icon
- remove bold font on unavailable events
- strike-through first line on unavailable events
Before:
After:
After (no color):
After (no red):
After (no green):
=> Calendar view: improve differentiation between events’ states (Z#173939)

src/pretix/base/models/checkin.py, src/pretix/base/services/checkin.py, src/pretix/helpers/jsonlogic_query.py, src/pretix/static/pretixcontrol/js/ui/checkinrules.js, src/tests/base/test_checkin.py
=> Check-in rules: Add now_isoweekday and minutes_since_last_entry

src/pretix/base/exporters/orderlist.py
This includes canceled lines in the "order positions" and "order fees" tabs of the "order list" export.
Before, the lines were just not included.
With this patch, the lines only marked by the "canceled" value in the status column that is set even when the order as a whole has a different status. This is logical and consistent, but I'm still not sure if it might be a bad surprise for some users of the list? Can't imagine a situation where it would be, though.
=> Order list export: Include canceled positions

src/pretix/plugins/badges/exporters.py
PyPDF 1.27.6 has introduced different handling of trimBox when merging pages – with 1.26 trimBox was ignored when the background-PDF was placed, but since 1.27.6 PDFs with a trimBox got a mask the size of the trimBox (ie. clipped) when merged. As of the release notes, this is intended behaviour for PyPDF, so we need to change the behaviour in our code. This PR sets the trimBox of any background-PDF in badges to the mediaBox.
=> Badges: Remove trimBox from background PDF (Z#2398854)

src/pretix/base/pdf.py
When using `salution` on its own or in any of the other automatic combinations with `name_parts`, it is not localized in PDF output. This PR fixes this.
Thanks to a suggestion by @raphaelm this PR also filters out `salutation` from any combined placeholder, if `salutation` is `"Mx"`.
=> Localize salutation when creating PDFs

src/pretix/base/pdf.py
There is an useful email placeholder `name_for_salutation` which this PR brings to the editor/PDF as well.
=> Add placeholder name_for_salutation to editor/PDF to improve handling of salutation „Mx“

src/pretix/static/pretixcontrol/js/ui/editor.js
I noticed that copy-paste etc. only works with CTRL-key, which is unexpected on macOS. This PR adds support for metaKey (CMD on Mac) to the editor.
=> PDF Editor: support Mac-like (CMD/metaKey) keyboard shortcuts

src/pretix/static/pretixcontrol/js/ui/editor.js
When e.g. using answers/questions in editor for tickets/badges/etc. and lateron deleting a question, currently the textfield is not visible in/reachable through the GUI as its content is `""`. Although this artefact in the layout itself does no harm and can be fixed in the editor’s code-view, this PR changes the GUI-behaviour for unknown placeholders to render content as `"???"`.
=> PDF Editor: set textfield to ??? to hint at placeholder being unknown

src/pretix/base/models/customers.py, src/pretix/base/models/items.py
This PR validates question identifiers to only contain alphanum, dot, dash & underscore. It forces identifiers to start and end with an alphanumeric character (currently no real need for this, just to be consistent with event-slug’s constraint).
=> Limit identifiers (Question, QuestionOption, Customer) to alphanum, dot, dash & underscore

src/pretix/presale/views/order.py
=> Fix #2651 - Crash when editing add-on products after order

src/pretix/base/pdf.py
In ReportLab the automatic word wrap only works on space characters. When rendering long strings (e.g. names) this creates ugly line-breaks. This PR adds an almost invisible space after hyphen characters to enable word wrapping in words with hyphens. Sadly the „zero width space“ is not supported/not recognized as a word boundary, but the „hair space“ works.
Before:
After:
=> PDF render: enable word-wrap on hyphens (Z#23101879)

src/pretix/plugins/banktransfer/payment.py
Add some help_text regarding special characters in the account holder’s name. Punctuation though is not 100% correct as it seems e.g. ! can cause problems. Maybe use „some punctuation“ instead?
=> Banktransfer: add help-text to name of account holder

src/pretix/base/email.py
E-Mail placeholder event_admission_time was missing a `astimezone`. I glanced over the other placeholders in email.py as well and have not spotted any other issues.
=> Fix timezone in email placeholder event_admission_time (Z#23102667)

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html
~~This PR adds a label „FREE“ in price columns to products that are free – previously addons have not had anything shown if they were free. I see how this works well with all addons being free, but IMHO is a bit confusing if free addons are combined with addons that have a price other than 0.~~
Furthermore this PR adds cart-icons to addons-checkboxes like they are used in the normal product selection. Sorry, if this mixes two only remotely related things into one PR.
UPDATE: this PR adds the label „free“ to addon-products, if their price is 0.00 and if the main product’s setting „price_included“ is set to false. If the main product’s setting „price_included“ is true, everything will stay as is and the label „free“ is only available to screen reader users.
=> Checkout: label add-ons as free if price is 0 and add-ons are not included in the main product (Z#23101974)

doc/api/resources/customers.rst
Upon my first reading, I thought the name of a customer couldn’t be changed, but that’s not correct. PATCH requests that update the name_parts field work fine, and that influences the name field.
I think what the docs are trying to convey is that the name field is never settable because it’s derived from the name_parts field, so update the prose to make that more clear.
=> Docs: Clarify customer name field editing

doc/api/resources/customers.rst, src/pretix/api/serializers/organizer.py, src/pretix/api/views/organizer.py, src/pretix/base/models/customers.py, src/pretix/presale/forms/customer.py, src/tests/api/test_customers.py
Before this commit, customers whose accounts were created via the API would not
get any email, and would not be able to log in until they followed the reset
password flow — not a great experience overall.
With this commit, customers created via the API get the same activation email
that they would get when using the account creation form.
=> API: Allow to send activation email when creating customers

doc/api/resources/orders.rst, src/pretix/api/serializers/order.py, src/tests/api/test_order_create.py, src/tests/api/test_orders.py, src/tests/base/test_shredders.py
Add the `custom_field` in the `order.invoice_address` resource for REST API.
=> Add custom_field in orders API

src/pretix/presale/forms/checkout.py
Before this commit:
With this commit:
=> checkout: fix initial membership selection with only one choice

src/pretix/static/pretixpresale/js/ui/main.js
When entering an unknown/invalid voucher code, the error message was shown twice. The error for the voucher-input was using aria-describedby on the main alert-box at the top, which Javascript uses to display the aria-describedby error-messages for each input, that has errors. That caused the error message for vouchers to appear twice.
This PR checks, if the description is actually the alert box and does not another message to it. Drawback to this is, that in this error message there is no link to go to the input anymore.
Generally error messages around voucher input are not ideal, as the error currently only gets shown at the top of the page but JavaScript focuses the first input with error – which for vouchers is usually so far down the page, that the error message is scrolled out of …
=> Presale: fix doubled error messages (Z#23104019)

src/pretix/settings.py
This matches the default listening port of `python manage.py runserver`, which the pretix development guide recommends using: https://docs.pretix.eu/en/latest/development/setup.html#run-the-development-server
=> Set default for SITE_URL to localhost:8000

deployment/docker/supervisord/base.conf
`/usr/local/bin/pretix` (`deployment/docker/pretix.bash` in git) runs `supervisor`,
at least the `all` and `web` subcommands.
But, the `pretixtask` and `pretixweb` supervisor programs each also run
`/usr/local/bin/pretix taskworker` and `webworker`, respectively.
This means that `/usr/local/bin/pretix` does 3 `pretix migrate` calls,
two of which run in parallel and will likely never migrate anything
(as another migration ran *just before*).
I instrumented my `/usr/local/bin/pretix` with a `set -x` call.
Before this commit, pretix logs 3 migrations and starts in 19 seconds:
```
Jul 29 20:00:57 exo1 systemd[1]: Started pretix.
Jul 29 20:00:58 exo1 docker[46319]: + python3 -m pretix migrate --noinput
Jul 29 20:01:03 exo1 docker[46319]:   No migrations to apply.
Jul 29 20:01:05 exo1 …
```
=> Docker: Set AUTOMIGRATE=skip for subprocesses

src/pretix/base/pdf.py, src/pretix/base/settings.py, src/pretix/control/views/pdf.py, src/pretix/plugins/badges/exporters.py, src/pretix/plugins/ticketoutputpdf/exporters.py, src/pretix/plugins/ticketoutputpdf/ticketoutput.py, src/setup.py, src/tests/plugins/badges/test_pdf.py, src/tests/plugins/ticketoutputpdf/test_ticketoutputpdf.py
This updates PyPDF2 to 2x, which renamed everything. The old names still work until we upgrade to 3.0 some day, so if we missed soemthing it's not too bad, but we should check that everything still works.
This needs to be merged BEFORE the new ZUGFeRD plugin version
There's also work needed AFTER this merge in some plugins
=> Bump PyPDF to version 2

src/pretix/static/pretixcontrol/js/ui/editor.js
When changing the selected object to either type `other` or `other-i18n`, the text-value of a previously selected object of the same type was still present in the input textarea. This PR resets the content of text inputs `other` and `other-i18n`.
Also when switching between type other and other-i18n, this PR adds the feature, that the content from other is copied to other-i18n. When switching from other_i18n to other, the value of the first i18n-textarea is copied to the other-textarea.
=> PDF-Editor: fix other/other-i18n input prefill bug (Z#23104692)

src/pretix/base/templates/pretixbase/email/base.html, src/pretix/base/templates/pretixbase/email/separator.html
This PR fixes #2760 by adding empty alt  attributes to the purely decorative images in the default html email-template.
=> Fix: add alt attribute to images in default html email-template

doc/api/resources/customers.rst, src/pretix/api/serializers/organizer.py, src/pretix/api/views/organizer.py, src/tests/api/test_customers.py
I wanted to unify the email/password combination across an internal members-only area and a pretix shop.
With this change, I can set a password in the API when creating the pretix customer account.
Do you want to add docs/tests and push this PR over the finish line?
Thanks
=> API: allow setting password when creating customer

src/pretix/static/pretixcontrol/js/ui/main.js
When using select2 in pretix-control a JavaScript error is thrown when trying to access `hasAttribute` on a jQuery-object instead of the actual DOM-node.
=> Fix JavaScript for custom select2 focus handler

src/pretix/base/models/discount.py
When a discount needs discounted products to be from different dates from an event series, the product-filter for this discount (`initial_candidates`) was not applied. This PR fixes this.
AFAICT tests in tests/base/test_pricing_discount.py currently do not test for the product filter at all. Is this somewhere else or something we should add?
=> Fix discount for distinct dates when only certain products are allowed (Z#23107419)

src/pretix/base/models/event.py
attempt to fix #2771 by retaining the original mail_attachment_new_order filename.
=> Retain filenames when cloning an event

src/pretix/base/models/event.py, src/pretix/base/pdf.py
For customer convenience, this adds a new placeholder `event_begin_weekday` and `event_end_weekday` to the PDF editor to allow printing the weekday of the event date to tickets.
=> PDF: Add event weekday variable

src/pretix/static/npm_dir/package-lock.json
Upgrade javascript package lockfile from v1 to v2
_The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree._ (cit. https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile)
=> Upgrade package-lock to v2

src/pretix/plugins/badges/exporters.py
When outputting multiple tickets/badges per page, the transformation in PyPDF is only applied to page-contents not the mediabox/trimbox, which resulted in missing background images. This PR fixes it by offsetting the mediabox/trimbox of background-PDFs before adding them to the page.
=> PDF: Fix missing backgrounds when outputting multiple tickets/badges per page (Z#23107984)

src/pretix/static/pretixcontrol/js/ui/editor.js
When editing tickets/badges and clicking the preview-button, Chrome opens an empty new tab. This seems to be because of an JavaScript triggered form-submit on a form with target=_blank. As soon as the JS-submit is removed, PDF-preview works – as the button, that triggers the preview, is already a submit-button for that form.
=> PDF editor: Fix empty preview tab in Chrome

src/pretix/presale/templates/pretixpresale/event/fragment_downloads.html, src/pretix/presale/views/order.py
As discussed this fixes the hint regarding download-date for tickets when plugins disallow the download.
=> Fix ticket download-date hint when plugins disallow download (Z#23104496)

src/pretix/presale/templates/pretixpresale/event/voucher.html
In an event series when trying to redeem a voucher on a date where the associated productis not available, this would result in an empty product list and an inactive add-to-cart button. This PR adds a message to describe that no products are available at the moment.
Feel free to improve the wording!
=> Improve voucher redeem if no products are available (Z#23107372)

src/pretix/control/templates/pretixcontrol/checkin/index.html, src/pretix/control/templates/pretixcontrol/organizers/devices.html, src/pretix/control/templates/pretixcontrol/subevents/index.html
select2 fails to initialize dropdown for subevents as the filter-form is repeated as-is inside the bulk-action form, which causes two inputs having the same id – which select2 seems to fail and only initialize the last (in this case hidden) one. This PR fixes it by outputting the second, visually hidden form as hidden form-fields.
=> Fix hidden bulk-action filter-form (Z#23108559)

src/pretix/presale/templates/pretixpresale/event/fragment_cart_box.html
As user reports suggest the checkbox icon is not ideal for the submit button when adding a voucher from within the cart. The clearest way would be to use a readable text-label as well, but this could be problematic too as in viewport-width around 480px depending on the length of the translation of „redeem“, the actual voucher input can get quite small so the voucher code in the input will be cut off. Even with just the icon on the button, at 480px viewport-width the voucher code can be cut-off (at least in my tests the last letter was cut off).
Just the word „redeem“:
Or just a pointer (this is what this PR currently implements):
=> Cart: change icon from checkbox to arrow-right for voucher submit

src/setup.py
This fixes the issues encountered in #2681 in which currently an install of pretix fails on arm64 systems as wheels for arm64 weren't added until this [commit](https://github.com/Stranger6667/css-inline/commit/559e43aaf3787d8bc0d460ed30cc5dbb2935b2bd). 
Currently, it falls back to wanting to compile `css-inline` with rust, however certain compiler options aren't passed in order to get a functioning `css-inline`. Thankfully with `0.8.0` and on, a properly compiled package is available for arm64.
=> bump css-inline from 0.7.x to 0.8.x to allow for successful arm64 installs.

src/pretix/base/pdf.py, src/pretix/plugins/badges/exporters.py
Depending on the background-PDF, handling background-PDFs when creating badges could be slow due to PyPDF handling the merging and creating larger filesizes as necessary. This PR splits creating the badge PDF and imposing multiple badges on one page for printing into two separate steps. That way one can use the `render_background` method of the renderer, which by default supports merging backgrounds with pdftk, which is faster and sometimes creates way smaller files (in my tests 3.5MB instead of 13MB).
=> PDF/Badges: Improve performance/reduce filesize when creating multiple badges

doc/api/resources/carts.rst, src/pretix/__init__.py, src/pretix/api/serializers/cart.py, src/pretix/api/serializers/order.py, src/pretix/api/views/cart.py, src/pretix/base/services/cart.py, src/tests/api/test_cart.py, src/tests/api/test_order_create.py
This PR bundles two changes, in two separate commits:
1. A complete re-implementation of the API endpoint to create carts. Previously, we had an implementation that created a single cart position, and for the bulk endpoint we'd call this implementation in a loop. This was highly inefficient and presented a major blocker for #2408 which basically requires having only one quota check per transaction. The new implementation is a clean implementation of bulk-creation and the single creation now just calls the bulk creation with just one item.
2. Support for atomically creating add-on and bundled positions when creating cart positions.
=> API: New implementation for cart creation

src/pretix/base/models/orders.py, src/pretix/base/views/mixins.py, src/pretix/presale/checkoutflow.py, src/pretix/presale/views/__init__.py, src/pretix/presale/views/questions.py
Cart order in pretix was confusing:
- In situations where we can group positions, we sorted by order of categories, items, …
- In situations where we can't group positions, we sorted by order of addition to the cart
With this PR, we'll always sort by order of categories/items/… to be consistent.
A customer complained that by going back and forth in the checkout process and changing the number of add-on products, you can create very weird groupings in the cart such as this:
This PR makes the cart view completely ignore "chronological" order and strictly sort by the sorting attributes of the products and variations involved, with one exception: Bundled products are always sorted before add-on products.
The same sorting is applied when submitting the order and computing the ``positionid`` …
=> Clarify cart order

src/pretix/plugins/ticketoutputpdf/models.py
Our rendering implementation uses `"content":"secret"` as fallback if not set - but the default layout should set it explicitly.
Serverside: https://github.com/pretix/pretix/blob/5992abcb7dc9ead95a127f90c1a7c720a73ca1e8/src/pretix/base/pdf.py#L703
pretixPRINT: https://github.com/pretix/pretixprint-android/commit/432910737526cb620196e0a11496427e8165569d#diff-5a85c6bb47e2357b72ff645c0b59f99044653b5b17e9601fe696af8d9a97534fR72
=> Set default ticket layout QR code content explicitly to secret

src/pretix/plugins/stripe/views.py
I faced today an issue that I was not able to properly connect my test Stripe account using our staging keys: The connect account name was empty.
According to the Stripe API docs, with 2019-02-19 some fields got shuffled around - so according to this, we're lucky this didn't break yet in our faces: https://stripe.com/docs/api/accounts/object
Interestingly enough, even with the new, updated hashed, my API-calls do net yield a `business_profile` or `email`...
=> Stripe Connect: Fix account name retrieval

src/pretix/static/pretixpresale/js/ui/main.js
If form inputs are not valid (through means of HTML5 validation) but hidden inside a folded panel, they block form submission, but are not shown. This fix opens the folded panel and brings focus to the element. Note: invalid-events are fired on inputs, so there is no easy way to catch just one global invalid-event per form (one could work with a debounced timeout-callback). When there are multiple invalid fields in a form/panel, this fires multiple events which one could think would be a problem as that would trigger multiple click-events on the same `.panel-heading` and open, then close that panel again. In my tests that is acutally not a problem as the browser seems to debounce those input.focus and click-triggers. Alternatively instead of triggering the click-event on the …
=> Fix: make hidden form inputs visible, if invalid

src/pretix/plugins/paypal2/static/pretixplugins/paypal2/pretix-paypal.js
During checkout when navigating back and forth between steps, the payment options can initially be selected. When PayPal was included, it disabled the continue-button even if a payment option was initially selected. This PR fixes this. I tested in console as I do not have a working PayPal setup. It would be great if someone with a PayPal-setup could test this. Thanks!
=> Fix paypal disabling continue button (Z#23110784)

src/pretix/presale/templates/pretixpresale/fragment_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_day_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_week_calendar.html, src/pretix/static/pretixpresale/scss/_calendar.scss
Continued events in calendar views were colored the same way as events that were over. This PR marks continued events with the word „(continued)“ and keeps the color of the original event (e.g. available, etc.).
Two questions:
1. Should the wording be „(continued)“ or the shortened version „(cont.)“?
2. The word „(continued)“ is set in italic so screen readers should pronounce it differently from the title to make it clear, that the word is not part of the event’s title. Optically IMHO it works as well when set in italic, but I am okay to change it to upright. Technical note: the styling uses a custom CSS-class `.event-name-continued`, which currently only sets the font-weight to normal – maybe instead we should create a global `.font-weight-normal` utility-class as bootstrap4 does?
=> Calendar: add label „continued“ to event’s name (Z#2397988)

.github/workflows/docs.yml, .github/workflows/strings.yml, .github/workflows/style.yml, .github/workflows/tests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Actions: Security hardening

src/pretix/base/invoice.py, src/pretix/base/services/invoices.py
Our data model for invoices will likely forever stay at a one-line-per-orderposition model, but there's no reason to render hundreds of lines in the PDF. We've recently changed this in https://github.com/pretix/pretixprint-android/pull/47 for POS receipts already.
The downside is that it makes the data model less "visible" and the XLSX export or ZUGFeRD data will be different from the PDF… That's annoying, but I think printing less pages of PDF is still worth it?
=> Group identical lines on invoice PDF

doc/admin/config.rst
I fixed a small typo error in docs
=> Docs: Fix small typo

src/pretix/base/exporters/orderlist.py, src/tests/api/test_exporters.py
This PR optionally adds the event’s meta data to the order export and the subevent’s meta data to the order-position export. Should order-fees export should include event’s meta as well?
Meta data columns labels are prefixed with „Meta: “.
=> Order list export: Add event meta data (Z#2397902)

src/pretix/static/pretixpresale/js/ui/main.js
Originally when copying answer the first cartitem/set of answers was used. This PR changes behaviour so the answers from the previous cartitem are used instead of the first cartitem. This also changes some `const/let` to `var` for better backwards compatability. Furthermore file-inputs cannot be copied so are skipped.
=> Checkout: copy previous answers instead of first

src/pretix/plugins/paypal2/views.py
=> PPv2: Simulate cart_payments in XHR-calls; only look at multi_use-payments for remaining value calculation

src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html, src/pretix/presale/templates/pretixpresale/event/order.html, src/pretix/static/pretixpresale/scss/_event.scss, src/pretix/static/pretixpresale/scss/main.scss
This PR tries to improve about the discoverability of an order’s edit links. Currently they are only on the right side of the panel’s head, styled as text (no underline, no button). This PR moves those links to the left and underlines them. Furthermore it removes panel-primary purple in favor of panel-default grey panel-headers, so the newly added buttons „pop“ more.
For this PR, all plugins that listen to signals `order_info_top` and `order_info` as well as `checkout_confirm_page_content` have been checked. Only pretix-shipping needed adjustments.
=> Presale: Improve visibiltity of edit links on order confirm/details page (Z#23108817)

src/pretix/static/pretixcontrol/js/ui/editor.js
There seems to be a way to create a PDF-Layout with an element having no content-attribute. This PR currently changes the editor to not fail, but ignore such elements. This creates an element, that once selected in the editor has no option in the „Content“-dropdown selected. And once one selects e.g. „Other“ the text (Sample text?) gets replaced with an empty string. Do we want this or should we instead do `if (!d.content) d.content = "other";`.
=> Editor: fix sample text when key missing

src/pretix/control/templates/pretixcontrol/organizers/customer.html, src/pretix/control/views/organizer.py, src/pretix/static/pretixcontrol/scss/main.scss
Add an entry for lifetime spending in a customer account's details section, so organizers can easily see how much a customer has spent on all of their events. It gets split for currency, as money exchange courses are not set in stone.
=> Add lifetime spending to customer details

src/pretix/base/services/cart.py
In cart there is an error message „One of the products you selected can only be bought as an add-on to another project.“ I think this should be „One of the products you selected can only be bought as an add-on to another product“.
=> Cart: fix typo in error message for addon-only

src/pretix/plugins/paypal2/static/pretixplugins/paypal2/pretix-paypal.js
PPv2 disables the continue button and reenables it after loading the sdk if paypal is the only option (and thus is preselected) or when one of the payment options is selected. This is inconsistent with other payment methods: Usually the continue button is enabled even if no payment option is selected. This also breaks the checkout process in one case:
If 1) paypal is enabled as a payment method, 2) paypal is not available (because it is hidden, limited to certain countries, ...) and 3) there is exactly one payment method available, PPv2 disables the continue button with no way for the user to enable it:
The user cannot generate a `change` event, since the sole radio button is preselected and cannot be unselected.
This change fixes the inconsistent behaviour and the broken checkout …
=> PPv2: Fix continue button behaviour

doc/development/api/exporter.rst, src/pretix/base/exporter.py, src/pretix/base/exporters/answers.py, src/pretix/base/exporters/customers.py, src/pretix/base/exporters/dekodi.py, src/pretix/base/exporters/events.py, src/pretix/base/exporters/invoices.py, src/pretix/base/exporters/items.py, src/pretix/base/exporters/json.py, src/pretix/base/exporters/mail.py, src/pretix/base/exporters/orderlist.py, src/pretix/base/exporters/waitinglist.py, src/pretix/control/templates/pretixcontrol/orders/export.html, src/pretix/control/templates/pretixcontrol/orders/export_form.html, src/pretix/control/templates/pretixcontrol/organizers/export.html, src/pretix/control/templates/pretixcontrol/organizers/export_form.html, src/pretix/control/views/orders.py, src/pretix/control/views/organizer.py, src/pretix/plugins/badges/exporters.py, src/pretix/plugins/checkinlists/exporters.py, src/pretix/plugins/reports/exporters.py, src/pretix/plugins/ticketoutputpdf/exporters.py
With more and more exporters being added to pretix, the export page has become very crowded and I noticed that new users have a hard time discovering which are the actual useful ones for their use case.
So I propose the following changes:
- Exporters have a description now
- Exporters are sorted into categories
- Our most recommended exporters that are useful for most users are now marked as "featured"
- Selecting an exporter and filling out its parameters are now two separate steps. This is especially relevant since I'm planning on adding another feature that will make the forms more … extensive
=> Reorganize UI for exporters

src/pretix/api/views/upload.py, src/pretix/base/forms/questions.py, src/pretix/base/models/items.py, src/pretix/control/forms/__init__.py, src/pretix/helpers/images.py, src/pretix/testutils/api.py, src/tests/api/test_cart.py, src/tests/api/test_checkin.py, src/tests/api/test_checkinrpc.py, src/tests/api/test_events.py, src/tests/api/test_items.py, src/tests/api/test_order_change.py, src/tests/api/test_order_create.py, src/tests/api/test_organizers.py, src/tests/api/test_upload.py, src/tests/const.py
Uploading images that are below our 10MB barrier but have millions of pixels can eat up lots of memory, which leads to problems during thumbnail generation. We should already validate for that at upload time.
=> Validate image size in pixels at upload time

src/pretix/base/addressvalidation.py
Indonesia uses a 4 digit zip-code with an additional province-select in localflavor. Pretix currently does not support province, so a common fallback seems to be a 5 digit zip-code, which fails in localflavor. This PR removes Indonesia from zipcode-validation through localflavor.
Should I add a custom validator that at least does a basic „is 5 digits“ validation?
=> Checkout: remove Indonesia from zipcode-validation

src/pretix/presale/ical.py
This PR adds a comma to join an event’s location with multiple lines. Multiple empty lines are compressed to one. Fixes #3032
=> Presale: join multiline locations with comma in ical

src/pretix/static/pretixcontrol/js/ui/main.js
When using a colorpicker without the contrast-check, an empty help-text element is created, which takes space and causes layout-shifts with white-space if previously the color was empty.
=> Remove empty help-text for colorpickers with no-contrast

src/pretix/base/services/export.py, src/tests/base/test_export.py
The customer who sponsored the scheduled export feature, requested this change to make sure only the boss is highlighted in the "To" field of the report.
=> Scheduled exports: Set owner to cc instead of to if there is an explicit recipient

src/pretix/control/forms/orders.py
A customer requested this and it's kinda a breaking change, but I'm inclined to agree it's a good change. It's so easy to accidentally keep this box checked if you really don't want to notify your customer.
=> Changing orders: Default to not notifying the user

src/pretix/plugins/paypal2/payment.py, src/pretix/plugins/paypal2/templates/pretixplugins/paypal2/checkout_payment_confirm.html
When paying an **existing** order with PayPal, it is not obvious that you have to click one more time after you signed in with PayPal. This tries to make it more obvious
=> PPv2: Improve visibility of last step in paying orders

src/pretix/presale/templates/pretixpresale/event/base.html, src/pretix/presale/templates/pretixpresale/organizers/base.html, src/pretix/static/pretixpresale/scss/_theme.scss
Currently when navigating with tab or after a click on the logo-link, the focus-outline is just one line-height high due to being `display: inline`. THis PR fixes the outline to contain the logo image but at the same time keeping text-only logo/page-header to stay on the same line by using `display: inline-block` instead of `display: block`, which would cause the text-only logo to break the line before displaying the date.
There is one edge-case where the layout then differs from the current behaviour: when there is not header-image, but the event’s title is used and the title is veeeeery long and has a line break in itself, then the following date will be on a new line.
Old behaviour:
New behaviour:
On „normal“ length event titles it looks the same as before.
Another approach might be to …
=> Shop header: Fix logo link outline to contain image (Z#23115320)

src/pretix/base/services/cart.py, src/pretix/base/services/orders.py, src/pretix/presale/views/cart.py, src/pretix/presale/views/order.py, src/tests/presale/test_cart.py
Currently cart.py uses gettext to localize its error-messages on process-startup. This is not a problem as long as english is the default locale on startup as during code execution the error-messages get run through `gettext` again. If default locale is not english, this then creates static error messages in that locale for every language. This PR fixes #2519 
This PR actually fixes two things:
1. All pre-defined error messages in `services/cart.py` and `services/order.py` were translated during startup time, which is only a problem if you happen to have a default-locale other than `en` in your pretix.cfg. This PR now changes all pre-defined error message to use the lazy-versions of gettext.
2. These lazy-versions then introduce a different problem, when using pretix with celery (the …
=> Clean up localization or error messages in cart

.github/workflows/docs.yml, .github/workflows/strings.yml, .github/workflows/style.yml, .github/workflows/tests.yml, Dockerfile, doc/admin/installation/manual_smallscale.rst, src/setup.cfg, src/setup.py
Waiting on https://github.com/celery/celery/issues/7605 for now
=> Test on Python 3.11, drop Python 3.7-3.8

src/pretix/base/models/event.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/presale/templates/pretixpresale/event/fragment_subevent_list.html, src/pretix/presale/templates/pretixpresale/fragment_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_day_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_week_calendar.html, src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/presale/views/widget.py, src/pretix/static/pretixpresale/scss/_calendar.scss, src/pretix/static/pretixpresale/scss/_theme.scss, src/pretix/static/pretixpresale/scss/widget.scss, src/tests/base/test_models.py
This introduces a new setting as well as a new state in the event list and calendar. If set the new setting to "20", the event calendar will now mark all tickets with less than 20% available spots as "Few tickets left".
This is a little complex to implement as we need to deal with all possible combinations of overlapping quotas, etc.
The `best_availability_state` function is entirely rewritten for this purpose. In the end, performance should be approximately the same as before.
Design-wise, I think there are two main open questions:
- Should this new state be green or yellow? I kept it green for now since we use yellow for "waiting list", "reserved", and "not yet for sale" currently. So yellow currently means "not able to book", and making this new state yellow could be confusing. On the …
=> Fix #1251 -- Event list/calendar: Show "event almost sold out" state

src/pretix/base/pdf.py, src/pretix/control/templates/pretixcontrol/pdf/index.html, src/pretix/static/pretixcontrol/js/ui/editor.js, src/pretix/static/schema/pdf-layout.schema.json
This PR adds support for controlling lineheight in PDF-editor and PDF-output. As reportlab rendering differs a bit from browser canvas rendering, this PR introduces more magic/empiric numbers to get reportlab to render as similar as possible to canvas.
This PR also removes autoLeading as this creates inconsistent leading over several lines and for some fonts even breaks the default 1.0 line-spacing.
=> PDF: Add support for line height

src/pretix/plugins/badges/exporters.py
It would be great to have PyPDF limit the precision when placing an element, but for now, we need to do it ourselves.
=> PDF-Export: limit pagesize precision in badges nup-placement

doc/api/resources/webhooks.rst, src/pretix/api/webhooks.py, src/pretix/control/templates/pretixcontrol/organizers/webhook_logs.html
I decided for one grouped webhook category instead of 12 single ones since we might add more of them at any time and users still likely would want to receive the hooks in that case.
=> Add webhooks for changes to items

src/pretix/static/pretixcontrol/js/ui/variations.js
Currently the first translation of the variation is shown as the variation name in the variation list. This commits changes this to prefer the variation name in the language that the control interface is set to.
=> Use local name in control variation list heading

src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/static/pretixpresale/scss/_cart.scss, src/pretix/static/pretixpresale/scss/_event.scss, src/pretix/static/pretixpresale/scss/_theme.scss, src/pretix/static/pretixpresale/scss/main.scss
This PR tries to improve the visual appearance by increasing the white-space around products and headlines. It furthermore harmonizes line-width between products to 1px as used in other places for lines. Furthermore it fixes a minor padding-top issue with cart where the first item of the cart is too far away from the top/panel-title.
=> Event index: Increase white-space for products and headlines

doc/api/resources/webhooks.rst
Extend the API documentation with info and examples for the new webhooks comment field
=> Docs: Add comment to webhook API

src/pretix/plugins/sendmail/signals.py, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/rule_create.html, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/rule_inspect.html, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/rule_list.html, src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/rule_update.html, src/tests/plugins/sendmail/conftest.py, src/tests/plugins/sendmail/test_rules.py
This is a breaking change, but I think it's worth it. It mainly prevents rules to execute immediately after cloning an event, which is a common pain point.
=> Disable email rules if event is not live

src/pretix/static/pretixpresale/js/widget/widget.js
My latest changes regarding A11y for widget opening variations failed badly when variations were to be displayed open by default. The actual problem was, that I did not take into account that `transitionend` bubbles – and Firefox has a transition on input-focus-outline. So as soon as one focuses an input, a transition starts to fade-in the focus-outline and at the end of that short transition, the whole variations would be removed.
This PR fixes the bubbling issue and also changes the behaviour in that, if the variations are shown by default, none of the watchers are installed as variations that are open-by-default can not be closed. Furthermore the code is less complicated by always removing maxHeight when transition is done and always setting initial maxHeight before a transition is …
=> Widget: fix default-open variations being hidden (Z#23118652)

src/pretix/static/pretixpresale/scss/widget.scss
On some customer sites, svg gets a style `display: block` which is not the default and breaks the close-icons centering. This PR fixes this.
=> Widget: fix centering for close-svg

src/pretix/base/pdf.py
When using unpersonalised addon-products that create tickets with names on it, the fallback should be the order-position’s attendee name. This currently only works for the full name, but not the attendee_name_parts. This PR fixes this.
=> PDF: add attendee_name_parts fallback for addons (Z#23118890)

src/pretix/control/templates/pretixcontrol/event/index.html, src/pretix/control/urls.py, src/pretix/control/views/event.py, src/pretix/static/pretixcontrol/scss/main.scss, src/setup.py, src/tests/control/test_views.py
Non-technical users often struggle with finding the URL of their shop or generating a QR code for posters etc.
This adds a simple helper to make it easier:
Of course, we could make this really complicated with options for the QR code colors and sizes but I think with this small effort we can already do a lot.
=> Add option to copy shop URL and generate QR code

doc/development/setup.rst
It took a little bit of searching to figure out that in the dev environment, by default, celery tasks are run synchronously, but periodic tasks are not run at all.
=> Docs: Note on periodic tasks in dev setup

src/pretix/control/forms/filter.py
_Checkin requires attention_ is a flag that can be set on orders, but couldn't be searched/filtered for in the advanced order search.
=> Add checkin requires attention to advanced order search

src/pretix/presale/templates/pretixpresale/event/checkout_base.html, src/pretix/static/pretixbase/js/details.js, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/main.scss
This PR adds an button „show cart“ and shows parts of the active cart during checkout. This should make it more obvious that the cart can be opened.
=> Cart: Add sneak-peek preview

src/pretix/base/customersso/oidc.py
In OIDC `claims_supported` are only recommended, so it happens, that an Open ID provider does not output them. We only check `claims_supported` during OIDC if they are listed in the provider’s config.
Note: `scopes_supported` is recommended only, but seems better supported. Should we also add an `if` or do we always check for it?
Closes #3294
=> Open ID: validate requested claims only if provider lists claims_supported

src/pretix/static/pretixpresale/js/ui/main.js
Latest pretix-seating (see internal merge request) improves its own disable/enable add-to-cart button by adding a hidden dummy-input element, which is tracked automagically by the existing disable/enable add-to-cart button algorithm. This PR just removes the if-condition to not disable add-to-cart button when seating is active.
=> Cart: disable/enable add-to-cart button even with seating active

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/js/widget/widget.js
There are situations where the max-attribut of an input might not be available. In that case the spin-buttons would always return 0. This PR fixes it by falling back to `Number.MAX_SAFE_INTEGER` if no max-attribute is available. Furthermore it disables the spin-buttons if the input is `disabled`.
=> Fix spin-buttons when no max-attribute present (Z#23122239)

src/pretix/presale/views/order.py, src/tests/presale/test_orders.py
`Order._can_be_paid` returns `True` if an order can be paid and a `str` with an error message otherwise. The result of `_can_be_paid` should thus be check somewhat like `order._can_be_paid() is not True` instead of `not order._can_be_paid()`. In a few cases this check in done incorrectly.
=> Fix Order._can_be_paid checks

src/pretix/base/services/invoices.py
This PR adds order-code to the email sent to organizers whenever an invoice is created. Please note: I did not manage to get this email to be sent on my local dev environment though – I think this is because it is a periodic task.
=> Invoicing: Add order-code to organizer CC mail (Z#23123051)

src/pretix/api/serializers/orderchange.py, src/tests/api/test_order_change.py
Pretix crashes whenever the `addon_to` parameter is set for an item in `create_positions`.
See the regression test I've added. Without this change, the test fails with:
```
self = OrderPositionCreateForExistingOrderSerializer(context={'order': <Order: DUMMY-FOO>, 'request': <rest_framework.request..._from = DateTimeField(allow_null=True, required=False)
valid_until = DateTimeField(allow_null=True, required=False)
data = OrderedDict([('item', <Item: WS1>), ('addon_to', 1)])
def validate(self, data):
data = super().validate(data)
if data.get('addon_to'):
try:
>               data['addon_to'] = data['order'].positions.get(positionid=data['addon_to'])
E               KeyError: 'order'
pretix/api/serializers/orderchange.py:75: KeyError
```
=> API: Fix crash when creating addons with order change endpoint

src/pretix/static/pretixpresale/scss/_forms.scss
When the quantity is disabled, the spinner buttons are disabled as well. Current design for disabled buttons removes border, which in case of the spinner buttons’ design as a union with the input does not look good. This PR adds the usual border (technical a box-shadow) to disabled spinner buttons.
Normal
Normal disabled button with added border (current status of this PR)
With background-color slightly darkened (actual background of input element, but disabled buttons have a slight opacity):
With background-color darkened to same bg as input (ie. no additional no opacity on button) – this is my favourite:
=> Product list: add border to disabled spinner buttons

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/voucher.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/_event.scss, src/pretix/static/pretixpresale/scss/_forms.scss
This PR explores the option to make the checkbox for items with a max-oder of 1 to look like a button. I like the idea, maybe something is missing? Add an icon? Or have it read „select one“?
Note: Firefox currently seems to not support the combination of `:has` and `:checked` – so atm only Safari/Chrome show the darkened background. For testing purposes this is okay. If we go with this design, then we might fallback on JS to handle this or ignore and wait for Firefox to catch up (as it is not that substantial).
Maybe with an icon? I like the one with an icon in front, but then we might remove the checkbox and use the icon to indicate state. E.g. an icon of a cart, then when checked, have a pointer pointing inside the cart? I fear using a checkmark on top of a cart might be misunderstood …
=> Cart: make single-select checkbox look like a button (Z#23121616)

src/pretix/base/settings.py, src/pretix/control/middleware.py
When trying to access something in pretix-control, that the currently logged in user has no access-right to, the error message was not localised correctly.
In settings there were some formatted strings used incorrectly with translation – some where translated before being fed into format_lazy, one was using gettext_lazy, but directly using Python’s `.format`.
=> Fix: use format_lazy for formatted translation in settings

src/pretix/api/views/order.py, src/tests/api/test_order_create.py
This PR adds an order.log_action and thus a webhook-call for confirmed payments created through the order-create-API.
=> API: add log_action/webhook for confirmed payments

src/pretix/control/templates/pretixcontrol/subevents/index.html
Same as done with the products in their overview; for easier ID-selection when constructing custom widgets.
Yay/nay?
=> Expose SubEvent-PK in SubEvent Overview List

src/pretix/plugins/banktransfer/payment.py, src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/email/order_pending.txt
The main reason for using ``<pre>`` here previously was that we did not have a good way to do force new lines otherwise, but I fixed that in 3df64a46e.
=> Bank transfer: Do not use <pre> for bank details in emails

doc/development/api/payment.rst, src/pretix/base/middleware.py, src/pretix/base/payment.py, src/pretix/plugins/stripe/payment.py, src/pretix/presale/templates/pretixpresale/event/checkout_payment.html, src/pretix/presale/templates/pretixpresale/event/fragment_walletdetection_head.html, src/pretix/presale/templates/pretixpresale/event/order_pay_change.html, src/pretix/static/pretixpresale/js/walletdetection.js, src/pretix/static/pretixpresale/scss/_checkout.scss
Until now, we have never actively advertised card tokenization wallet-payment methods such as Apple or Google Pay in the payment provider selection screen.
This is based on the fact, that there are a lot of factors involved in deciding if the wallet payment method is actually offered to the customer: browser, browser settings (incognito/regular), cards added to the wallet, payment-gateway support, merchant enrollment, etc.
So we ended up only displaying "Credit Card" on the selection screen and leaving it up to the payment provider to render one or more wallet payment buttons if they deemed it appropriate.
Understandably, some event organizers do not like this, since their customers do not realize that Apple Pay/Google Pay is just a glorified credit card transaction and wouldn't think of …
=> PProv: Implement detection of wallets such as Google Pay and Apple Pay

src/pretix/base/middleware.py, src/pretix/plugins/stripe/signals.py
As discussed in #3444, this is moving the Stripe-specific CSPs to Stripe's `signals.py` and out of the global middleware.
At the same time, the global middleware is retaining the inclusion of Google Pay - but limiting it to the payment selection pages.
Following https://stripe.com/docs/security/guide#content-security-policy, checkout.stripe.com has been dropped. We also dropped the `img-src`, as it is not mentioned by Stripe in their documentation anymore. 
Reviewers should extensively check that the payments with Stripe did not break.
=> Stripe/Middleware: Move CSP to signal

src/pretix/base/exporter.py, src/pretix/base/pdf.py, src/pretix/plugins/badges/exporters.py, src/pretix/plugins/badges/tasks.py
This PR tries to optimize memory usage when placing multiple badges on one page. Previously the whole single-page PDF was held in memory as well as the NUP-PDF. This PR changes it so the NUP-PDF is split into several tempfiles (currently every 100 pages, not sure what a good value for this is though), then releases the single-page PDF from memory and joins the NUP-tempfiles into one big PDF.
=> Badges: reduce memory usage when placing multiple per page (Z#23125583)

doc/admin/config.rst, src/pretix/settings.py
The corresponding PR adds TLS and mTLS support for PostgreSQL and Redis.
**TODO:**
=> Add PostgreSQL & Redis TLS/mTLS support

src/pretix/control/signals.py, src/pretix/control/templates/pretixcontrol/item/index.html, src/pretix/control/views/item.py
The forms returned by the `item_forms` signal can now set the `title` and (optional) `template` attributes, which behave in the same way as `item_formsets`.
This was proposed in https://github.com/pretix/pretix/discussions/3480.
Currently, there are no automated tests for this feature, which is not ideal. I'm happy to work on some tests if you think it's necessary.
=> Recognise `title` and `template` attributes on `item_forms` signal

src/pretix/static/pretixcontrol/js/ui/typeahead.js
This forces a query of the typeahead menu to immediately occur once the sidebar dropdown is opened by the user, instead of waiting 250ms. 
The delay causes UX problems as users might see that the menu is empty and immediately close it again, not noticing that options would be available after a delay.
=> Sidebar dropdown: remove menu load delay

src/pretix/base/orderimport.py, src/tests/base/test_orderimport.py
As of right now, it is only possible to import `True` values for Yes/Now-Questions, because `if value` on a bool is always skipped if the value happens to be `False`.
This should remedy the situation.
However with this change, there are only two ways to get a non-`False` value into the database:
- Verbatim `True` --> `True`
- `None` --> `None`/Not answered
Everything else will be `False`; without this change, everything else would have been `None`/Not answered.
=> Import: Allow to import "False"-value (Z#23127414)

src/pretix/static/pretixbase/js/details.js
Recently, we have introduced a "almost collapsed" state for the cart:
This however feels odd if the fully expanded cart is only a few pixels larger than the collapsed one. Therefore this PR adds a heuristic to only collapse when the full cart would take more than 200px
=> Cart: Disable sneak peek on very small carts

src/pretix/static/pretixbase/js/details.js
This PR improves #3512 in three ways:
1. It removes the doubling of the `$elements` selector
2. It uses `outerHeight()`, which takes margin into account
3. It makes height-calculation more robust as technically details/summary allow for more than one child other than summary, so it uses array-reduce to sum all outerHeights.
=> Cart: make disabling sneak-peek more robust

src/pretix/presale/templates/pretixpresale/event/fragment_event_info.html, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/event/voucher.html
If you have an event logo that does not include the event name, and have therefore enabled the "show event title anyways" option in the design settings, users who enter the shop through the voucher redemption page will not know what event they are buying for. This PR tries to fix that in the least invasive way possible.
=> Voucher redemption: Display event title in some cases (Z#23127871)

doc/development/setup.rst
I spent a long time debugging why certain things were not working during development. It ended up being because Celery was configured to use Redis in my `pretix.cfg`. This PR adds a warning in the docs about this.
=> Add warning about configuration of Celery in development mode to docs

src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html, src/pretix/static/pretixcontrol/scss/main.scss
When uploading a banktransfer with lots of columns, the row-headers were scrolled out of view. This PR makes them sticky.
Sticky: 
Note: due to position:sticky and the needed background-color, the borders between rows were overlayed and hidden. A somewhat hacky fix is to use a linear-gradient as a background. Maybe there is another less hacky way?
=> Banktransfer: make row-headers sticky (Z#23127000)

src/pretix/base/pdf.py
#3490 introduced deduplication of addons in PDF, but forgot to filter canceled addons. This PR fixes it.
=> PDF: fix deduplicated list of addons (exclude canceled)

pyproject.toml, src/pretix/base/models/items.py, src/pretix/base/services/quotas.py, src/pretix/testutils/mock.py, src/setup.cfg, src/tests/base/test_models.py, src/tests/conftest.py
We allow computing quotas in different ways, e.g. with and without ignoring the waiting list. This is necessary since e.g. some backend actions take priority over the waiting list, but the shop does not.
So far, we have only **cached** the results for `count_waitinglist=True` and we have made sure never to read from the cache if `count_waitinglist=False` was requested. However, we have *written* to the cache when `count_waitinglist=False` was set and therefore wrong data was written to the cache.
A simple solution would be to never write to the cache with `count_waitinglist=False`, but this PR fixes this problem by caching both results, although with separate cache keys.
It also introduces a new dependency that was required to test this properly, as I don't want this error to creep back …
=> Fix quota cache mixup

src/pretix/presale/checkoutflow.py, src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
When e.g. jumping in checkout-steps to edit invoice-info, this PR improves the heuristic, whether the invoice-panel needs to be shown open. Usually when invoice is optional it was closed. This PR adds the option to force-open the invoice panel by respecting the `GET.invoice` parameter (useful when linking to modify-invoice-info from the checkout-review-step), but also inspects initial values in the invoice-form to respect pre-filled values from widget-data or even plugins using the signal `contact_form_fields_overrides`.
=> Checkout: improve heuristic to open invoice-panel (Z#23125697)

src/pretix/control/forms/global_settings.py
This removes the legacy osm tileserver subdomains per https://github.com/openstreetmap/operations/issues/737 
Additionally the html for the leaflet attribution suggestion is escaped, so admins can copy the link for attribution easier
=> Fix leaflet osm tile suggestion

src/pretix/base/models/items.py
This has been supported by our apps for some time now (Android with https://github.com/pretix/libpretixui-android/commit/795f855e6b8060f9680e9919de0aff46bebe3232, iOS with https://github.com/pretix/pretixscan-ios/commit/c31f06067dfe763cfff2369f496b014d7d80573e)
=> Enable phonenumber question during checkin

src/pretix/base/payment.py
This negation seems to be incorrect - Redirection is *only* allowed if execute_payment_needs_user=True, right?
=> Fix docs for execute_payment

doc/api/resources/subevents.rst, src/pretix/api/views/event.py, src/tests/api/test_subevents.py
Found while adding support for subevents to pretix kiosk:
If the sub-event _name_ contains the slug by accident, the sub-event is found by the `SubEventFilter`, but if not, no results are returned. The main `EventFilter` already supports search for the event slug thanks to https://github.com/pretix/pretix/commit/71e7df303812a6f2c2b80ace1ab42335ca022be6 - this adds it for the sub-events.
=> API: Add parent event slug to subevent list search

src/pretix/base/payment.py, src/pretix/base/services/orders.py, src/tests/base/test_orders.py
This adds a payment provider setting to prevent payment reminder mails to be sent if that provider is chosen for payment. The setting is accessed (via method that could be overwritten in specific payment providers if needed) during the periodic task sending out those reminder mails.
=> Payment: Add setting to prevent reminder mails (Z#23123914)

src/pretix/presale/checkoutflow.py
Otherwise, we present a wrong heuristic result every twelve hours.
This is fixed by storing the cached value (long-lived, 30 days) and a validity flag (short-lived, 12 hours) separately. If the validity flag is expired, we still return the old value for the current request, but trigger a new calculation in a background task. After calculating, we set a new validity flag and update the cached value.
=> Fix: keep is_business heuristic result for a longer time (Z#23126061)

src/pretix/api/views/checkin.py, src/pretix/base/models/checkin.py, src/pretix/base/services/checkin.py, src/pretix/control/forms/checkin.py, src/pretix/control/templates/pretixcontrol/checkin/list_edit.html, src/pretix/control/templates/pretixcontrol/checkin/simulator.html, src/pretix/control/views/checkin.py, src/pretix/control/views/typeahead.py, src/pretix/static/pretixcontrol/js/ui/checkinrules.js, src/pretix/static/pretixcontrol/js/ui/checkinrules/checkin-rule.vue, src/pretix/static/pretixcontrol/js/ui/checkinrules/viz-node.vue, src/tests/base/test_checkin.py
This PR adds three new things to the check-in rules engine:
- Current "gate" assigned to the device – useful for situations like the one discussed in #3466
- "Number of entries since a freely choosable date" – useful if you e.g. have a three-phase event "build-up / event / teardown" and you want to create a ticket type that is valid exactly once during build-up and exactly once again during teardown
- "Number of entries before a freely choosable date" – I struggle to come up with a real-world use case for this one, but it seemed wrong only giving the "since" option, and implementing both forced me to do a cleaner implementation overall ;)
The first one is a simple additional variable ``gate`` in the JSON logic engine. The second and third are unfortunately more complex since they need to …
=> Check-in rules: New variables

src/pretix/control/templates/pretixcontrol/organizers/giftcard_acceptance_list.html
Just a simple typofix. Also visible in the screenshot on https://pretix.eu/about/en/blog/20230627-release-2023-6/.
=> Fix typo in gift card acceptance page

doc/user/events/widget.rst, src/pretix/static/pretixpresale/js/widget/widget.js
When using the widget with additional data (e.g. cookie consent) one needed to make sure, that all needed data-attributes are available when initializing the widgets. This PR adds the reactive data-attributes so one can change/add data-attributes on widgets/buttons which then get passed through to the reactive `widget_data`. This is e.g. useful to add `data-consent` which usually are available async.
Note: once the checkout process is started, changing data-attributes are not reflected onto the iframe (no reload ist done) to not interfere with checkout-UX.
=> Widget: make data-attributes reactive

src/pretix/plugins/stripe/templates/pretixplugins/stripe/control.html, src/pretix/presale/templates/pretixpresale/event/order_pay.html, src/pretix/presale/templates/pretixpresale/event/order_pay_change.html
This is the continuation of #3583.
I also did a quick scan for `round_decimal()` and I think we should have covered everything with this (except for plugins)
=> Display amounts with currency-derived decimals

src/pretix/presale/ical.py, src/tests/presale/test_event.py
Calendar apps have problems, when dtend is omitted. This PR always adds a dtend – with a default of one hour if `show_times` is set, else one day.
=> Calender/ics: always add dtend (Z#23131739)

deployment/docker/pretix.bash
The current default `2 * $(nproc --all)` is based on the number of installed processors. Changing this to `2 * $(nproc)` only counts CPUs available to the current process.
This change is required since somewhere between glibc 2.31 (Debian 11) and 2.36 (Debian 12) the algorithm to determine the number of configured processors on Linux changed from [counting the number of `cpu[0-9]+` entries in `/sys/devices/system/cpu`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/getsysstats.c;h=1ef077f9af465384eb3098f545ec55b3b97f19d3;hb=refs/heads/release/2.31/master#l242) to [reading `/sys/devices/system/cpu/possible`](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/getsysstats.c;h=064eaa08ae2f79b6f5ffb580c7d77b318494a804;hb=refs/heads/release/2.36/ma …
=> Docker setup: Change default number of workers to `2 * $(nproc)`

src/pretix/static/bootstrap/scss/bootstrap/_variables.scss, src/pretix/static/pretixbase/scss/_theme.scss, src/pretix/static/pretixbase/scss/_variables.scss
#1996 changed the placeholder color inside bootstrap dependency. This PR reverts this and uses the variable `$input-color-placeholder` instead to set a lighter shade of gray to improve the distinction between placeholder and real input. This breaks color contrast for a11y, but IMHO this is still worth it, as distinction between placeholder and input is more important than being able to read placeholder content. It furthermore makes placeholder-text italic.
=> UI: improve distinction between placeholder and input

src/pretix/control/templates/pretixcontrol/subevents/bulk.html, src/pretix/control/templates/pretixcontrol/subevents/detail.html
Somewhat analog to #3492
The panel-`<div>`s might not be the best solution for this PR.
Another idea I had was the same `<fieldset>` and `<legend>`, that are already sectioning the page. For a cleaner style, this might be preferable.
However: in that case, all form-fields that are not part of a form with a title should be grouped together *and* moved within the `Additional Settings` block to the end of the page, else it could get confusing for the user when they see
- Legend: Additional settings
- random Formfield
- Legend: Plugin
- formfield plugin
- formfield plugin
- formfield plugin
- random formfield
(Excellent showcase for this, when enabling CineSend, Seating and Kulturpass)
=> Subevent editor: Allow plugins to declare form titles

src/pretix/plugins/ticketoutputpdf/forms.py
When setting PDF-layouts for products, empty labels cause a fallback to another layout, which currently is marked „As above“. This PR makes empty labels more explicit to which layout this fallback points to.
Note: PlugIns using PDF-layout might need updates as well.
=> Product settings: improve fallback labels for PDF-layouts

src/pretix/control/templates/pretixcontrol/items/question_delete.html, src/pretix/control/views/item.py
This PR is hard for me to write a proper commit-message for. It adds a few tiny text improvements to make clear that deleting a question deletes the answer as well – although this could maybe be misinterpreted as the answer-options, that are created when having a „Choose one from a list“-question.
- changes delete-button to „Delete question and all answers“
- makes warning text more prominent by moving it inside an div.alert.alert-warning
- adding a help-text with link to set question ot hidden instead
- Fix: use internal of item if any
Is hiding a question a common operation? If so, we might add a button to do so directly in the questions overview? Or should the checkbox „hidden product“ be moved to the top of the first tab like the „Active“-checkbox on products?
=> Improve help texts when deleting questions (Z#23134288)

src/pretix/base/settings.py, src/pretix/presale/views/order.py, src/tests/presale/test_order_change.py
This adds a new strategy option for price changes in self-service order changes.
=> Order change: Allow price reduction as long as no refund is required (Z#23135268)

src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/checkout_confirm.html, src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/checkout_payment_form.html, src/pretix/static/pretixpresale/scss/main.scss
- If there is only SEPA account information, the bank information will no longer be shown until the order is complete
- If there is "other information" available, this change would be backwards-incompatible for some users, so we go a different route:  The bank information is no longer copy-able and if you hover it, there is a warning. This will hopefully catch users who try to copy the IBAN to early ;)
=> Bank transfer: Discourage payments before an order code exists (Z#23135042)

src/pretix/control/templates/pretixcontrol/event/mail_settings_fragment.html, src/pretix/control/templates/pretixcontrol/item/include_variations.html, src/pretix/control/templates/pretixcontrol/order/change_questions.html, src/pretix/presale/templates/pretixpresale/event/checkout_addons.html, src/pretix/presale/templates/pretixpresale/event/checkout_base.html, src/pretix/presale/templates/pretixpresale/event/checkout_membership.html, src/pretix/presale/templates/pretixpresale/event/checkout_questions.html, src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_cart_box.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/order_modify.html, src/pretix/static/pretixcontrol/scss/main.scss, src/pretix/static/pretixpresale/scss/main.scss
This PR tries to improve the visibility of the collapse-feature on panels by moving it closer to the actual label of the panel.
Instead of changing the existing HTML for .collapse-indicator in lots of places – as well as probably lots of plugins – this PR just hides `.collapse-indicator` and adds its own as a ::before.
Currently it uses FontAwesome similar to the .collapse-indicator, but does not get the fout-hiding from .fa-elements. So I think we need to switch to a svg-based background as a FOUT could happen.
=> UI: Improve panel collapse visibility (Z#23132549)

src/pretix/base/templatetags/money.py, src/tests/base/test_templatetag.py
This PR adds unit tests for the "money" template filter, which contains some complex logic. 
It also simplifies the rounding error protection, which was included twice, with minimally different logic, depending on the hide_currency flag (if True, only check for rounding errors if decimal places < 2; if False, always check for rounding errors). This PR only changes the behavior if hide_currency=False (the default), places >= 2.
=> Add test for money filter + streamline rounding error protection logic

src/pretix/static/pretixcontrol/js/ui/main.js
Currently, it doesn't do anything if placed on the dependent element (as it seems to be supposed to be used). If it were placed on the dependency, it would work *sometimes* (only on change, but not on page load).
=> Fix the 'data-checkbox-dependency-visual' attribute

src/pretix/api/serializers/event.py, src/pretix/base/settings.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/event/cancel.html, src/pretix/presale/templates/pretixpresale/event/order.html
As discussed instead of showing a date, we add customizable text snippets for terms of cancellation for unpaid/free and paid orders. If terms are available, they replace pretix’ auto-generated terms.
=> Add customizable terms of cancellation (Z#23135646)

src/pretix/api/views/order.py
Before this change, each order row needed an additional database query just to resolve the customer id (integer) to customer identifier (string).
With this change, django does a database JOIN.
This is a performance optimization. In my setup, querying a few hundred orders now takes ≈1.5s instead of 2 to 2.5s
=> API: Prefetch customer in order list view

src/pretix/plugins/stripe/payment.py, src/pretix/plugins/stripe/signals.py, src/pretix/plugins/stripe/static/pretixplugins/stripe/pretix-stripe.js, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_simple_messaging_noform.html
Same story as Affirm...
Some things about this, that irk me a little bit:
- The messaging-Component is always advertising the "pay in x installments". This might be offputting for people who do not know Klarna and the different payment options that are offered.
- We do not know, which payment options will be offered to the customer.
- We could in theory include the matrix of countries and products (3/4 installments, financing, pay later, pay now/sofort). But I don't feel like keeping that list up to date and we don't even know what the customer will actually choose
- This is not really a 1:1 drop-in replacement for SOFORT. Account registration is required.
- We have to absolutely transmit the customers country. I'm doing that right now on a best effort basis, but no idea what/if any …
=> Stripe: Add Klarna

src/pretix/plugins/banktransfer/tasks.py, src/tests/plugins/banktransfer/test_import.py
The bank import has weird handling of negative amounts. This is understandable, since we don't have sufficient information on what the user actually wants. This PR makes the handling less weird (although not entirely non-weird).
=> Bank transfer: Improve refund handling

src/pretix/control/middleware.py
When both two factor authentication and a password change are being forced, a redirect loop occurs. This commit resolves this by allowing the password change to occur between 2fa setup is forced. More specifically, 2fa is no longer forced whilst a forced password change is in operation.
=> Fix redirect loop caused when both 2fa and password change are forced

src/pretix/presale/views/customer.py
When a customer views the list of their orders on their profile, orders which have been cancelled with a fee are displayed as 'paid'. This commit fixes this by using the same logic from other places where order status badges are displayed.
=> Fix incorrect order status on customer profile orders

src/pretix/base/forms/questions.py
Currently, if a name format with salutation is selected, we show the following choices:
* `---` (pre-selected, but choosing this is not allowed)
* Mr
* Ms
* Mx
The idea behind this design choice was:
- We do not allow the empty option since we don't want people skipping the field out of pure laziness
- We always provide an option for people who are neither Mr not Ms. If someone chooses Mx, that will later not be used e.g. in emails, instead, we'll be addressing the person simple as `{given_name} {family_name}`
Now, we've had a complaint that not only some people might not want to use Mx either, but furthermore some people might not want to *disclose* which salutation is appropriate for them, therefore an empty option should be selectable. I still think it is a good idea to disallow the …
=> Name formats: Allow empty salutation

src/pretix/control/forms/subevents.py
This PR fixes a bug probably introduced in commit 2acf043 that initially creates two repeat-rules for bulk-creating dates in an event series.
=> Fix: remove duplicate repeat rule in subevent bulk creation

src/pretix/plugins/paypal2/templates/pretixplugins/paypal2/checkout_payment_form.html, src/pretix/plugins/stripe/payment.py, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_card.html, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_sepadirectdebit.html, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_simple.html, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_simple_messaging_noform.html, src/pretix/plugins/stripe/templates/pretixplugins/stripe/checkout_payment_form_simple_noform.html
A customer reports that end-users are confused when they see payment methods like Przelewy24 they have never heard of and there is no indication that this is for a different target group. This PR therefore adds explanatory texts to some payment methods.
=> Stripe/PayPal: Add explanatory texts (Z#23127572)

src/pretix/helpers/cookies.py, src/pretix/helpers/monkeypatching.py
Chrome is deprecating third-party cookies that may be used for tracking. The 1% trial is already running:
https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct
You can opt-in for the trial at chrome://flags/#test-third-party-cookie-phaseout
This breaks the widget entirely. The only suitable fix is marking our cookies as "Partitioned":
https://developers.google.com/privacy-sandbox/3pcd/chips
Unfortunately, Firefox and Safari not yet support that. If they do some day, it will also fix our cross-site issues there.
This PR sets Partitioned on all cookies that we set SameSite=None on, in all browsers that are known not to break with unknown cookie flags.
=> Add "Partitioned" flag to our cookies

src/pretix/presale/views/customer.py
In a7f7c64, a `customer_signed_in` in signal was introduced. However, when a user currently logs in using a popup, the signal is not fired. This PR resolves this.
=> Ensure `customer_signed_in` signal is fired for popup login

src/pretix/control/views/subevents.py
The "bulk copy" of subevents had inconsistent handling of `presale_start`/`presale_end` vs `available_from`/`available_until` of specific products. This PR unifies the behaviour.
=> Subevent bulk creation: Handle available_from of items the same way as dates

src/pretix/control/templates/pretixcontrol/item/index.html, src/pretix/control/templates/pretixcontrol/organizers/edit.html, src/pretix/static/pretixcontrol/js/ui/tabs.js
Currently tab IDs are autogenerated from the form and fieldset indizes (e.g. tab-0-7), causing them to change if a new tab is inserted in-between (which can happen dynamically by a plugin).
This change allows tab IDs to be set in the HTML code, making them persistent.
This change also adds IDs to some tabs of the organizer and event settings, where links should be added from other places.
=> Allow consistent deep links to tabs

src/pretix/base/invoice.py
Adds an invoice renderer variant that
- has more logo space
- does not have the sender in the "address window"
- has no event name included
- has the event date as part of the body of the invoice
This also renames the modern invoice renderer because the name no longer makes sense
=> Add simplified invoice renderer

src/pretix/base/models/orders.py, src/pretix/base/services/orders.py, src/pretix/base/services/tickets.py, src/pretix/base/settings.py, src/pretix/base/signals.py, src/pretix/base/ticketoutput.py, src/pretix/plugins/ticketoutputpdf/ticketoutput.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/templates/pretixpresale/event/fragment_downloads.html, src/pretix/presale/views/order.py, src/tests/base/test_orders.py, src/tests/testdummy/ticketoutput.py
The pretix-shipping plugin needs this to prevent the download only of the tickets which should be shipped physically to the customer, but not the tickets which should stay available for Print-at-home.
This modifies the `allow_ticket_download` signal so that it can not only return True or False to allow or block ticket download for an order as a whole, but alternatively return a list of OrderPositions, making only those downloadable.
https://github.com/pretix/pretix/pull/3836/files#diff-efaade2fa7bebe18526b3532280a3d750061a038953066c3a43b38be7d87c8d1R644-R652
=> Let plugins allow/prevent the download of individual tickets in an order

src/pretix/base/payment.py
Well, that was a fun one...
Setup:
- Limit Payment Provider to one or more countries
- Require approval for product
- Invoice address optional
- Do not provide Invoice Address during checkout
When selling an item that does *not* require approval, the Payment Provider can be selected, since this will trigger `InvoiceAddress.DoesNotExist`.
However, once approval is required and granted, the PaymentProvider cannot be selected, since `order_change_allowed` will compare `str(ia.country) not in restricted_countries` and fail: This is because once an order has been created, it will have an InvoiceAddress - even it is empty an `ia.country` is `''`.
Same thing for retrying a failed payment, it will fail due to the same cause.
=> BasePaymentProvider: skip country check if ia.country == '' (Z#23143749)

src/pretix/plugins/reports/exporters.py
This PR fixes a column-overflow by adding a Paragraph around each item (as is already done to variations as well as categories).
The second commit valigns the tdata top instead of middle – IMHO looks better, but that is just personal preference, so can undo if someone has a strong opinion on this.
middle:
top:
=> Fix item column overflow in order-overview PDF-report

src/pretix/static/pretixpresale/js/widget/widget.js
in the following example, the product "T-Shirt":
- has an unavailable_from date which is not reached
- and unavailable_from_mode = "info":
current behaviour of widget: (t-shirt variations seem to be available, but adding to cart fails)
fixed behaviour of widget: (all t-shirt variations are set to "Not yet available")
behaviour of regular presale is unchanged:
=> Widget: fix availability of variations whose base item is unavailable

src/pretix/control/templates/pretixcontrol/pdf/index.html
For the PDF-editor this PR moves some inputs around and visually groups them together by adding `<hr>`s.
=> PDF-Editor: improve grouping of object attribute inputs

src/pretix/static/pretixcontrol/js/ui/main.js
This PR adds an option, triggered by the HTML-attribute `data-close-on-clear`, to close the dropdown when all input is cleared. This is helpful when select2-inputs are optional/can be empty, as when clearing the input, but keeping the dropdown open, it feels that there needs to be input something. Latest Seating-plan selection uses this to better allow for empty setting „General admission“.
=> Select2: add option to close when clearing selection

src/pretix/static/pretixpresale/scss/widget.scss
This PR fixes the quantity-input which was cut off on very narrow screens (or if the widget container was less than 310px wide).
Additionally it adds a clearfix after the product-image containing element on mobile to fix some indent/column issues for price.
=> Widget: fix quantity cut-off on very narrow screens (Z#23141650)

src/pretix/base/models/event.py
To further test improving microdata this PR adds a hidden `event_microdata` to an event’s settings. This should contain a string of JSON-formatted microdata as described [here](https://developers.google.com/search/docs/appearance/structured-data/event?hl=de).
=> Presale: prefer event’s microdata from settings over generated microdata

doc/admin/config.rst
According to https://github.com/pretix/pretix/blob/master/src/pretix/settings.py#L315 the correct key is `sessions` not `session`.
(it seems the GitHub editor threw in a newline at the end…)
=> Correct config key in docs

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/voucher.html
To make parsing and calculating prices in presale-frontend easier (e.g. for  e-commerce tracking), this PR adds an attribute `data-price` to each `<article>` in presale.
=> Presale: add data-attribute price to article

src/pretix/base/services/cart.py, src/pretix/base/services/orders.py, src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/static/pretixpresale/js/ui/main.js
Two little things I noticed while reviewing https://github.com/pretix/pretix/pull/3968
- Extend the usage of "data-exclusive-prefix" to addon Items (currently only used on addon ItemVariations)
- Fix a typo in an error message
=> Presale: improve handling max-count for add-on products clientside

src/pretix/base/invoice.py
When there is no tax on invoice, the column header for the first column (description) was aligned right, which caused an irritating gap. This PR moves „description“ to the left.
=> Fix: left align first column header on invoices without tax (Z#23147636)

doc/admin/config.rst, src/pretix/settings.py
On systems that follow the FHS it may be desirable to separate logs and cache files into dedicated base directories (e.g. /var/log/pretix or /var/cache/pretix).
=> Allow customization of cache and log directory

src/pretix/_base_settings.py
Use our own ALL_LANGUAGES as default for LANGUAGES, instead of those provided by django.
Fixes the problem reported in https://github.com/NixOS/nixpkgs/issues/297708 and patched in https://github.com/NixOS/nixpkgs/pull/297729, which is also relevant to our wheel.
=> Build jsi18n for all supported languages

src/pretix/base/models/orders.py, src/pretix/base/services/cart.py, src/pretix/base/services/orders.py, src/tests/presale/test_checkout.py
This was a bug that took days to find. The story goes like this: A cart is created with four positions that each include four bundled positions. A discount is applied, changing the price of *one* of the four top-level positions to a reduced value. The list of position IDs gets passed to `perform_order()`, which later passes it on to `transform_cart_positions()`. `transform_cart_positions()`, however, receives the positions in an order that has the first-level product *after* the bundled products that belong to it. Therefore, it can't properly assign the parent-child relationship between the positions.
The main reason is that cart positions are processed in "database order" in a number of places, i.e. we make `SELECT` queries without an explicit `ORDER BY` statement, leading the database …
=> Fix invalid orders being created in a complex situation

src/pretix/plugins/stripe/payment.py, src/pretix/plugins/stripe/signals.py
As PayPal is one of those payment methods, that require the Connect Platform to be certified, too, we are not making the choice available in UI just yet.
=> Stripe: Add PayPal (#4049) (Z#23123667)

src/pretix/base/services/orders.py
Up until now, there were two behaviors for orders within the approval process:
- `event.settings.mail_attach_ical = True` + `settings.mail_attach_ical_paid_only = False`: The initial email has the ical attached, the approval mail has no ical file attached
- `event.settings.mail_attach_ical = True` + `settings.mail_attach_ical_paid_only = True`: The initial email has no ical attached, the approval mail also has no ical file attached
Attaching/not attaching the ical to the first message is working as intended, this PR aims at the second, approval mail...
=> Approval Process: Attach ical to approval-messages if properly configured

src/pretix/presale/checkoutflow.py
When using profiles in customer accounts, answers to custom questions for country codes showed the actual country code and not the human readable country name in the profile’s description. This PR formats country-code answers the same way select-from-list answers are formatted as a dict with key-value where country-code is the key and value is the human readable country name.
=> Fix: show human-readable country name in profile description for custom country-code questions (Z#23148948)

doc/admin/installation/community.rst, doc/admin/installation/index.rst
As discussed in #4011, a separate community install guide page with the Helm chart for Kubernetes deployment
=> Add a community install guide page

src/pretix/base/services/orders.py, src/tests/presale/test_order_change.py
Scenario:
- Main ticket
- Addon product for t-shirts
- Addon product for workshops
Order with a main ticket and a t-shirt, now a user wants to change the order to include a workshop. However, `available_until` of the t-shirt is over since they already started production. Currently, pretix will automatically remove the t-shirt when trying to book a workshop because the t-shirt is no longer part of the `set_addons` input.
There are different approaches how to solve this:
- Show unavailable products in the order change view as if they were not unavailable, and allow keeping or reducing their amount, but not increasing it.
- Do not silently remove products that are no longer available.
This PR chooses the latter, because it was simpler to implement and seems to be the safer option to go with …
=> Do not remove unavailable addons when changing order (Z#23150855)

src/pretix/base/services/quotas.py, src/pretix/presale/views/organizer.py
This fixes a performance issue introduced by the new settings lookup in #4036
=> Fix N+1 query in event calendar found by sentry

src/pretix/static/pretixbase/scss/_theme.scss, src/pretix/static/pretixcontrol/js/ui/main.js
When an error-alert is given, this PR adds descriptive links to invalid inputs including label and first help-text (usually the error) of that input.
TODO: We might think about changing the link-style in alert-danger to e.g. red with underline?
=> Add links to invalid inputs on error alert (Z#23149061)

src/pretix/api/views/order.py, src/pretix/control/views/orders.py, src/pretix/presale/views/order.py
This is not a perfect solution as it does not handle all code paths to create invoices, but it handles all that seem likely to be triggered concurrently
=> Introduce locking to prevent duplicate invoices (Z#23150548)

src/pretix/base/models/discount.py, src/tests/base/test_pricing_discount.py
Example:
Two discounts:
A) "For every 1 item1, you get three item2 for 10 % off."
B) "For every 1 item1, you get five item3 for 10 % off."
Cart: 2x item1, 2x item2, 6x item3
Expected result: 2x item1 full price, 2x item2 discounted, **5x item3 discounted, 1x item3 full price**
Current result without fix: 2x item1 full price, 2x item2 discounted, **6x item3 full price**
(because discount A erroneously "consumes" both item1, instead of just one)
=> Discount bugfix

src/pretix/base/pdf.py
As pointed out in my issue at pypdf, merging rotated pages is very simple. See https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html#merging-rotated-pages
=> Simplify merging rotated background PDFs

src/pretix/plugins/paypal2/payment.py, src/pretix/plugins/paypal2/views.py
We are seeing some customers using APMs losing payments and bookings, as they seem to get lost in the process.
- Customer pays with APM such as giropay or SOFORT
- Order does not receive any webhook LogEntries for order being captureable
- pretix doesn't capture anything
- order expires
- PayPal refunds the money back after some days
As of right now, the only time a capture is occurring is when a the PayView POSTs (after a successful payment) or if the success-view is hit. This is done through the `execute_payment()`-function of the payment provider.
We are in the process of researching what the customer is doing exactly to apparently never hit these pages (or if they hit them, why nothing happens).
By manually removing the calls to `execute_payment` from `views.py`, I was able to …
=> PPv2 APM: Create referenced PPObjects for APM Orders; enable webhooks to capture them

doc/admin/maintainance.rst
The docs of 2024.4 describe the metric names to be `pretix_XX_logins` with `XX` being successful or failed. However, the `/metrics` endpoint returns:
```
pretix_logins_successful 2.0
pretix_logins_failed{reason="2fa"} 1.0
pretix_logins_failed{reason="invalid"} 1.0
```
=> Docs: Fix metrics names

src/pretix/base/pdf.py
pypdf happily handles PDFs with versions greater than what our reportlab produces (1.4). When a background PDF uses features from versions higher than 1.4 that creates problems. This PR fixes it by:
- when using pypdf, the pdf_header of the output will match the bigger pdf-version of either background PDF or foreground PDF.
- when using pdftk, manually setting the pdf-version did not yield the same success, but instead of placing the background inside the foreground PDF, stamping the foreground PDF onto the background PDF worked. We now just need to make sure, that the background PDF has the same amount of pages as the foreground PDF.
=> PDF: use PDF-version from background-PDF if higher than foreground in pypdf

src/pretix/presale/templates/pretixpresale/event/seatingplan.html
The change from precompiled CSS to Custom Properties broke seatingframe as no precompiled CSS is now loaded there. This PR adds the results from presale.signals.html_head to its HTML-head. This adds the needed CSS-files for seating to be displayed correctly.
CAVEAT: I am not sure though, what the implications are when using additional plugins as presale.signals.html_head does totally different things than just adding CSS – I looked through my plugins locally and they either filter for specific pages when adding stuff or „just“ add tracking javascript.
=> Fix missing CSS in seatingframe

src/pretix/presale/signals.py, src/pretix/presale/templates/pretixpresale/event/seatingplan.html, src/pretix/presale/views/event.py
To not include all possible html_head responses into the stripped down seatingframe, we (temporarily?) add a new signal seatingframe_html_head
=> Add signal seatingframe_html_head

src/pretix/static/pretixcontrol/scss/main.scss
This PR does a micro-UI improvement by removing a border-top from the plugin-list.
Before with featured:
After with featured:
Before without featured:
After without featured:
=> UI: in plugin-list only show border-top when necessary

src/pretix/control/forms/renderers.py, src/pretix/presale/forms/renderers.py
Labels for disabled checkboxes currently show `cursor: pointer`. Bootstrap3 offers a class `.disabled` on `div.checkbox` to make contained lables have `cursor: not-allowed`. This PR adds it to the FieldRenderer.
Instead of changing the Renderer, thanks to the „new“ CSS-`:has` we could add a CSS rule such as
`.checkbox label:has(input:disabled) {cursor: not-allowed}`
I am not sure which way is preferable. I tend to the CSS only solution though.
=> Set cursor: not-allowed on labels for disabled checkboxes

src/pretix/control/forms/item.py
This PR adds the file-type check for product image that we talked about in #4308 It does not add support for webp, whcih we might add at a later stage?
=> Fix file-type check for product image

src/pretix/static/pretixpresale/js/ui/main.js
This PR adds auto-filling questions from invoice address fields by matching id-suffixes, placeholder-attributes and (visible) labels to placeholder-attributes.
It removes the code to alyways update all questions when one of the answers changes to just updating the question matched to the one answer, that was changed.
=> Auto-fill questions from invoice address (Z#23143497)

doc/admin/installation/manual_smallscale.rst, src/pretix/base/exporter.py
python3-dev is named twice in the package dependencies. I deleted it in line 68, it remains in line 67.
=> Docs: Remove redundant package dependency

src/pretix/static/pretixcontrol/js/ui/main.js
In a special case when setting up a custom email adress, only one warning-box was present – but this box was inside a .panel, which sometime happens to be an error-message to a group of inputs, which needs to be converted to a link as well. This PR fixes the auto-linker when it tries to add an error-message to itself.
=> Fix auto-linking error-inputs self-referencing (Z#23159088)

src/pretix/presale/views/cart.py
Redeeming a voucher failed if current time is outside the booking period and the shop was accessed via time machine.
=> Fix voucher redemption with time machine [Z#23159226]

src/pretix/plugins/badges/exporters.py
When background-PDFs with a cropbox and a higher PDF-version than our PDF-default of 1.4 are used (which triggers a special stamp operation when using pdftk), then when placing multiple pages on one page (e.g. nup-badges), the cropbox made all pages except the first one disappear. This PR fixes it by setting the cropbox to the trimbox, which is/was set to the mediabox.
=> Fix nup-badges for PDFs with cropbox (Z#23160479)

src/pretix/settings.py
Checking whether a path does not exist before trying to create it does not follow the Python paradigm of asking for forgiveness, rather than permission, and opens up a time-of-check to time-of-use race.
I did in fact hit that race condition while testing the 2024.7.0 release in a NixOS VM test, probably because we have multiple units (web and periodic) coming up in parallel, and they both import the settings.py.
```
[   23.299368] systemd[1]: Starting pretix web service...
[   23.308752] systemd[1]: Started pretix asynchronous job runner.
[   31.135238] pretix-web-pre-start[1046]: Traceback (most recent call last):
[   31.137615] pretix-web-pre-start[1046]:   File "/nix/store/iawyf9d0snhqk47yhpz83w6bgf8kvyf2-pretix-2024.7.0/bin/.pretix-manage-wrapped", line 32, in <module>
[   31.145118] …
```
=> Prevent race condition in directory creation

src/pretix/presale/views/event.py
Honor the time machine in the following situations, where it was ignored before:
- Filtering visible product variations by availability date (fixes issue #4201)
- Filtering visible products by availability date overridden in the subevent ("Date") settings (fixes issue #4271)
- Visible date range of subevent calendar
=> Fix #4201, Fix #4271 -- Time machine issues

doc/development/setup.rst
These variables effectively hardcode the location from which the script is run.  We shouldn't need these since git should know it is inside a repo when run.
GIT_DIR isn't set by default, at least for me.  If we still need to get the root path for the repo, we can use `git rev-parse --show-toplevel`.
=> Remove git dir and work tree config from pre-commit hook

src/pretix/static/pretixcontrol/js/sb-admin-2.js
Originally window.load was bound to inside a jquery-ready call, which sometimes does not work as the window.load event was already fired.
The diff looks a bit weird, but I basically just moved the binding to window.load/resize outside the jquery-ready call.
=> Control: fix initial sidebar display for mobile

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html
I stumbled upon a divergent html source when having uncategorized products listed. Especially combined with a waitinglist on seating this could create a valid, but somewhat strange page-structure for a11y. This PR unifies the handling of h3s for grouping products into categories.
=> A11y: improve/unify html-source for uncategorized products

src/pretix/base/customersso/oidc.py
This fixes OIDC-Logins for LinkedIn, which - as outlined [here](https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?tabs=HTTPS1#step-3-exchange-authorization-code-for-an-access-token) require the client_id and client_secret to be present in calls to the token endpoint.
Well - that's what LinkedIn is saying - in reality the client_id is not really, really required...
I am torn to just merge this change, as I am not sure how other OIDC-providers will handle this addition. In an ideal world, they would just ignore the extra fields - but will they?
=> OIDC: Respect token_endpoint_auth_methods_supported (Z#2164777)

doc/api/resources/taxrules.rst, src/pretix/base/models/tax.py
I have not been at ease with our eu_reverse_charge flag for a while (see #1837 for first attempt to remove it). For now, I'd like to formally deprecate it.
The reason is that the case of a non-business customer in a different EU country is handled in a way that is only correct for companies with <10k€ in sales of this type. Larger companies need to use the One-Stop-Shop mechanism that requires a more complex setup. We cannot properly take on the responsibility of handling this for clients.
=> Formally deprecate eu_reverse_charge

src/pretix/base/views/tasks.py, src/pretix/presale/templates/pretixpresale/waiting.html, src/pretix/static/pretixpresale/scss/waiting.scss
=> Render progress info on non-javascript fallback page for celery tasks

doc/development/api/general.rst, src/pretix/api/views/device.py, src/pretix/base/signals.py
This provides both the original and updated version of the Device so subscribers can see the changes.
=> Add device_info_updated signal

src/pretix/presale/checkoutflow.py, src/pretix/presale/templates/pretixpresale/event/checkout_addons.html
=> Show proper error message in case of add-ons that are required, sold-out and hidden

src/pretix/presale/templates/pretixpresale/event/checkout_addons.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/static/pretixpresale/scss/_checkout.scss, src/pretix/static/pretixpresale/scss/_event.scss
=> Cross-selling: Use different label if there are no add-on products

pyproject.toml
asyncio_default_fixture_loop_scope requires at least 0.24
=> Dev: add support for asyncio_default_fixture_loop_scope in pytest-asyncio

src/pretix/testutils/mock.py
In my dev setup, `PYTEST_XDIST_WORKER` returns `None`. Not sure this is a config error on my part though.
=> Fix testutils redis mock

src/pretix/control/templates/pretixcontrol/items/category.html
translation(de):
> Bitte beachten Sie, dass Cross-Selling-Kategorien nur als Marketing-Feature gedacht sind, und nicht geeignet sind, um sicherzustellen, dass Produkte nur in bestimmten Kombinationen erhältlich sind.
=> Add warning that cross-selling can't prevent unwanted combinations

pyproject.toml
It doesn't work anymore on python 3.13, since
2to3 is deprecated and removed (PEP 594).
Trying to build on Fedora 41 result in:
Downloading slimit-0.8.1.zip (88 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
Python 3.X support requires the 2to3 tool.
[end of output]
And slimit is not used in the code base nor anywhere in git (no single match)
=> Remove slimit dependencies

src/pretix/base/models/checkin.py, src/pretix/control/forms/filter.py, src/tests/control/test_checkins.py
On pretix.eu production, we have an event with ~14k tickets where filtering the check-in list for people currently present takes a mindblowing **7 minutes**. Looking at the query plan, PostgreSQL executes the subquery with the window function 14082 times – once for every order position. This is a complete waste of resources, as the subquery is not dependent on the order position it is executed one. This feels like an optimizer bug in PostgreSQL to me.
While looking at the query for hours, I noticed there is a pointless layer of subqueries in there. And luckily, removing this pointless layer seems to resolve the issue. So here's my proposed change.
Query plan excerpt (before):
```
->  Group  (cost=2983.73..2983.75 rows=5 width=8) (actual time=27.584..27.584 rows=0 loops=14082)
Group Key: …
```
=> Fix performance issue in filtering checkin list (Z#23170917)

doc/admin/installation/docker_smallscale.rst, doc/admin/installation/manual_smallscale.rst
> [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead
=> docs: update nginx config example

src/pretix/static/pretixbase/scss/_bootstrap_vars.scss, src/pretix/static/pretixbase/scss/_theme_variables.scss
Originally lighten/darken was used to make colors lighter/darker for alert-boxes. Depending on color, this resulted in pure white quickly or even overly vibrant colors. This PR makes alert-boxes use colors blended with black/white by using our custom color-mix functions `shade` and `tint`.
Before (way to vibrant green e.g.)
After
=> [A11y] Improve color combinations for alerts

src/pretix/base/forms/questions.py, src/pretix/base/models/orders.py, src/pretix/base/views/js_helpers.py, src/pretix/control/templates/pretixcontrol/base.html, src/pretix/control/templates/pretixcontrol/order/change_questions.html, src/pretix/presale/checkoutflow.py, src/pretix/presale/templates/pretixpresale/fragment_js.html, src/pretix/static/pretixbase/js/addressform.js, src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixpresale/js/ui/main.js, src/tests/presale/test_checkout.py
This PR consolidates the front-end (javascript) code to show/hide and mark as required/optional certain address components depending on the selected country. Information on the required fields is loaded on demand. It's loaded in the same request as the list of (federal) states of a country, so no additional request is required.
Example response for Germany:
this resolves the following problems:
- the state select box was always marked as optional, even if it was required because the whole address was required and a country with "state in address" was selected - this is now handled correctly
- even for countries where we don't know about the correct address fields, we always required street, zipcode and city, if the whole address form was obligatory (but only street address if the whole …
=> Update address field logic (Z#23163120)

src/pretix/presale/templates/pretixpresale/fragment_calendar.html, src/pretix/static/pretixbase/scss/_theme_variables.scss, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/_calendar.scss
This PR improves accessibility on the mobile calendar-view as it turns the calendar-table into a role="grid" with keyboard-selectable option, info on number of events on that day and making `#selected-day` an aria-live-region.
It further improves the mobile UI by mimicking a single event box on the day-label with the most important event-availability taking precedence.
Before (just brand-primary, no hover, no selected state):
After:
=> Improve organizer/event-series calendar UI on mobile

src/pretix/static/pretixpresale/scss/_event.scss
This PR removes padding from .panel-body when it does not have any childnodes – due to excessive white-space the :empty-selector does not work. The implication of this is, that .panel-body with plain-text will have no padding. I have never come across a panel-body with plan-text though.
Before
After:
=> Hide empty panels

src/pretix/base/payment.py, src/pretix/base/services/cart.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart_box.html, src/pretix/presale/views/__init__.py, src/pretix/presale/views/cart.py, src/pretix/presale/views/event.py, src/tests/presale/test_cart.py, src/tests/presale/test_event.py
"Gift card" and "vouchers" are concepts so similar, many ticket shop users can't tell them apart. Since the voucher input shows up first, people are likely to enter a gift card as a voucher. Previously, we have shown a specific error message, explaining people to enter the gift card in a later step. However, as the real world shows again and again, people do not read error messages. They just see the red bubble and know if failed, but don't read our explanation.
Therefore, this PR changes the system to just allow it! We'll just add a payment dataset to the cart and show a cart, even there are no products selected yet. Since we introduced #2912, we can quite easily do so, and it's a nice way to remove friction from the checkout.
=> Allow to enter gift cards into the voucher input (Z#23171961)

src/pretix/static/pretixpresale/scss/_forms.scss, src/pretix/static/pretixpresale/scss/main.scss
The new fieldset-accordion markup was worng by using p and div inside legend-elements. This PR fixes the CSS when changing them to correctly label and span.
=> Fix fieldset accordion css

src/pretix/static/bootstrap/scss/bootstrap/_forms.scss, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/_forms.scss
This PR undoes commit a747ab1, which changed a bootstrap css – although we probably never receive an update to bootstrap 3, I guess we should not change it if possible. Furthermore it adds slideUp/Down-animation through Javascript to the panels as using transform with plain CSS does not properly due to auto-height and padding issues.
=> Move cursor fix for disabled fieldsets from bootstrap to presale

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/voucher.html
This PR groups the number inputs and its rocker-buttons into a fieldset with a legend, which improves the screenreader experience by reading that legend as well when focusing the +/- rocker buttons.
=> [A11y] Improve number inputs for screen-readers

src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/static/pretixpresale/scss/main.scss
This PR just changes from label to textbubble for better handling of color contrast. It also adds some icons, just because it looks nicer.
I am not sure about the wording though, especially „Book now“ is a call to action and not a status label and kind of asks to click the label – with textbubbles it is not that bad as they do not look so much like the button next to it, but it still kind of feels to much of a call to action. I would change the wording to „Available“ instead and maybe even change the text on the actual button from „Tickets“ to „Book now" although „Book now“ feels a little less strong/fitting IMHO.
Before 
After
Forgot to add a screenshot of the new textbubble-success-warning:
=> [A11y] fix color-contrast for event-list status-bubbles

src/pretix/static/pretixpresale/js/widget/widget.js
This PR adds a `html_id` to `$root` for each widget/button-instance, which can later be used as reference/prefix in labels, etc. for improving e.g. a11y. It adds an optional parameter `html_id` to `create_widget` and `create_button`. If not provided, it falls back to the element’s id attribute or creates a random id by using the already existing `makeid`-function.
=> Widget: add unique html_id for use in labels, etc.

src/pretix/presale/templates/pretixpresale/organizers/index.html
When an event is planned to go on sale, the status-bubble is a very long text including the date, which causes overflow issues on smaller screens. This PR makes the column for the status-bubble a little wider and also moves the availability date in a new line that allows white-space to wrap. This now works down to about 360px width (so e.g. iPhone 6 upwards should  be fine – at least in german).
Before:
After:
If we need to go lower to e.g. 320px, then we would need to dump the bootstrap-cols and do a combination of pull-left/pull-right and put the status-bubble and the btn-link in the same col-element. Actually works like a charm on very small screens, but we lose styling the button as btn-block so every button has the same width. Not sure it is worth it for these very very narrow …
=> Fix organizer event list status overflow

src/pretix/static/pretixcontrol/scss/_forms.scss, src/pretix/static/pretixpresale/scss/_forms.scss
Somehow accordion-panels got lighter panel-headings than all other panel-default panel-headings.
Instead of setting the colors again, use the cascade on panel-default. I double checked, any `div.accordion-panel` also is `.panel.panel-default`, so no need to define colors in CSS twice.
=> Fix color differences for panel-heading in accordion-panel

src/pretix/base/settings.py
The reasons for the corrections are as follows:
This results in names being displayed as “泽东毛” (phonetically "ZedongMao"), which is inconsistent with the example and opposite to the name order in cultural contexts where Chinese characters are used.
Furthermore, using the simplified Chinese version of “毛泽东” may be difficult to understand in regions that do not use simplified characters. (Simplified Chinese is used primarily in Mainland China and Singapore.)  Additionally, the name of a leader of the Chinese Communist Party may be considered inappropriate in some regions.
I propose replacing this example with “孫文” (Sun Wen, the official name of “Sun Yat-sen”).
The characters in this name are identical in both simplified and traditional Chinese, and they also match the character style used …
=> Name order and Examples Defined in PERSON_NAME_SCHEMES, Adaption to Japanese addressing system

src/pretix/base/auth.py, src/pretix/base/timemachine.py, src/pretix/presale/views/event.py, src/pretix/presale/views/order.py
This button is currently missing on custom domains:
With this PR, we use the `pretix_event_access` cross-domain session, if available, to determine whether the user is logged into a backend session with `can_view_orders` permission  to show th button if appropriate.
=> make "Show in backend" button on ticket pages available on custom domains

doc/api/resources/orders.rst
This PR fixes a typo in the documentation, just noticed that during reading :)
=> Fix typo in documentation

src/pretix/base/reldate.py, src/pretix/base/templates/pretixbase/forms/widgets/reldate.html, src/pretix/base/templates/pretixbase/forms/widgets/reldatetime.html
Use namedtuples for the parts of RelDate[Time]{Field,Widget} 
Fix two bugs in the process:
- RelativeDateTimeField.clean: validate days relation_to instead of minutes relation_to when "Relative date" is selected
- RelativeDateTimeField.set_event: apply relative_to filter not only to minutes, but to days as well
=> Refactor RelativeDate(Time)Field and -Widget

src/pretix/presale/templates/pretixpresale/event/base.html
Micro adjustment from a11y-audit – link text and label should be the same otherwise it is a „barrier“. The label does not add value to understanding what or where the link leads to, so can and should be removed.
=> [a11y] Remove h1 aria-label in presale

src/pretix/base/invoice.py, src/pretix/helpers/reportlab.py
Valid ZUGFeRD invoices must be compliant with PDF/A-3. pretix-zugferd ensures this by passing them through ghost script. Unfortunately, if the logo contains transparency, this will still fail with:
```
<validationReport jobEndStatus="normal" profileName="PDF/A-3B validation profile" statement="PDF file is not compliant with Validation Profile requirements." isCompliant="false">
<details passedRules="144" failedRules="1" passedChecks="4239" failedChecks="1">
<rule specification="ISO 19005-3:2012" clause="6.2.10" testNumber="2" status="failed" failedChecks="1">
<description>If the document does not contain a PDF/A OutputIntent, then all Page objects that contain transparency shall include the Group key, and the attribute dictionary that forms the value of that Group key shall include a CS …
```
=> Invoice rendering: Remove transparency from logos (Z#23179391)

src/pretix/base/models/orders.py, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html
Simple approach to reassure customers they got the expected discount.
- I decided against showing the original price, since then we'll get into discussions about `listed_price` vs `original_price` and pre-voucher vs post-voucher. This way, it's showing the percentage given by the discount rule and hopefully no-one will care about these details.
- I switched the icons because it looked weird otherwise: "% 50 % discount".
=> Show percentage of discount in cart (Z#23176955)

src/pretix/base/logentrytype_registry.py, src/pretix/base/logentrytypes.py, src/pretix/base/models/log.py, src/pretix/base/models/orders.py, src/pretix/control/logdisplay.py, src/pretix/control/views/event.py
This creates LogEntryType definitions for all missing `action_type`s (order changes, check-in events, settings changes of PaymentProviders and TicketOutputs).
This also checks whether the stored `content_object` is of the expected model type, preventing incorrect links. 
Refactoring:
- Moving the base LogEntryType definitions for our models to their own file was required to allow referencing model classes without import loops.
- HTML escaping was moved into `make_link` to make it less likely to oversee in the LogEntryType definitions
- pretix.event.order.deleted is now logged with the deleted Order model as content_object, matching the other `*.deleted` action_types
=> Define LogEntryTypes for all actions in pretix core, improve content_object handling

src/pretix/helpers/metrics/middleware.py
For some time now, I was able to observe on my local dev instance, that uploaded files (such as header graphics, background-PDFs, etc.) were not accessible and the server instead returned a `TypeError` like this:
> TypeError at /media/pub/thumbs/2dc3b4bbad87f9fea81f2d60919157ea.5000x120_iUpmgGG.jpeg
> can only concatenate str (not "NoneType") to str
This is caused when `url.url_name` is none - in those cases, the `url.namespace` will probably be empty too and thus I am not sure how much the logging makes sense...
This fixes the issue for me, but I am not sure this is the best way to handle this.
I would also assume that this bug is only an issue in Dev-environments, since we normally serve the `/media/`-folder through a reverse proxy where the requests would never touch the …
=> MetricsMiddleware: Do not record pretix_view_duration_seconds for urls with no url.url_name

src/pretix/base/customersso/oidc.py, src/pretix/control/forms/organizer.py
Z#23180758
I guess, we could also just blindly append the `query_parameters` to the URL and assume that everything has already been properly urlencoded... But this seems safer...
=> OIDC: Allow to add query parameters to Authorization URL

src/pretix/base/invoice.py, src/tests/base/test_invoices.py
=> Invoice renderer: Group invoice lines even with addons (Z#23173618)

src/pretix/presale/checkoutflow.py
Z#23181657
Especially when the fields are locked, we need to copy the information over - or the customer is stuck in a dead-end.
=> Widget: Prefill email_repeat with data-email attribute (Z#23181657)

src/pretix/base/settings.py
We extended the scope of this setting over time and people use it for things it was not intended for, so this wording tries to make the intention clearer while keeping the limitation.
=> Change wording for "show_dates_on_frontpage" setting

src/pretix/control/logdisplay.py, src/pretix/control/views/global_settings.py, src/pretix/static/pretixcontrol/js/ui/main.js
- Fixes link in pretix.event.order.changed.split
- Adds link to existing order in pretix.event.order.changed.split_from
- Fixes display of checkin entries without datetime in data
- Adds additional info for admins (action type, linked content object):
=> Fix log display for checkins and order splits (Z#23181229)

src/pretix/control/templates/pretixcontrol/vouchers/detail.html
A common workflow is to search for a voucher by code, which navigates directly to the voucher details page. Previously, the delete button was only available in the formset list view, but in many cases, vouchers are never accessed via this view, especially when a large number of vouchers are active. This meant users often had no visible way to delete a voucher.
This commit adds a delete button to the voucher details page, allowing users to remove vouchers directly from this interface.
=> Add delete button to voucher details page

src/pretix/plugins/banktransfer/tasks.py, src/tests/plugins/banktransfer/test_import.py, src/tests/plugins/banktransfer/test_parsing.py
When dates are ambiguous, use the event's locale to infer whether the day or month comes first. Since regions follow certain date format conventions, this helps make more accurate guesses.
This could probably be improved by (1) adding other countries to the check (although this can be extended later), or even better, (2) allowing the date format to be specified to avoid any wrong interpretations. However, I think this might be a reasonable stepping stone.
=> Improve date format heuristic for bank statement import

src/pretix/static/pretixpresale/js/ui/main.js
When copying ansers from the invoice form to the first product-question, the CSS-selector failed if an apostroph `'` was used in the label/placeholder. We still need to keep the CSS-selector based on the label/placeholder, as there is no other way to match custom question in products (like for a company) to the corresponding input in the invoice-form.
=> Fix copying invoice answers with special chars in label (Z#23177041)

src/pretix/base/services/cart.py, src/tests/presale/test_cart.py
For items with "Free price input" (user-selectable price), vouchers redeemed on existing cart should apply if and only if the chosen price equals minimum price.
Old behavior is that the voucher is marked as applied but the price doesn't change.
=> Fix voucher application on "free price" items (Z#23183254)

src/pretix/control/forms/filter.py, src/pretix/control/templates/pretixcontrol/orders/index.html, src/pretix/control/templates/pretixcontrol/vouchers/index.html
Adding autofocus is an interuption to normal flow in keyboard access and bad for a11y. This is usually only sensible on single-purpose pages such as search (as in search-engine) and login/auth. As discussed, we keep it for the control-dashboard for now as not to interrupt workflow after login (you can just type away immediately to search). It is not ideal, but hopefully a workable compromise. I looked into alternatives like changing tab-order or manually auto-focusing through JS when the first thing one does after login is type, but that is to much magic and did not help.
In presale, there is an autofocus on the ContactForm, which is kind of in-between. One could argue it would help when you start the checkout-process and as you clicked a „button“ (actually a link), you showed the intent …
=> [A11y] Remove all autofocus in pretix-control except login/auth and dashboard (Z#23180233)

src/pretix/static/pretixpresale/js/widget/widget.js
Before this fix, `window.PretixWidget.open("https://pretix.eu/org/event/", null, 12345, null, payloadCheckout);` does not actually open the subevent
=> Widget: Fix opening a subevent dynamically (Z#23176995)

src/pretix/presale/context.py, src/pretix/presale/views/__init__.py, src/pretix/static/pretixpresale/js/ui/cookieconsent.js, src/pretix/static/pretixpresale/js/widget/widget.js
The current approach of the "data-consent" field of the widget has two problems:
- There is unclear precedence if there is already a value stored in the widget. We inverted the precedence in #4862, but it is still weird. The problem is, that we have different usage scenaries, such as a well-built main website that has proper cookie consent management and a user that only ever interacts with pretix through the widget on that page. In that case, we want later updates to the cookie consent choices on the main website to also apply to the widget. The other case is a user who is also interacting with the pretix directly and has already chosen their consent through the pretix UI and then stumbles over the widget and there is likely no intention of revoking prior consent. Therefore, I propose …
=> New mechanism to transfer cookie consent from the widget (Z#23181715)

src/pretix/plugins/checkinlists/exporters.py
This rarely caused flaky tests on CI
=> Checkin list CSV export: Use stable orderings

src/pretix/presale/templates/pretixpresale/event/base.html, src/pretix/presale/templates/pretixpresale/organizers/base.html
Users usually do not want to have the list of old events or the list of events in a specific month as a search result. However, these are still interesting pages for search engines to crawl and discover events. So let's set them to noindex but follow.
=> Search engines: Do not index event lists for specific dates (#23185037)

src/pretix/base/settings.py
Currently it was possible to enter negative as well as very large positive numbers, which then failed calculation for validity-dates. This PR sets min 0 and max 99 years.
=> Add min/max-imit on giftcard_expiry_years

src/pretix/control/templates/pretixcontrol/checkin/bulk_revert_confirm.html
It is a question, so it needs to end with a question mark.
=> Add missing question mark to delete check-ins confirmation form

src/pretix/base/forms/questions.py, src/pretix/base/settings.py, src/pretix/base/views/js_helpers.py, src/pretix/control/context.py, src/pretix/control/forms/event.py, src/pretix/control/templates/pretixcontrol/order/index.html, src/pretix/presale/context.py, src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html, src/pretix/presale/templates/pretixpresale/event/fragment_cart.html, src/pretix/presale/templates/pretixpresale/event/order.html, src/pretix/static/pretixbase/js/addressform.js
In Italy, the province is part of the mailing address:
http://www.bitboost.com/ref/international-address-formats/italy/
This is used in the same way that e.g. a US state is part of an address. So far, our field has always been named "State", even though it reflected e.g. the "Provinces" of Canada. Nobody complained about this, because structurally, the thirteen provinces by Canada are on a similar level of government as e.g. a US state. I'm sure they Canadians don't like them being named states, but they are probably used to it.
In contrast, in Italy the "province" is not structurally on the same level as a "state". The equivalent to a "state" in Italy would be the 20 "regions". However, these are not used in the addresses – the ~100 "provinces" are. So this PR also allows …
=> Address form: Add provinces for Italy

src/pretix/static/pretixpresale/js/widget/widget.js
When redeeming a voucher, the widget did not submit widget-data if it had `disable-iframe`. This PR further unifies handling of form submission for redeeming a voucher in the widget. Instead of adding all needed hidden inputs through html manually, it creates a property `hiddenParams` which gets generated from `$root.voucherFormTarget` search-params. That way we make sure, these params are always in sync and we only need to make changes in one place.
=> Refactor widget redeeming voucher form

src/pretix/control/templates/pretixcontrol/orders/search.html, src/pretix/control/views/orders.py
Previously, if input was valid, the entire search query was just ignored.
=> Order search: Proper input validation with error feedback for advanced search

src/pretix/control/forms/filter.py
Only crashed on PostgreSQL, but also did not search properly for dates
=> Order search: Fix typing errors in advanced search (fixes #4900)

src/pretix/control/forms/filter.py, src/pretix/helpers/models.py
Currently, it always says:
> Search query: Order status: None
Regardless of the order status chosen
=> Display "Order status" correctly in the "Search query" line of advanced search results

src/pretix/static/pretixpresale/js/ui/main.js
When there is an image-question for the product, a hidden input for cropdata is created, which the copy-to-first-form fails on as that hidden input does not have an id and also not a label. This PR does two things to prevent this: 1. it only tries to match labels if input has an id (because otherwise the get-label-through-id-selector fails) and 2. do not even select inputs with type=hidden as possible matches.
=> Fix label matching when copying answers (Z#23186844)

src/pretix/base/payment.py
The 'offsetting' payment method includes a clear description specifying which order the offsetting applies to, but the associated refund does not. This commit ensures refunds use the same message as payments, making the associated order explicit.
=> Clarify description for offsetting refunds

src/pretix/api/serializers/__init__.py
We stumbled over an issue where copying an event through the API had a `data["sales_channels"]` being `None`, which caused the serialization to fail. This PR only migrates legacy sales_channels if there are any.
=> API: fix event creation sales-channel-migration

src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixpresale/js/ui/main.js
When a filter form asks users to select a datetime range, it is a common scenario that users want to filter just by date. However, this will easily lead to off-by-one-errors, as "Feb 1st, 00:00 to Feb 28th, 00:00" is missing the last day of February. This PR tries to detect these fields and use a different initial value for the time field.
=> Date picker: Guess default time 23:59 for end dates (Z#23182900)

src/pretix/static/pretixpresale/js/widget/widget.js
This PRs improves focus management in the widget when using any navigation methods other than opening the iframe-overlay – this usually only happens on event-series or when the widget is included on a organizer-level. To make screen-readers recognize new content loaded dynamically and not lose focus-order, focus is moved to the widgets container and the screen-reader reads the aria-label, which is the event’s name (empty for organizer level, could be improved if a subevent is selected).
Making the whole container aria-live is not helping here, as aria-live will read the whole container once it is loaded.
Usually only interactive elements are focusable (depending on browser). To make the container focusable (at least in Safari with VoicerOver), we need to add a `tabindex` to it. This makes …
=> [A11y] Improve focus management + navigation in widget ajax

src/pretix/helpers/daterange.py, src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/presale/views/organizer.py, src/tests/base/test_models.py, src/tests/helpers/test_daterange.py
When outputting date ranges in HTML the connecting hyphen is read as minus. This PR changes it to use „until“ similar to how it is already in use in fragment_calendar.html
In all cases except one, the connecting hyphen has surrounding spaces. Only in german with a day-range, when it is used without surrounding spaces. I used `mark_safe(until.strip())` there, although I am not sure that is the correct or most elegant way.
=> [A11y] Improve HTML output of daterange

src/pretix/control/templates/pretixcontrol/pdf/index.html, src/pretix/static/pretixcontrol/js/ui/editor.js
This PR tries to improve the usability of the page-size controls in the PDF-editor and better distinguish between custom PDF background (which also defines the page-size) and manual page-size with new, empty background.
Before:
After:
=> PDF-Editor: improve UI for page-size and background PDF

src/tests/control/test_checkins.py
`test_checkins_list_filter` happened to randomly falsely match op.secret with its short attendee_name „a4“. This PR changes the test to use a longer attendee_name.
=> Fix checkin-list-filter test randomly matching secret

src/pretix/static/pretixpresale/js/ui/cart.js, src/pretix/static/pretixpresale/js/ui/main.js
When using min/max with datepicker, the minDate/maxDate is parsed with moment() and replaces the viewDate inside datepicker. We have three options to fix this bug:
1. Change bootstrap-datepicker dependency to apply `options.locale` when parsing a date.
2. Add our own parseInputDate to `options` when instantiating datepickers
3. Globally tell `moment()` to use `body[data-datetimelocale]`
I did not want to change a dependency if not needed (1.). Providing a custom `options.parseInputDate` seemed error-prone as we need to provide it everywhere where we instantiate a datepicker (2.). So I chose 3, which IMHO anyways feels like the right way to do to make sure all dates on the page are used with the correct locale.
=> Fix datepicker locale when using min/max

src/pretix/static/datetimepicker/bootstrap-datetimepicker.js, src/pretix/static/pretixcontrol/js/ui/main.js, src/pretix/static/pretixpresale/js/ui/main.js
When using min/max dates in datepicker (either one or both) when opening, closing and then opening the datepicker again, the currentDate is now and datepicker-nav is disabled. This PR fixes the behaviour, ~~but changes a depency – although an old one. I was not able to find a way to fix this from the outside, so changing it in the dependency was the only way. Actually, there might be a way~~: register an event-listener to `dp.hide` and set the `viewDate(viewDate)` manually to a correct one inside the boundaries of minDate/maxDate. This needs to be done everywhere, where we instantiate datepicker though, but that is currently only in one spot.
=> Fix datepicker date display when using min/max (Z#23185544)

src/pretix/static/pretixbase/scss/_theme.scss, src/pretix/static/pretixpresale/scss/main.scss
Text inputs need a contrast at least 3:1 to its surrounding (white in our case). This PR increases the contrast of the border and also adds the 2px focus-outline used on buttons to text inputs.
Before:
After:
It further improves the cart-select-button-checkbox focus state by adding the focus-outline to the `.btn-checkbox` instead of the checkbox.
Before:
After:
=> [A11y] fix border contrast for inputs

src/pretix/base/templates/pretixbase/email/base.html, src/pretix/presale/templates/pretixpresale/base.html, src/pretix/presale/templates/pretixpresale/event/seatingplan.html, src/pretix/static/pretixpresale/scss/main.scss
Users need to be able to scale the website. When removing `user-scalable=false`, the website zooms slightly on smaller iPhones (e.g. iPhone SE 2020) when focusing input elements due to them having a fontsize of 14px. To remedy this, we have several options.
Original screenshot for reference:
1. Change everything to 16px (ie. 1rem on `body`)
2. Only change font-size on inputs (ie. 1rem on `.form-control`)
3. Only change overall font-size to 1rem on smaller screens
4. Only change inputs’ font-size on smaller screens
IMHO changing only the inputs’ font-size looks okay on the product-list when only entering quantities or prices, but on the checkout questions page, it looks a bit odd. Changing everything to 16px (1rem) feels a bit to big IMHO, so I would go with option 4.
=> [A11y] allow users to scale website

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/presale/templates/pretixpresale/event/voucher.html
While reviewing #5022, I noticed a double border that is caused by a new label element interfering with the :first-child select. The bug is not new with #5022, but becomes more visible.
Before:
After:
=> Product list: Fix DOM position of label causing wrong border

src/pretix/static/pretixpresale/scss/main.scss
When we changed our fontsize to a rem-based system, we overlooked a small detail on the text-inputs’ vs. buttons’ height – inputs were slightly higher than buttons. This PR fixes the height difference.
Before:
After:
=> Fix rem-based input height

src/pretix/_base_settings.py, src/pretix/static/pretixbase/scss/_rtl.scss
See discussion in https://github.com/raphaelm/django-i18nfield/issues/39
=> Add CSS for right-to-left language input fields

src/pretix/base/forms/questions.py
The min/max constraint on date/datetime inputs is not accessible in either the widget nor – when manually entering a date that exceeds the constraints – is an error message given. The easiest solution seems to add a description that explains these min/max input constraints.
This PR adds a help_text to date/datetime questions having a min/max constraint, if no other help_text is provided in the configuration. That way users can overwrite the help_text/constraint-description manually.
=> [A11y] add min/max as help_text to date/time inputs

src/pretix/base/exporters/orderlist.py
Not 100% sure how we end up with an empty list of attendee_name_parts here, maybe through changing name_scheme during the event or by importing orders? This PR adds a safeguard to the export.
=> Fix order export for empty attendee_name_parts

src/pretix/base/payment.py
This is a quick fix for handling empty giftcards – not sure, how it happened that the giftcard-property was not even sent through POST though …
=> Fix handling of empty giftcard-code

src/pretix/presale/forms/renderers.py, src/pretix/static/pretixpresale/scss/_forms.scss
The * after the label for required inputs is not explained anywhere. We do have `.sr-only` „required“ in the labels, but users without screen-reader need an explanation what the * means. One of the solutions can be a footnote before (or maybe after) the form explaining what the * means – this would require a lot of work on every form and probably isn’t the visually most pleasing option.
This PR explores the option to change the * to the actual text „required“, like so:
Another alternative, that I need to check, is to instead of a CSS-content generated star, to use an image/icon with a title-attribute. Although I doubt that that would be enough, as the error states that the * needs a „visual explanation“.
=> [A11y] make text "required" visible in labels

src/pretix/plugins/banktransfer/static/pretixplugins/banktransfer/swisscross.css, src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/pending.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/main.scss
This PR fixes some a11y with the old boostrap-tabs implementation. It adds a new implementation loosely based on https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
In presale, tabs are currently only used for payment qr-codes. This PR uses a simpler nav-pills-like tab-navigation instead of the previous box-inside-a-box tab-interface – on the hand, UI is lighter (alhtough the btn-primary might be a bit bold, but btn-default does not feel light a „selected“-state) and on the other hand, the original panel-style tabs was not possible to implement with the current set of styles due to not allowed HTML-nesting of li-elements inside an element with role=tablist.
=> [A11y] fix tablist issues

src/pretix/static/pretixpresale/scss/_forms.scss
=> Remove line-break before "required" in label on small screens

src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/views/event.py
Add new ctx to count visible subevents to use in template
(why not |length filter in tag? because the different list-types and branches in the template make that veeery complicated)
=> Presale: Hide subevent lists if subevents exist but none are visible (Z#23186153)

src/pretix/presale/forms/customer.py, src/pretix/presale/templates/pretixpresale/event/checkout_customer.html, src/pretix/presale/templates/pretixpresale/organizers/customer_info.html, src/pretix/presale/templates/pretixpresale/organizers/customer_login.html, src/pretix/presale/templates/pretixpresale/organizers/customer_password.html, src/pretix/presale/templates/pretixpresale/organizers/customer_registration.html, src/pretix/presale/templates/pretixpresale/organizers/customer_resetpw.html, src/pretix/presale/templates/pretixpresale/organizers/customer_setpassword.html, src/pretix/presale/views/customer.py, src/tests/presale/test_customer.py
The forms for customer accounts (create, login, reset-password, etc.) all were set using the `DefaultRenderer`, which did not include any of the a11y-improvements we made with `CheckoutFieldRenderer`. This PR changes the customer forms to use the `CheckoutFieldRenderer`, which causes the forms to be a horizontal layout. It is not ideal for every form, especially the ones with longer labels (e.g. in the register form with „What is the result of X +Y?"), but IMHO it is a good compromise and now the forms are visually more like other presale-checkout forms.
Before:
After:
=> [A11y] Improve customer account forms

src/pretix/presale/templates/pretixpresale/event/checkout_base.html, src/pretix/static/pretixbase/js/details.js, src/pretix/static/pretixpresale/scss/main.scss
The half-open cart is complicated for accessibility. The containing panel needs to be open for the button „show full cart“ to be visible and accessible. Therefore this PR adds an additional foldable element inside the details/summary. To not irritate screenreader users by removing the trigger-button, one needs to keep it in the DOM as long as it has focus.
This PR changes the behaviour when clicking on summary. Before it was opening the hidden cart inside the details, but should have closed the open details. This was confusing for screenreader users. So this PR keeps the default details/summary behaviour (which causes a click on the panel-title to close the panel) and only have the half-open cart open with a click on the button „show full cart“.
When sneak-peek is inside details (as it is …
=> [A11y] Fix sneak-peek for cart

src/pretix/control/templates/pretixcontrol/event/live.html, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/organizers/customer_address_delete.html, src/pretix/presale/templates/pretixpresale/organizers/customer_addresses.html, src/pretix/presale/templates/pretixpresale/organizers/customer_membership.html, src/pretix/presale/templates/pretixpresale/organizers/customer_memberships.html, src/pretix/presale/templates/pretixpresale/organizers/customer_orders.html, src/pretix/presale/templates/pretixpresale/organizers/customer_profile_delete.html, src/pretix/presale/templates/pretixpresale/organizers/customer_profiles.html, src/pretix/presale/templates/pretixpresale/organizers/index.html
In some panels we use `<b>` to make the panel more prominent than others. So accordings to a11y-testing b adds additional semantic meaning to the heading-elements of a panel, so it should be replaced with strong.
=> [A11y] replace b with strong for better semantics

src/pretix/static/pretixpresale/js/widget/widget.js
This PR removes disabled-attribute from buy-button and improves error-dialog by making it role=alertdialog (good for close-button being focused).
=> [A11y] fix widget buy button being disabled

src/pretix/presale/templates/pretixpresale/event/resend_link.html
=> Fix weird markup on "resend link" page

src/pretix/static/pretixpresale/scss/_theme.scss
When using a dark background, the focus outline was not following the contrast-color.
Before:
After:
=> Fix page-header-links outline color contrast

src/pretix/presale/templates/pretixpresale/base.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/main.scss
This PR adds a skip-link as the first element on the page to skip to the main-area on the page. JavaScript makes sure, there will be an element `*#content` available on the page, that can be linked to. The skip-link is only is visible when it has focus.
=> [A11y] add skip-link to main content

src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar.html, src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar_week.html, src/pretix/presale/templates/pretixpresale/fragment_calendar.html, src/pretix/presale/templates/pretixpresale/fragment_event_list_filter.html, src/pretix/presale/templates/pretixpresale/organizers/calendar.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_day.html, src/pretix/presale/templates/pretixpresale/organizers/calendar_week.html, src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/_calendar.scss, src/pretix/static/pretixpresale/scss/_event.scss, src/pretix/static/pretixpresale/scss/_forms.scss, src/pretix/static/pretixpresale/scss/main.scss
This PR fixes the nav-select dropdown for accessibility – the current auto-submit is not allowed and generally auto-submit is discouraged. So this PR makes the submit-button visible again.
It also arranges the form a bit differently and unifies the look of the calender across event-series and organizer-view by moving everything inside a panel (the organizer’s list-view already was inside a panel).
Before:
After:
~~Note: Somehow sometimes the `.input-group` for select and submit-button is not rendered correctly and the select and the button do not have the same height. Might be a rounding issue on the rem-size, but I could not figure out why.~~ UPDATE: it is a rounding issue. See [c174756](https://github.com/pretix/pretix/pull/5078/commits/c17475660bab905ea595ac43625f213b0c9cbb95)
=> [A11y] fix calendar nav dropdown

src/pretix/presale/templates/pretixpresale/event/fragment_subevent_list.html, src/pretix/presale/templates/pretixpresale/organizers/index.html, src/pretix/static/pretixpresale/scss/main.scss
According to a11y-testing `<dl>` ist not that well supported in screenreaders, so this PR changes the event-list to `<article>`.
Note: there is currently some mismatching in headings structure on the page, which this PR does not take into account. Another PR will fix this.
=> [A11y] change event-list from dl to articles with h3

src/pretix/static/pretixpresale/js/widget/widget.js
When a click-listener is registered on the element, the element needs to be focusable as well. That click-listener is only helpful on mobile screen, so we need to disable it on bigger screens. Also, the td needs to be a focusable element, e.g. role=button.
=> [A11y] Widget fix td-cells being clickable but not focusable

src/pretix/base/context.py
Due to potentially mixing links with normale text, we would need link-underlines in the footer. Instead we link the whole poweredby-footer.
=> [A11y] change footer poweredby-link to pretix.eu if no poweredby_url

src/pretix/presale/templates/pretixpresale/event/base.html, src/pretix/presale/templates/pretixpresale/organizers/base.html, src/pretix/static/pretixpresale/scss/main.scss
Links that are inline with normal text need to be underlined as otherwise the color-contrast between a link and normal text needs to be 4.5 as well as both text and link need have a contrast to the background (white) of 4.5. This limits the colors choices dramatically, so this PR adds CSS to style links accordingly.
It adds a CSS-class `.no-underline` to mark safe links explicitly. ~~Currently I could not find any of those safe links.~~ Links in help-text or other markdown-texts or even the „Add to calendar“-link on the homepage need to be underlined.
The h1 text-link combined with the date might be a problem though. Currently only the event’s name is linked, but next to it is the date of the event. Link-to-text-contrast is very low (1.2), so I guess we need to make the whole h1 with the …
=> [A11y] underline inline-links

src/pretix/presale/templates/pretixpresale/fragment_modals.html, src/pretix/static/pretixpresale/scss/_forms.scss
This PR fixes the cookie-consent dialog’s labels and help-texts – one should not have links in labels. Consent-Checkboxes are marked up similar to the checkout-style checkboxes.
This PR does one change to the checkout-style checkboxes: it indents the help-text the same as the label.
Before:
After:
=> [A11y] Fix cookie-consent-form labels + help-text markup

src/pretix/presale/templates/pretixpresale/fragment_login_status.html
Not necessarly a a11y-issue as it is a button and that can have a aria-label, but it is a best practise to have a visual label as well. And as „Log in“ is written out, I think „Log out“ should be as well. Also added a login-icon to the login-link.
Before:
After:
=> [A11y] logout-button make label visible

src/pretix/static/pretixpresale/scss/main.scss
The default bottostrap focus outline – especially the outline-offset – was not properly overwritten.
Before (barely noticable the first checkbox has focus)
After
=> [A11y] Fix checkbox:focus style

src/pretix/_base_settings.py, src/pretix/static/pretixbase/scss/_rtl.scss
As per [the pretix translation](https://translate.pretix.eu/languages/he/), the [gettext manual](https://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html), and [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes#he)
=> Use he as language code for Hebrew

src/pretix/presale/templates/pretixpresale/organizers/index.html
As we have a button next to it, that works the same, it should be okay to omit the underline on the event titles.
=> [A11y] Do not underline event-titles in organizer’s event-list

src/pretix/static/pretixpresale/scss/main.scss
The skip-link can be overlayed by a the back-to-organizer-link or by a `.panel` in the widget. Interestingly this wasn’t a problem in my testing, but came up during external a11y-testing. As a safe-gurad, this PR adds a z-index of 9999 to the skip-link.
=> [A11y] fix skip-link z-index

src/pretix/static/pretixpresale/js/widget/widget.js
To improve navigating through the widget in a document-tree view, this PR adds heading-levels to products labels
=> [A11y] add heading-level to product list

src/pretix/base/templatetags/dialog.py, src/pretix/presale/templates/pretixpresale/event/index.html, src/pretix/presale/templates/pretixpresale/fragment_modals.html, src/pretix/static/pretixbase/scss/_theme.scss, src/pretix/static/pretixpresale/js/ui/cookieconsent.js, src/pretix/static/pretixpresale/js/ui/main.js, src/pretix/static/pretixpresale/scss/main.scss
This is a draft to use a dialog[role=alertdialog] to show a message to the user when trying to add no products to the cart. The dialog currently has no styling yet, it is just to show how easy native dialogs would be and IMHO there is no need for a custom `window.pretix.dialog` implementation. Just add the dialog to the DOM and use it in JS directly. ~We might be able to make it easier to create a correct `<dialog>` by adding a blocktag-templatetag in django, but for the draft that seemed out of scope.~
I also added a simple_tag `{% dialog %}` and `{% enddialog %}` to help with most of the boilerplate.
=> [A11y] show dialog when empty add-to-cart instead of disabling the button

src/pretix/static/pretixpresale/scss/_checkout.scss
counteract change introduced in b638c009523dc687e053fe0cca71e1657961f22b
Before:
After:
=> Checkout: Center-align step-done fa

src/pretix/static/pretixbase/scss/_bootstrap_vars.scss, src/pretix/static/pretixpresale/scss/main.scss, src/pretix/static/pretixpresale/scss/widget.scss
Changing the `$btn-default-border:` and `$input-border` in pretixbase instead of presale main.scss fixes contrast issues in all of pretix. This might be considered a breaking change with the widget – but we have already changed lots of colors in the past, which also came through to the widget. So I would say, it should be fine to keep using `$btn-default-border:` and `$input-border`, which then would tickle down into widget.v1.scss. Or should I hard-code the old values in widget.v1.scss?
=> [A11y] fix input border & focus style

src/pretix/base/settings.py, src/pretix/static/pretixbase/scss/_bootstrap_vars.scss, src/pretix/static/pretixbase/scss/_theme_variables.scss
This wasn’t/isn’t a problem as e.g. alert-success uses shaded colors with enough contrast. But in the event settings with the new contrast requirement of 4.5, it looks a bit odd that the default color produces a warning of to low contrast.
=> [A11y] fix contrast for default success color

src/pretix/static/pretixpresale/js/widget/widget.js
This PR removes the link (and underline) from variation products to unify the look in product lists and not be forced to have links styled as links. Add a helper-script to make item-titles behave like label for inputs, that focus their inputs onclick.
To mimick current behaviour, clicking the variation-title not only focuses the variation button, but also opens the variations.
=> Widget v2: Remove link from variation-product title

src/pretix/static/pretixbase/scss/_bootstrap_vars.scss, src/pretix/static/pretixpresale/scss/widget.scss
This PR changes the status-coloring of events in calendar and list-view to resemble pretix-presale. It needs #5163 to remove links underline.
List-view only has a state-bubble, which differs from how this is displayed in pretix-presale (where there is a status-bubble and a button). So list-view status-bubble is styled tha same as the event in calendar:
=> Widget v2: Fix calendar events color contrast

src/pretix/static/pretixpresale/scss/main.scss
The calendar-view navigation uses .active for showing the current link. When hovering this link, the default styling makes the background way to dark due to $border-hover being darker to meet other contrast requirements.
Focus/hover before:
Focus/hover after:
=> [A11y] fix color contrast on hover for .active default-buttons

src/pretix/base/forms/questions.py, src/pretix/presale/forms/renderers.py
Ideally single-input name-schemes should have a properly marked up `<label for="…">`, but due to input-ids being only available on render, we cannot easily create the correct HTML-label. This PR changes the behaviour so that for single input name-schemes we still create a fieldset (ie. role=group) with a proper legend and aria-label for the single input. Not perfect, but at least accessible and better than before (inaccessible).
=> [A11y] add group labelling to single input name-widget

src/pretix/static/pretixbase/js/details.js
Since adding the renew-button to the sneak-peek we had an interactive element inside an aria-hidden element. This is not allowed, so this PR adds the inert-attribute to the container, so the button is not focusable any more.
=> Fix sneak-peek missing inert-attribute

src/pretix/static/pretixpresale/js/widget/widget.js
This PR fixes pre-filling the quantity-input when either a single variation-product with more than one variation is used.
=> Widget: fix prefill quantity=1 with single variation-product

src/pretix/static/pretixpresale/js/widget/widget.js
showDialog of iframe-dialog (with loading spinner) only reacted on frame_src instead of frame_loading – which did not trigger the loading-spinner while API-request to add to cart was running.
=> Widget: fix loading spinner not showing on API-request

src/pretix/static/pretixpresale/js/widget/widget.js
Suggestion from external a11y-test to use the visual available description, that is the same as the previous aria-label
=> [A11y] Widget: change calendar table aria-label to labelledby

src/pretix/static/pretixpresale/js/ui/iframe.js, src/pretix/static/pretixpresale/js/widget/widget.js
According to external A11y-testing the title of the iframe needs to update with the content for it to be meaningful enough. This PR adds a postMessage-mechanism if the presale-page is inside an iframe. Note though, that the label of the dialog stays the same „Checkout“.
This PR adds a very specifc event. We as well think about using a different name (pretix:widget:page) and e.g. add more info such as what type of page (shop, checkout – maybe even with steps –  and order-confirm) – this would give embedding pages the option to redirect to their own confirmation page, if they wish so.
=> [A11y] Widget: pass doc title in overlay to iframe.title

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html, src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html, src/pretix/static/pretixbase/js/details.js
Variations toggle-button was missing aria-controls. aria-label was different to content, which is not an error, but not ideal – so changed to aria-describedby to add context-info.
=> [A11y] fix variations toggle-button

src/pretix/control/templates/pretixcontrol/event/settings.html, src/pretix/static/pretixcontrol/js/ui/tabs.js
If "Hide all products that are sold out" is enabled, the waiting list won't work.
Resolves issue #5188
=> Show warning on incompatible waiting list options

src/pretix/control/templates/pretixcontrol/auth/base.html, src/pretix/control/templates/pretixcontrol/base.html, src/pretix/presale/templates/pretixpresale/base.html, src/pretix/presale/urls.py, src/pretix/presale/views/theme.py
Window 10 still uses browserconfig.xml for pinned Websites on the start-screen. Windows 10 EOL is mid October 2025. We might consider, removing all meta-tags from HTML, but keep the URL-route still available for now.
=> Remove browserconfig.xml

src/pretix/base/reldate.py, src/pretix/control/forms/event.py, src/pretix/control/forms/filter.py, src/pretix/control/forms/item.py, src/pretix/control/forms/orders.py, src/pretix/control/forms/organizer.py, src/pretix/control/forms/subevents.py, src/pretix/control/forms/vouchers.py, src/pretix/control/templates/pretixcontrol/event/fragment_geodata.html, src/pretix/control/templates/pretixcontrol/subevents/bulk.html, src/pretix/control/templates/pretixcontrol/subevents/bulk_edit.html, src/pretix/control/views/subevents.py, src/pretix/plugins/autocheckin/forms.py, src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/new_refund_control_form.html, src/pretix/plugins/sendmail/forms.py, src/pretix/settings.py, src/pretix/static/pretixcontrol/scss/auth.scss
This PR removes the automatism to set the placeholder to the same value as label if not otherwise defined. This makes the forms IMHO way cleaner.
Before:
After:
=> FormFieldRenderer: do not set placeholder automatically

src/pretix/base/templates/pretixbase/email/order_details.html
In order confirmation emails, subevents already list the location. This PR adds the location for a „normal“ event as well.
=> Add event's location to order confirmation mail (Z#23185285)

src/pretix/control/forms/vouchers.py
"title column" made me think of a column for the "title" part of names – looking at [the docs](https://docs.pretix.eu/guides/vouchers/#sending-out-vouchers-via-email), I think "title row" is better (though linking to the docs directly might be worthwhile here anyways?)
=> Fix bulk voucher CSV field description

src/pretix/control/forms/filter.py
With the move to a hybrid plugin instead of event level, payment provder banktransfer failed to register as a payment provider on order export.
=> Fix missing payment provider "banktransfer" on export

src/pretix/static/pretixpresale/js/ui/main.js
Fixes #5446 
To actually make it work, we need to disable automatic form validation and call it ourselves and look for invalid inputs and scroll them (or its label) into view.
=> Fix html-based form errors not being scrolled to in iOS/Safari

src/pretix/control/views/orders.py, src/pretix/control/views/organizer.py
This is especially important in admin mode, because currently you can setup scheduled exports in admin mode, but they will never run if your user does not have the permissions to do so outside of admin mode.
=> Scheduled exports: Check permissions on creation

src/pretix/plugins/ticketoutputpdf/exporters.py
When exporting all tickets as pdf, the wrong layout was chosen for tickets from a different sales-channel than "web".
=> Fix ticket-pdf export layout selection by saleschannel

src/pretix/api/serializers/organizer.py, src/pretix/api/views/organizer.py, src/tests/api/test_permissions.py
:exclamation: Check for security implications of this change
As of right now, none of our apps would be using this endpoint - but I feel like exposing it to the unrestricted SecurityProfile shouldn't do any harm.
=> API/Organizer: Allow Device-Token access to Organizer settings; expose mf0aes_random_uid

src/pretix/base/pdf.py
When using unknown placeholders and combining them with newlines, it could happen that the content that is to be encoded in the QR-code is newlines only. This PR strips all newlines. If we want to keep the possibility to end a QR-code with a newline (although AFAIK this should better be enabled in the barcode-scanner to add a return/line-feed after the scan), then we should move the `.strip()` into the if-check two lines below.
=> PDF: fix handling empty qr-codes
