pretix/pretix

doc/development/api/general.rst
doc/development/api/plugins.rst
doc/development/api/restriction.rst
doc/development/concepts.rst
doc/development/goals.rst
doc/development/setup.rst
doc/development/structure.rst

Spelling corrections

---

src/pretix/base/exporter.py

use long names in list comprehensions, so that we have not just one letter, but a more expressive word indicating where we pull the information from.

improved top-to-bottom-adhoc-readability

---

src/pretix/control/views/event.py

Seems to be a similar issue as with product picture upload.

Fixed ticket generator pdf upload

---

src/pretix/presale/views/locale.py

Thanks to David Gullasch for finding this one.

Fix Open Redirect issue in /locale/set

---

src/pretix/control/templates/pretixcontrol/item/base.html
src/pretix/locale/de/LC_MESSAGES/django.po
src/pretix/locale/de_Informal/LC_MESSAGES/django.po
src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/checkout_payment_confirm.html
src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/checkout_payment_form.html

Second one in a row, this time for german_informal

Typos & translations

---

src/pretix/presale/views/cart.py

Thanks to David Gullasch for pointing this one out. - This is an example of why refactoring user input validation as per #220 might be a good idea.

Assert that the item count is a positive integer

---

doc/development/setup.rst

Address #160
Adding step to run collectstatic on development setup (lines 52-55)
Also added extra info required for testing (lines 21-25).

Add step to run collectstatic and info for testing env #160

---

src/pretix/control/views/vouchers.py

enable substring-search when matching voucher tags

---

src/pretix/base/services/orders.py
src/pretix/locale/de/LC_MESSAGES/django.po
src/pretix/locale/de_Informal/LC_MESSAGES/django.po

There was a missing in a sentence

---

src/pretix/control/views/vouchers.py

This is a fix for this MySQL issue: https://code.djangoproject.com/ticket/24662
It is (imo) the best solution over custom SQL queries or explicit int
casting later on.

Fix voucher tag overview with MySQL (closes #253)

---

src/pretix/helpers/formats/en/formats.py
src/pretix/plugins/ticketoutputpdf/ticketoutput.py

Add order code to tickets generated by PDF
Add order code to ticket settings in control
#148

Add order code to pdf and to ticket settings #148

---

deployment/docker/nginx.conf

Leaking less data is always a good idea

Simple change to leak less information to make recon harder.

---

src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
src/static/pretixpresale/js/ui/main.js

Enhancement for copying answers into multiple tickets with a checkbox state as UI

Added copying multiple tickets answers enhancement (#149)

---

src/pretix/base/__init__.py
src/pretix/base/signals.py
src/pretix/control/__init__.py
src/pretix/multidomain/__init__.py
src/pretix/plugins/checkinlists/__init__.py
src/pretix/plugins/paypal/__init__.py
src/pretix/plugins/reports/__init__.py
src/pretix/plugins/ticketoutputpdf/__init__.py

New flake8 version finds more (correct) issues.

Add PEP8 style empty lines in appropriate places

---

AUTHORS
src/pretix/control/context.py
src/pretix/control/forms/orders.py
src/pretix/control/templates/pretixcontrol/base.html
src/static/pretixcontrol/js/ui/main.js

Previous build on a different branch was failing so I managed to grab the latest changes from the main branch, merged the changes in a new branch, ran tests and get the new PR.

Fix for Disable weekends in datetimepicker for expiry #274

---

src/pretix/base/models/event.py
src/pretix/base/models/organizer.py
src/pretix/base/validators.py
src/tests/base/test_models.py
src/tests/presale/test_event.py

Not sure about a couple of things - the validation message correctness and the most appropriate place to place the unit tests.

Fix #294 - blacklist for slug validation

---

src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_form.html
src/pretix/plugins/banktransfer/views.py

Banktransfer filtering

---

src/pretix/presale/templates/pretixpresale/event/index.html
src/pretix/presale/urls.py
src/pretix/presale/views/cart.py
src/tests/presale/test_cart.py

Add 'Empty Cart' button to cart.
Add test_remove_all to tests
One note: I added a new view `CartRemoveAll` but the only difference from `Cart Remove` is the success message.... Is that ok or are they too similar to have both?

Add empty cart button #161

---

src/pretix/base/services/stats.py
src/pretix/control/templates/pretixcontrol/orders/overview.html
src/static/pretixcontrol/scss/_orders.scss

Change column layout in order overview. Closes #302

---

src/pretix/control/logdisplay.py

More extensive log display when changing an order email.

---

doc/plugins/pretixdroid.rst
src/pretix/plugins/pretixdroid/urls.py
src/pretix/plugins/pretixdroid/views.py
src/tests/plugins/test_pretixdroid.py

Simple pretixdroid status API

---

src/pretix/plugins/banktransfer/views.py

Now if you try to "Start upload" on Import bank data page without choosing any file, the error message reads "You must choose a file to import."

Added specific error message for no file uploaded for empty bank import.

---

AUTHORS
src/pretix/control/templates/pretixcontrol/vouchers/bulk.html
src/pretix/static/pretixcontrol/js/ui/main.js

Pressing "Generate random vouchers" will result in a malformed AJAX request and an undefined error message.
I've added a check that the input field is not empty and changed the input field to `type=number`.
Please give it a short test before merging.

Added validation for voucher generation field

---

src/pretix/presale/templates/pretixpresale/event/index.html
src/pretix/presale/urls.py
src/pretix/presale/views/event.py
src/requirements/production.txt
src/setup.py
src/tests/presale/test_event.py

Hello,
Here is the PR for #389 
Please feel free to leave me some comments!

added event ical download feature

---

src/tests/plugins/test_sendmail.py

Start adding tests to sendmail plugin.
Hi, @raphaelm! I didn't make much progress on my own. When you have some time, would you please help me move this forward?
Thanks!

add test for sendmail plugin

---

src/pretix/control/templates/pretixcontrol/event/permissions.html

The boxes vor adding and editing vouchers were switched for new users.

Wrong checkbox order

---

src/pretix/base/forms/__init__.py
src/pretix/base/forms/validators.py
src/pretix/control/forms/event.py
src/pretix/plugins/sendmail/forms.py

Added class-based validator right to the forms.py at plugins/sendmail and integrated it in MailForm in same file.

Fix #448 -- Integrated PlaceholderValidator to MailForm at plugins/sendmail

---

src/pretix/control/templates/pretixcontrol/checkin/index.html
src/pretix/control/templates/pretixcontrol/event/base.html
src/pretix/control/urls.py
src/pretix/control/views/checkin.py
src/pretix/control/views/dashboards.py
src/tests/control/test_checkins.py
src/tests/control/test_permissions.py

Hi,
This is the PR for #297.
I added dashboard widget and checkin page under orders section in pretix control. 
There are 2 points to confirm:
1) I added filter to check whether the order position links to an item related to admission ticket. Is my understanding correct?
https://github.com/jlwt90/pretix/blob/602274fb6e2fe456e0a87d3b53cbe5ead64d7423/src/pretix/control/views/checkin.py#L27
2) I used a dict to apply multiple filters to the query to avoid [this](http://stackoverflow.com/a/28253623) issue. Is there any better way to do it?
https://github.com/jlwt90/pretix/blob/602274fb6e2fe456e0a87d3b53cbe5ead64d7423/src/pretix/control/views/checkin.py#L16
Feel free to leave some comments ;) Thanks!

#297: pretixdroid: Show metrics in the control panel

---

src/pretix/control/templates/pretixcontrol/base.html
src/pretix/control/templates/pretixcontrol/event/index.html
src/pretix/static/pretixcontrol/scss/main.scss

Added a global go to shop button in the top navigation bar.

#445 - Added go to shop button

---

src/pretix/base/models/vouchers.py
src/pretix/control/templates/pretixcontrol/vouchers/bulk.html
src/pretix/control/views/vouchers.py
src/pretix/static/pretixcontrol/js/ui/main.js

Allow to add a prefix when generating voucher codes

---

doc/admin/config.rst

Closes https://github.com/pretix/pretix/issues/528

config.rst: Include environment variable in list of paths

---

src/pretix/base/services/orders.py
src/pretix/base/settings.py
src/pretix/control/forms/event.py
src/pretix/control/templates/pretixcontrol/event/mail.html
src/pretix/control/views/event.py
src/pretix/locale/de/LC_MESSAGES/django.po
src/pretix/locale/de_Informal/LC_MESSAGES/django.po
src/tests/control/test_settings.py

Send a notification email to user when
order is cancelled.

Ref #391 -- Send email on cancelled order

---

src/pretix/control/templates/pretixcontrol/waitinglist/delete.html
src/pretix/control/templates/pretixcontrol/waitinglist/index.html
src/pretix/control/urls.py
src/pretix/control/views/waitinglist.py
src/tests/control/test_waitinglist.py

Add new action "delete" for each waiting list entry

Ref #541 -- Allow delete waitinglist entries

---

src/pretix/base/services/stats.py

Implementing proposed change from #553

Order by position first in order_overview

---

src/pretix/control/views/vouchers.py

Another 5-character fix today ;-)

Fix #556 - Max. redemptions instead of amount of vouchers

---

src/pretix/control/templates/pretixcontrol/event/mail_settings_fragment.html
src/pretix/control/templates/pretixcontrol/event/payment.html
src/pretix/presale/templates/pretixpresale/event/checkout_addons.html
src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
src/pretix/presale/templates/pretixpresale/event/order_modify.html
src/pretix/static/pretixcontrol/scss/main.scss
src/pretix/static/pretixpresale/js/ui/main.js
src/pretix/static/pretixpresale/scss/main.scss

Offer informative feedback to user by showing icons to indicate
expansible panels.

Ref #552 -- Add icon to expansible panels

---

src/pretix/settings.py

I added a try/except to make it work on Windows

os.chown is not available on Windows

---

src/pretix/control/views/orders.py

Fix missed out ordering get request handling.

Fix #565 -- OrderList ordering request handling

---

src/pretix/control/forms/event.py

I'll update translations once you've merged the other PR, to prevent rebase/merge conflicts.

Clarify mail subject prefix.

---

src/pretix/control/forms/item.py
src/pretix/control/templates/pretixcontrol/item/create.html
src/pretix/static/pretixcontrol/js/ui/hidequota.js
src/tests/control/test_items.py

Ref #475 -- add to existing quota / add new quota from product form

Ref #475 -- add to existing quota / add new quota from product form

---

doc/development/concepts.rst

I'm really new to open-source and do not have the experience to find bugs in code yet, and stumbled upon this typo while reading the documentation.
Hope to be able to contribute more in the future.

Fixed typo in Concepts.rst

---

src/pretix/control/forms/filter.py
src/pretix/control/views/orders.py

Fix #628 -- Sorting of filtered order list

---

src/pretix/control/logdisplay.py

https://github.com/pretix/pretix/issues/643

Fixes the order history text as mentioned in issue #643

---

src/pretix/base/services/cart.py
src/pretix/presale/views/cart.py
src/tests/presale/test_cart.py

* Fix #489 -- Handle Vouchers With Expired Items
* Add regression test

Fix #489 -- Handle Vouchers With Expired Items

---

src/pretix/base/services/orders.py
src/pretix/base/views/async.py
src/pretix/control/views/event.py
src/pretix/control/views/orders.py
src/pretix/locale/de/LC_MESSAGES/django.po
src/pretix/locale/de/LC_MESSAGES/djangojs.po
src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/job_detail.html
src/pretix/static/pretixbase/js/asyncdownload.js
src/pretix/static/pretixbase/js/asynctask.js

All resources I could find listed this as misspelled, but I wasn't too
sure…
Also, it should be checked if all changes to the .po-files are respected
in the corresponding src-files.

occured -> occurred

---

src/pretix/base/payment.py
src/pretix/base/templatetags/rich_text.py
src/pretix/control/templates/pretixcontrol/event/widget.html
src/pretix/plugins/paypal/payment.py
src/pretix/plugins/stripe/payment.py
src/pretix/presale/templates/pretixpresale/base.html
src/pretix/presale/templates/pretixpresale/base_footer.html
src/pretix/presale/templates/pretixpresale/event/base.html
src/pretix/static/pretixpresale/js/widget/widget.js

Required reading: https://mathiasbynens.github.io/rel-noopener/

Use rel="noopener" with target="_blank".

---

src/pretix/base/signals.py

fix typos in doc signal

---

CODE_OF_CONDUCT.md

Fix #689 -- Add CODE_OF_CONDUCT.md

---

src/pretix/locale/de/LC_MESSAGES/django.po
src/pretix/locale/de_Informal/LC_MESSAGES/django.po

Typo in German translation #709

Fixing Typo

---

src/pretix/base/services/orders.py
src/pretix/control/logdisplay.py

I just did what @raphaelm wrote in his first comment at #747.

Fix #747 -- Logging of download reminders

---

doc/admin/config.rst

The code looks for PRETIX_CONFIG_FILE in src/pretix/settings.py.
This change updates the documentation to match.

Replace PREFIX_CONFIG_FILE with PRETIX_CONFIG_FILE

---

src/pretix/static/datetimepicker/_bootstrap-datetimepicker.scss
src/pretix/static/pretixcontrol/scss/main.scss
src/pretix/static/pretixpresale/scss/main.scss

This seems to be fixing the problem.
#740

Fix #740 -- Date picker: Fix line height for decade span

---

src/pretix/base/models/vouchers.py
src/pretix/control/forms/filter.py

@rixx Would love to hear your opinion if you think this makes it clearer

Improve voucher redemption filter

---

src/pretix/plugins/stripe/forms.py
src/pretix/plugins/stripe/payment.py
src/pretix/plugins/stripe/signals.py
src/pretix/plugins/stripe/urls.py
src/pretix/plugins/stripe/views.py
src/requirements/production.txt
src/tests/plugins/stripe/test_webhook.py

Fix #103 -- Implement Stripe Connect

---

src/pretix/base/templatetags/rich_text.py

Fix #881 -- dont redirect tel scheme

---

src/pretix/control/forms/event.py

Fix #922 -- make widget compat mode not required

---

src/pretix/base/models/event.py
src/pretix/base/settings.py
src/pretix/control/forms/event.py
src/pretix/control/templates/pretixcontrol/event/display.html
src/pretix/presale/templates/pretixpresale/event/fragment_subevent_list.html
src/tests/presale/test_event.py

Add setting to configure subevent ordering on frontpage

---

src/pretix/base/ticketoutput.py
src/pretix/presale/templates/pretixpresale/event/fragment_cart.html
src/pretix/presale/templates/pretixpresale/event/order.html
src/pretix/presale/views/order.py

I screwed up that rebase pretty bad - so here is another, fresh PR...

Show download-provider specific icons where defined

---

doc/api/resources/question_options.rst

The Header is `Content-Type` not `Content`.

Correct typo

---

src/pretix/base/forms/questions.py
src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html

Fix #970 -- invoice info consistency

---

src/pretix/control/templates/pretixcontrol/order/index.html

Solve #1071.
I'm not happy about how the invoice address panel is really wide now.

make payments and invoice address full width panels

---

doc/spelling_wordlist.txt
doc/user/events/widget.rst
src/pretix/base/models/items.py
src/pretix/base/services/cart.py
src/pretix/presale/checkoutflow.py
src/pretix/presale/templates/pretixpresale/event/voucher.html
src/pretix/presale/views/cart.py
src/pretix/presale/views/event.py
src/pretix/static/pretixpresale/js/widget/widget.js
src/tests/presale/test_cart.py

Allow to pass user data to the widget

---

doc/spelling_wordlist.txt
src/pretix/base/models/event.py
src/pretix/base/models/items.py
src/pretix/base/services/quotas.py
src/pretix/base/settings.py
src/pretix/control/forms/organizer.py
src/pretix/control/templates/pretixcontrol/organizers/display.html
src/pretix/helpers/database.py
src/pretix/presale/forms/checkout.py
src/pretix/presale/templates/pretixpresale/event/fragment_subevent_calendar.html
src/pretix/presale/templates/pretixpresale/event/fragment_subevent_list.html
src/pretix/presale/templates/pretixpresale/fragment_calendar.html
src/pretix/presale/templates/pretixpresale/organizers/calendar.html
src/pretix/presale/templates/pretixpresale/organizers/index.html
src/pretix/presale/views/event.py
src/pretix/presale/views/organizer.py
src/tests/base/test_models.py

Fix #785 -- Show availability in (sub)event list

---

doc/development/api/general.rst
src/pretix/presale/signals.py

Well - that was a surprisingly easy fix... Just add some indents ;-)

Fix #1119 - Proper indent and pluralisation

---

src/pretix/helpers/daterange.py
src/tests/helpers/test_daterange.py

Adding some code to support date ranges display on Spanish. Also adding the respective tests.

Support for daterange in spanish

---

doc/api/resources/orders.rst
src/pretix/api/views/order.py
src/pretix/base/models/items.py
src/pretix/base/services/orders.py
src/pretix/control/forms/orders.py
src/pretix/control/templates/pretixcontrol/order/cancel.html
src/pretix/control/views/orders.py
src/tests/api/test_orders.py
src/tests/base/test_models.py
src/tests/control/test_orders.py

Allow to keep cancellation fees

---

src/pretix/control/templates/pretixcontrol/items/index.html

Corrected language typo.

---

src/pretix/base/payment.py

The name of the methods was incorrect.

Correct documentation for payment forms

---

doc/api/resources/events.rst
doc/api/resources/subevents.rst
src/pretix/api/serializers/event.py
src/pretix/api/views/event.py
src/pretix/base/models/event.py
src/tests/api/test_subevents.py

Refs #654 -- Add writable API for subevents

---

doc/user/events/widget.rst
src/pretix/base/models/event.py
src/pretix/control/forms/event.py
src/pretix/presale/style.py
src/pretix/presale/urls.py
src/pretix/presale/views/event.py
src/pretix/presale/views/organizer.py
src/pretix/presale/views/widget.py
src/pretix/static/pretixpresale/js/widget/widget.js
src/pretix/static/pretixpresale/scss/widget.scss
src/requirements/dev.txt
src/setup.py
src/tests/presale/test_widget.py

Fix #878 -- Add multi-event widget

---

src/tests/api/test_events.py
src/tests/api/test_oauth.py
src/tests/plugins/test_sendmail.py

Courtesy of [pytest-deadfixtures](https://pypi.org/project/pytest-deadfixtures/)

Remove dead test fixtures

---

doc/development/api/general.rst
src/pretix/base/signals.py
src/pretix/base/timeline.py
src/pretix/control/templates/pretixcontrol/event/fragment_timeline.html
src/pretix/control/templates/pretixcontrol/event/index.html
src/pretix/control/views/dashboards.py
src/pretix/static/pretixcontrol/scss/main.scss
src/tests/base/test_timeline.py

Display a timeline on the dashboard

---

src/pretix/base/forms/auth.py

This automatically focuses the username field of the login form on browsers that support the `autofocus` attribute.

Autofocus login form

---

src/pretix/base/payment.py
src/pretix/plugins/banktransfer/payment.py

Just some stuff I noticed while looking at #1396 :)

Code style improvements

---

src/pretix/control/forms/vouchers.py
src/pretix/control/views/vouchers.py

Make voucher code in notification clickable

---

src/pretix/control/templates/pretixcontrol/items/categories.html
src/pretix/control/templates/pretixcontrol/items/index.html
src/pretix/control/templates/pretixcontrol/items/questions.html

Fix #1436 -- Only disable up arrow on first page and down arrow on last page

---

src/pretix/base/models/orders.py

As required by the superbundles

Rearrange order_gracefully_delete signal-call

---

doc/api/resources/events.rst
doc/api/resources/orders.rst
doc/api/resources/subevents.rst
src/pretix/api/views/event.py
src/tests/api/test_events.py
src/tests/api/test_subevents.py

API: Allow to filter events by attributes

---

src/pretix/base/__init__.py
src/pretix/base/email.py
src/pretix/base/services/mail.py
src/pretix/base/services/vouchers.py
src/pretix/control/forms/vouchers.py
src/pretix/control/logdisplay.py
src/pretix/control/templates/pretixcontrol/vouchers/bulk.html
src/pretix/control/views/vouchers.py
src/pretix/static/pretixcontrol/js/ui/main.js
src/tests/control/test_vouchers.py

Fix #312 -- Bulk-send vouchers via email

---

src/pretix/base/services/orders.py
src/pretix/control/forms/orders.py
src/pretix/control/logdisplay.py
src/pretix/control/templates/pretixcontrol/order/change.html
src/pretix/control/views/orders.py
src/tests/base/test_orders.py
src/tests/control/test_orders.py

Allow to change fees in existing orders

---

doc/api/resources/questions.rst
src/pretix/api/serializers/item.py
src/pretix/base/forms/questions.py
src/pretix/base/models/items.py
src/pretix/base/models/orders.py
src/pretix/control/forms/item.py
src/pretix/helpers/json.py
src/pretix/settings.py
src/requirements/production.txt
src/setup.py

Z#2352979
Thoughts on this?
The dropdown-selection is not as pretty as it could be though (country flags, etc.)...

Add question type: phone number

---

src/pretix/base/channels.py
src/pretix/base/services/cart.py
src/pretix/presale/views/event.py
src/tests/presale/test_cart.py

If this is okay - we also need to merge pretix-resellers and pretix-seating - same branch.

Add unlimited_items_per_order-flag to Sales Channels

---

src/pretix/base/services/mail.py
src/pretix/base/templates/pretixbase/email/base.html
src/pretix/base/templates/pretixbase/email/separator.html

Improve email contents

---

src/pretix/control/templates/pretixcontrol/base.html
src/pretix/static/are-you-sure/jquery.are-you-sure.js
src/pretix/static/pretixcontrol/js/ui/main.js

Add "Are you sure?"-dialog to dirty forms

---

src/pretix/presale/templates/pretixpresale/event/fragment_cart.html
src/pretix/presale/views/__init__.py

Add itemcount (Items, excluding AddOns) to fragment_cart

---

doc/api/resources/carts.rst
src/pretix/api/serializers/cart.py
src/pretix/api/serializers/order.py
src/pretix/base/models/event.py
src/pretix/base/models/seating.py
src/pretix/base/services/cart.py
src/pretix/base/services/orders.py
src/pretix/base/settings.py
src/tests/api/test_cart.py
src/tests/api/test_orders.py

See also https://code.rami.io/pretix/pretix-seating/merge_requests/4

Allow sale of blocked seats on specific channels

---

src/pretix/base/forms/auth.py
src/pretix/control/templates/pretixcontrol/auth/login.html

Fix #1522 -- Login button redirects to authentication url with single backend

---

src/pretix/base/models/event.py
src/pretix/plugins/statistics/templates/pretixplugins/statistics/index.html
src/pretix/plugins/statistics/views.py

Statistics on sold and unsold seats, as well as potential profits

---

src/pretix/plugins/paypal/payment.py

Do not hard fail on Unauthorized PayPal Userinfo-calls

---

src/pretix/control/templates/pretixcontrol/base.html

unifying the text bit 'Go to shop' to display 'shop' with a lowercase s in base.html

Localization string unification changes

---

src/pretix/base/payment.py
src/pretix/base/settings.py
src/pretix/control/forms/item.py
src/pretix/plugins/banktransfer/__init__.py

Changed the wording from "following" to "selected" to match the display in payment.py

Added various missing punctuation marks, changed wording

---

src/pretix/base/forms/questions.py
src/pretix/presale/checkoutflow.py
src/tests/presale/test_checkout.py

Fix #1675 -- Allow '0' as answer to number questions

---

src/pretix/presale/views/__init__.py

This fixes #1740. Also refs #1663.

Fix #1740 - Do not group gift card positions

---

src/pretix/base/services/orderimport.py
src/tests/base/test_orderimport.py

Fix #1759: order import increasing  positionids

---

src/pretix/static/pretixcontrol/js/ui/main.js
src/pretix/static/pretixpresale/js/ui/main.js

I'd like this for a plugin.
Want me to change it for presale js as well?

Support required-if and display-dependency for more elements

---

src/pretix/control/forms/vouchers.py

Allow to unselect product or quota from voucher

---

doc/development/api/plugins.rst

Fixed small typo and update references

Update plugin-development documentation

---

src/pretix/plugins/banktransfer/views.py

cf. https://github.com/pretix/pretix-sepadebit/pull/18

Allow Refunds for SEPA Debit

---

src/pretix/base/models/event.py

Added total seats, sold seats, and reserved seats to the existing free seat counter.

Add seating statistics in shared reports

---

doc/api/resources/exporters.rst
doc/api/resources/index.rst
src/pretix/api/serializers/exporters.py
src/pretix/api/urls.py
src/pretix/api/views/exporters.py
src/pretix/base/exporters/mail.py
src/pretix/base/models/devices.py
src/pretix/base/models/organizer.py
src/pretix/base/services/export.py
src/pretix/base/services/tasks.py
src/tests/api/test_exporters.py
src/tests/api/test_permissions.py

Fix #1780 -- Trigger exports through API

---

src/pretix/base/models/event.py
src/pretix/control/templates/pretixcontrol/user/notifications_disable.html
src/pretix/control/views/user.py
src/tests/control/test_user.py

Bad antivirus, clicking all my links! Very bad!

Confirm disabling all notifications

---

src/pretix/base/models/event.py
src/pretix/presale/templates/pretixpresale/event/fragment_subevent_list.html
src/pretix/presale/templates/pretixpresale/event/index.html
src/pretix/presale/templates/pretixpresale/organizers/index.html
src/pretix/presale/views/widget.py

- Z#2367456
- Relates to: /pretix/pretix-resellers/-/merge_requests/6

Add effective presale_start and presale_end properties

---

src/pretix/static/pretixcontrol/js/ui/subevent.js
src/pretix/static/rrule/rrule.js

Subevent repeat until date suggests that date is inclusive, but in RRule.until it is non-inclusive. Solution was to add 1 day. Updated to latest RRule 2.6.6

Fix preview of subevent repetition rule with UNTIL

---

src/pretix/presale/templates/pretixpresale/event/index.html

Has been requested multiple times and probably also makes more sense

Move front page text above date selection

---

src/pretix/base/settings.py
src/pretix/static/pretixcontrol/scss/_forms.scss
src/pretix/static/pretixpresale/scss/_forms.scss

Also fixed a display/overflow issue with the form inputs when displayed as a long line.

Added Person-Name-Scheme for showing/entering academic degree after the name (e.g. <Name>, MA)

---

src/pretix/base/settings.py

Thanks to @inwwin for [pointing this out](https://github.com/pretix/pretix/pull/1760#discussion_r532240765)!

Payment term on weekdays should not be required

---

src/pretix/base/models/orders.py

Remove last usage of blacklist in comment

---

src/pretix/base/pdf.py

Add Invoice and Attendee address mergefields for all address segments

---

doc/api/resources/organizers.rst
src/pretix/api/serializers/event.py
src/pretix/api/serializers/organizer.py
src/pretix/api/urls.py
src/pretix/api/views/event.py
src/pretix/api/views/organizer.py
src/pretix/base/settings.py
src/pretix/control/forms/event.py
src/pretix/control/forms/organizer.py
src/pretix/control/views/event.py
src/pretix/control/views/organizer.py
src/tests/api/test_events.py
src/tests/api/test_organizers.py
src/tests/api/test_permissions.py

REST API: Add organizer-level settings

---

doc/api/resources/orders.rst
src/pretix/api/serializers/cart.py
src/pretix/api/serializers/order.py
src/pretix/api/views/order.py
src/pretix/base/models/orders.py
src/pretix/control/views/orders.py
src/tests/api/test_cart.py
src/tests/api/test_orders.py

API: Allow to modify order position information

---

src/pretix/base/settings.py

Add salutation_given_family to PERSON_NAME_SCHEMES.

---

doc/api/resources/orders.rst
doc/development/api/general.rst
src/pretix/api/auth/devicesecurity.py
src/pretix/api/serializers/order.py
src/pretix/api/views/order.py
src/pretix/base/invoice.py
src/pretix/base/pdf.py
src/pretix/base/signals.py
src/pretix/control/templates/pretixcontrol/pdf/index.html
src/pretix/control/views/pdf.py
src/pretix/helpers/reportlab.py
src/pretix/static/pretixcontrol/js/ui/editor.js
src/pretix/static/pretixcontrol/scss/pdfeditor.css

PDF layout: Allow to show photos from questions

---

src/pretix/base/management/commands/runperiodic.py

Makes it easier to monitor errors when running `runperiodic` command.

Adjust runperiodic logging

---

src/pretix/control/forms/orders.py
src/pretix/control/templates/pretixcontrol/order/reactivate.html
src/pretix/control/views/orders.py

The form used is not exactly meant to be used here - but it works and has exactly the same functionality... So in order to avoid code duplication: here it is :-)

Add force-reactivate checkbox to order

---

src/pretix/api/auth/devicesecurity.py
src/pretix/api/serializers/event.py
src/pretix/api/serializers/exporters.py
src/pretix/api/views/device.py
src/pretix/base/forms/questions.py
src/pretix/base/services/cart.py
src/pretix/base/templatetags/money.py
src/pretix/base/views/errors.py
src/pretix/control/forms/item.py
src/pretix/control/permissions.py
src/pretix/control/views/event.py
src/pretix/helpers/jsonlogic.py
src/pretix/multidomain/templatetags/eventurl.py
src/pretix/plugins/checkinlists/exporters.py
src/pretix/plugins/reports/exporters.py
src/tests/api/test_events.py
src/tests/api/test_items.py
src/tests/api/test_subevents.py

Hi, I ran DeepSource analysis on my fork of the repo, and found some interesting [code quality and performance issues](https://deepsource.io/gh/akshgpt7/pretix/) to consider.
This PR fixes a few of the issues detected.
- Use literals instead of function calls to assign data structure.
- Refactor unnecessary use of list comprehension.
- Merge `isinstance` calls.
- Use `if` statements to improve readability.
- Remove calling `len()` for comparison.

Refactor code quality issues

---

src/pretix/base/metrics.py

The current implementation only works if redis is used as broker.
Otherwise it would throw an Exception, which causes a 500 to be returend.
Now we just don't have celery metrics in those cases.
Fixes #2029

Check if celery channel has client before getting metrics

---

src/pretix/control/views/global_settings.py

Should check for license being None first.

Fix type error in license check view

---

src/pretix/control/templates/pretixcontrol/event/tax_index.html

I'd like to see whether or not tax rules prices are inclusive or exclusive in the overview.

Tax rule list: Show inclusiveness and eu reverse tax status

---

src/pretix/control/forms/event.py
src/pretix/control/views/main.py

Event creation: set the organizer locales as default

---

doc/admin/config.rst
src/pretix/settings.py
src/setup.py

Both for caching and for celery
Fixes #1905

Add redis sentinel support

---

src/pretix/plugins/stripe/tasks.py

This is a re-re-re-visitation of the curious case of ApplePay not working for some users of pretix with Stripe - even though their domains had been registered through the corresponding API call.
Stripe says regarding this issue:
> The reason you’re getting this error is because, on acct_redacted, you’ve registered your Apple Pay domains with your testmode secret key. In order to correct for this, you’ll need to register your Apple Pay domain using the livemode Platform secret key, along with the Stripe-Account header of the Connected account, i.e. stripe_account: acct_redacted. You can then initialize Stripe.js with the testmode Platform publishable key along with the Stripe-Account header on their webpage, to test out Apple Pay functionality. 
This PR should implement the domain …

Always register ApplePay domains in livemode

---

src/pretix/base/models/event.py

Add uninstall-handler for plugins

---

doc/admin/installation/manual_smallscale.rst

Ref: https://github.com/pretix/pretix/commit/66cf9c1ac79518a07c239ba786c094346a09691c

Docs: no diff in mysql / pstgres in upgrade

---

src/pretix/base/views/mixins.py
src/pretix/presale/checkoutflow.py
src/pretix/presale/forms/checkout.py
src/pretix/presale/forms/renderers.py
src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
src/pretix/static/pretixpresale/js/ui/questions.js
src/pretix/static/pretixpresale/scss/_checkout.scss

Allow to save invoice addresses and attendee profiles to customer account

---

src/pretix/base/models/event.py

Micro-change, PR with tests just to make sure.

Subevent: add missing verbose_name for seating plan

---

doc/admin/config.rst
src/pretix/api/serializers/item.py
src/pretix/api/serializers/order.py
src/pretix/api/views/checkin.py
src/pretix/base/forms/questions.py
src/pretix/base/services/mail.py
src/pretix/base/settings.py
src/pretix/control/forms/organizer.py
src/pretix/control/views/orderimport.py
src/pretix/control/views/pdf.py
src/pretix/plugins/sendmail/forms.py
src/pretix/settings.py

Add config options for max file upload sizes

---

Dockerfile
deployment/docker/nginx-max-body-size.conf
deployment/docker/nginx.conf

To allow admins easier customization of that value.
See https://github.com/pretix/pretix/discussions/2188#discussioncomment-1329467

Dockerfile: Move nginx client_max_body_size to seperate file

---

src/pretix/base/invoice.py

We tried in de597ba86 and reverted in a09dac8

Another attempt at correct sanitization of HTML in invoice content

---

src/pretix/base/models/event.py
src/pretix/base/settings.py
src/pretix/static/pretixpresale/scss/main.scss

This PR introduces the non-controversial changes discussed in #2146

Change default settings for background color, invoice attachmentes and name scheme

---

src/pretix/presale/templates/pretixpresale/fragment_day_calendar.html
src/pretix/presale/templates/pretixpresale/organizers/calendar_day.html
src/pretix/presale/views/organizer.py
src/pretix/static/pretixpresale/js/ui/main.js
src/pretix/static/pretixpresale/scss/_calendar.scss

Add day calendar to organizer page

---

doc/development/api/cookieconsent.rst
doc/development/api/index.rst
doc/user/events/widget.rst
src/pretix/api/serializers/organizer.py
src/pretix/base/models/organizer.py
src/pretix/base/settings.py
src/pretix/control/forms/organizer.py
src/pretix/control/templates/pretixcontrol/organizers/edit.html
src/pretix/presale/context.py
src/pretix/presale/cookies.py
src/pretix/presale/signals.py
src/pretix/presale/templates/pretixpresale/event/base.html
src/pretix/presale/templates/pretixpresale/fragment_js.html
src/pretix/presale/templates/pretixpresale/fragment_modals.html
src/pretix/presale/templates/pretixpresale/organizers/base.html
src/pretix/static/pretixpresale/js/ui/cookieconsent.js
src/pretix/static/pretixpresale/js/ui/main.js
src/pretix/static/pretixpresale/scss/_forms.scss
src/pretix/static/pretixpresale/scss/main.scss

Add central cookie consent mechanism

---

doc/development/algorithms/index.rst

included missing adjective

---

src/pretix/control/forms/filter.py
src/pretix/control/templates/pretixcontrol/organizers/devices.html

Works as intended - but I seem to be hitting a wall when it comes to setting the initial value on the FilterForm, so that the "Active Devices"-filter is set by default.

Add filter for revoked devices

---

src/pretix/control/forms/filter.py
src/pretix/control/navigation.py
src/pretix/control/templates/pretixcontrol/search/payments.html
src/pretix/control/urls.py
src/pretix/control/views/search.py
src/tests/control/test_search.py

Add payment search page

---

src/pretix/plugins/webcheckin/static/pretixplugins/webcheckin/components/app.vue

Web checkin: Redirect user to login if session expired

---

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html

Removing the disabled attribute on the checkbox, since it also prevents the value from being submitted by POST

Remove disabled attribute on checkbox

---

src/pretix/base/shredder.py
src/tests/base/test_shredders.py

Fix #2456 -- Allow shredding instantly after event end

---

src/pretix/control/views/vouchers.py

Proposed fix for #2477.
I'm open to construct a test-case, if needed.

vouchers: allow deleting vouchers that are used on addon cartpositions

---

src/pretix/base/forms/widgets.py
src/pretix/helpers/formats/ar/__init__.py
src/pretix/helpers/formats/ar/formats.py

Accept arabic numbers from date picker

---

src/pretix/presale/templates/pretixpresale/event/voucher.html
src/tests/presale/test_event.py

When we refactored the product list, we apparently forgot about the voucher redemption page, leading to minor design and functionality issues. Also, the new accessiblity improvements did not make it here.
@wiffbi please double-check if my patch makes sense :)

Fix voucher redemption page markup

---

src/pretix/base/views/mixins.py
src/pretix/presale/checkoutflow.py
src/pretix/presale/views/order.py

Questions step: Only prefill customer name for first ticket

---

src/pretix/settings.py

As discussed with @raphaelm, add the Czech translation.

Add Czech translation

---

.github/workflows/tests.yml

Fix CI builds

---

src/pretix/static/pretixpresale/js/widget/widget.js

It seems I did some breaking changes before I submitted the #2569, that I did not correctly test. This minor change should fix that. Sorry for the inconvenience.

Widget: Fix trigger_close_callback()

---

Dockerfile

NodeJS 16 is the current LTS version, NodeJS 15 is unsupported

Upgrade NodeJS to version 16 LTS

---

src/pretix/static/pretixcontrol/scss/main.scss

Make IE11 warning in backend bigger

---

src/pretix/base/services/orders.py
src/tests/api/test_order_change.py

Fixes Z#23101774, supersedes #2695

API: Fix order total after order change operation

---

src/pretix/plugins/banktransfer/payment.py
src/pretix/plugins/banktransfer/static/pretixplugins/banktransfer/swisscross.css
src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/pending.html

This generates a new style of QR codes for bank transfers to Switzerland
Sample code has been tested with https://validation.iso-payments.ch/

Bank transfer: Minimal implementation of Swiss QR-bill

---

src/pretix/api/auth/devicesecurity.py

cf:
- pretix/pretix#2850
- pretix/libpretixui-android#7
- pretix-posbackend#5
- pretixpos-android#60

Security Profiles: Add stripeterminal.paymentintent to POS

---

src/setup.cfg
src/setup.py

Update celery to 5.2

---

src/pretix/control/forms/filter.py
src/pretix/control/views/organizer.py

This has been requested by a large number of people by now :)

Device list: Hide revoked devices by default

---

src/pretix/base/models/checkin.py
src/pretix/helpers/database.py

Optimize CheckinList.inside_count

---

doc/admin/installation/manual_smallscale.rst

Just made a new test installation on debian 11.6 and verified all steps from the installation guide.

bump debian version

---

src/pretix/control/forms/filter.py
src/pretix/control/templates/pretixcontrol/subevents/index.html
src/pretix/control/urls.py
src/pretix/control/views/subevents.py
src/pretix/control/views/typeahead.py

This PR adds meta-data filters to the dates/subevents overview.
In the second commit, I added some TODOs/questions in code comments.

Subevent list: Add meta-data filter (Z#23114466)

---

src/pretix/base/email.py
src/pretix/base/settings.py
src/pretix/control/forms/event.py
src/pretix/control/templates/pretixcontrol/event/mail.html
src/pretix/plugins/banktransfer/tasks.py
src/tests/plugins/banktransfer/test_import.py

Closes https://github.com/pretix/pretix/issues/2819

Separate mail template for incomplete payment notifications

---

src/pretix/static/pretixpresale/js/widget/widget.js
src/pretix/static/pretixpresale/scss/widget.scss

Widget: add role=button to close element 

---

src/pretix/base/templates/pretixbase/forms/widgets/thumbnailed_file_input.html
src/pretix/presale/templates/pretixpresale/event/base.html
src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html
src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html
src/pretix/presale/templates/pretixpresale/event/voucher.html
src/pretix/presale/templates/pretixpresale/organizers/base.html

The idea is to provide a 200% and 300% version for hi-dpi mobile devices, tablets and laptops.

Provide hidpi versions of logos and product pictures

---

src/pretix/base/models/customers.py
src/pretix/base/models/memberships.py
src/pretix/base/models/orders.py
src/pretix/base/models/waitinglist.py
src/pretix/base/settings.py
src/pretix/control/templates/pretixcontrol/order/index.html
src/pretix/control/templates/pretixcontrol/waitinglist/index.html
src/pretix/helpers/names.py

I went with really the minimum amount of places to change for now since I still feel without the salutations it is more natural in all kinds of lists, etc, but it's useful to see in the situation where you are e.g. just about to call someone.

Show name including saluation in some places (Z#23121817)

---

src/pretix/control/templates/pretixcontrol/orders/overview.html
src/pretix/plugins/checkinlists/exporters.py
src/pretix/plugins/reports/accountingreport.py
src/pretix/plugins/reports/exporters.py
src/pretix/plugins/reports/signals.py

There's lots of confusion around which reports from pretix are best to use for accounting purposes. This report tries to give a good answer to this question.

Reports: Add new "accounting report"

---

doc/admin/installation/docker_smallscale.rst
doc/admin/installation/manual_smallscale.rst

Just updated the requirements and links.
Is Postgres 11+ still the current requirement?

Docs: update requirements and links

---

src/pretix/base/services/shredder.py
src/pretix/base/shredder.py
src/pretix/base/templates/pretixbase/email/shred_completed.txt
src/pretix/base/views/tasks.py
src/pretix/control/templates/pretixcontrol/base.html
src/pretix/control/templates/pretixcontrol/shredder/download.html
src/pretix/control/views/shredder.py
src/pretix/static/pretixbase/js/asynctask.js

This PR does three things:
- Artificially slow down some queries used by data shredders to prevent them from overloading the database
- Sending an email to the user who triggered the shredding as a confirmation of successful deletion
- Showing a useful intermediate status

Data shredder optimizations

---

pyproject.toml

Bump celery to 5.3

---

doc/development/api/general.rst
src/pretix/base/signals.py
src/pretix/presale/views/customer.py
src/tests/presale/test_customer.py

Adds signals for customer account creation and sign in.
https://github.com/pretix/pretix/discussions/3455#discussioncomment-6419843

Add signals for customer account creation and sign in

---

src/pretix/base/models/orders.py
src/pretix/base/settings.py
src/pretix/control/forms/event.py
src/pretix/control/logdisplay.py
src/pretix/control/templates/pretixcontrol/event/mail.html
src/tests/base/test_orders.py

Send mail on payment failure [Z#23122835]

---

src/pretix/base/pdf.py

This is technically not backwards-compatibile, but I'm not able to come up with a situation in which it is not wanted.

PDF: Deduplicate list of add-ons

---

src/pretix/static/pretixcontrol/js/ui/typeahead.js
src/pretix/static/pretixcontrol/scss/main.scss

Adds a loading indicator to the typeahead dropdowns. It is only displayed if loading takes longer than a predefined timeout.
Also some refactoring of duplications in the typeahead code.

Typeahead: Add load indicator

---

src/pretix/api/serializers/order.py
src/pretix/base/pdf.py
src/pretix/base/signals.py
src/tests/api/test_orders.py

This is a new try at #3517 with less bugs ;)

Allow PDF variables to provide a bulk evaluation method

---

src/pretix/base/cache.py
src/pretix/base/forms/widgets.py
src/pretix/presale/checkoutflow.py

Set the default value for the "Individual" / "Business" field in the invoice address based on which one is more common in the overall orders of that organizer.

Feature: Prefill InvoiceAddress type heuristically (Z#23126061)

---

src/pretix/base/exporters/orderlist.py

Someone will complain about the column order changing, but I'd argue it's worth it – this makes a lot of sense for processing the file

Order data export: Add product/variation ID

---

src/pretix/api/serializers/order.py
src/pretix/api/views/checkin.py
src/tests/api/test_checkin.py

Requirement for https://github.com/pretix/libpretixsync/pull/29 working correctly

Improve edge cases in handling of check-in nonces

---

src/pretix/base/payment.py
src/pretix/plugins/stripe/payment.py
src/tests/base/test_payment.py

This PR will require changes to the pretix-mollie plugin which overrides the private method that I renamed

Payment providers: Allow to set an availability start date per method (Z#23126769)

---

src/pretix/control/forms/__init__.py
src/pretix/control/templates/pretixcontrol/multi_languages_select.html
src/pretix/control/templates/pretixcontrol/multi_languages_widget.html
src/pretix/helpers/i18n.py
src/pretix/static/pretixbase/scss/_theme.scss

Add language translation score to selector widget

---

src/tests/concurrency_tests/test_api_order_creation_locking.py

This is a test file I created for #2408 but forgot to push back then :sweat_smile:

Add tests for locking in API

---

src/pretix/plugins/paypal2/static/pretixplugins/paypal2/pretix-paypal.js

PayPal: Add visibility EventListener for onApprove (Z#23135203)

---

src/pretix/control/templates/pretixcontrol/checkin/bulk_revert_confirm.html
src/pretix/control/templates/pretixcontrol/checkin/index.html
src/pretix/control/urls.py
src/pretix/control/views/checkin.py

- Add a confirmation step
- Don't write a log entry if nothing was done

Improve check-in deletion

---

src/pretix/static/pretixpresale/js/widget/widget.js

Question: Are we in danger of this breaking pages of customers who show the widget in a lightbox-style overlay?

Add autoscroll to widget after changing pages (Z#23135651)

---

src/pretix/control/templates/pretixcontrol/pagination.html
src/pretix/static/pretixcontrol/js/ui/main.js

- Jump to last page (I don't really like the additional button visually, but was requested internally)
- Jump to specific page without cluttering the UI (was requested by a customer)

Paginator: Add options for advanced users in backend

---

src/pretix/presale/views/__init__.py
src/pretix/presale/views/locale.py

Fix #3701 -- Don't use static cookie_domain on custom domains

---

src/pretix/control/templates/pretixcontrol/orders/index.html
src/pretix/control/urls.py
src/pretix/control/views/orders.py
src/tests/control/test_orders_bulk.py

Orders: Add bulk action to refund overpaid amount

---

src/pretix/static/pretixcontrol/js/ui/main.js

Allows to display a field only if the dependency field's value matches a regex (currently we can only match against a single fixed value).

Add regexp compare for data-display-dependency-value

---

pyproject.toml
src/pretix/plugins/stripe/payment.py
src/pretix/plugins/stripe/static/pretixplugins/stripe/pretix-stripe.js
src/pretix/plugins/stripe/templates/pretixplugins/stripe/control.html
src/pretix/plugins/stripe/templates/pretixplugins/stripe/sca.html
src/pretix/plugins/stripe/views.py
src/tests/api/test_orders.py
src/tests/control/test_orders.py
src/tests/plugins/stripe/test_checkout.py
src/tests/plugins/stripe/test_provider.py
src/tests/plugins/stripe/test_webhook.py

Stripe: Convert all payment methods to intents except multibanco

---

src/pretix/helpers/formats/en_CA/__init__.py
src/pretix/helpers/formats/en_CA/formats.py

Ref: https://github.com/pretix/pretix/discussions/3842
I understand that I need to [make sure to have provisions](https://github.com/pretix/pretix/discussions/3842#discussioncomment-8284389) for this PR, but I'm not sure what that entails. Please let me know what else needs to be added or done, and I'll update this PR.
I'll create a PR for Django later. It looks like they already have a format for [Canadian French](https://github.com/django/django/blob/main/django/conf/locale/fr_CA/formats.py), which is great!
Related Django PR: https://github.com/django/django/pull/17794

Canadian English formats patch

---

src/pretix/base/models/orders.py
src/pretix/base/services/orders.py
src/pretix/base/services/tickets.py
src/pretix/base/signals.py
src/pretix/base/ticketoutput.py
src/pretix/plugins/ticketoutputpdf/ticketoutput.py
src/pretix/presale/templates/pretixpresale/event/fragment_cart.html
src/pretix/presale/templates/pretixpresale/event/fragment_downloads.html
src/pretix/presale/views/order.py
src/tests/base/test_orders.py
src/tests/testdummy/ticketoutput.py

second attempt at https://github.com/pretix/pretix/pull/3836
⚠️ merge at the same time as the matching change to pretix-shipping

Let plugins prevent the download of individual tickets in an order

---

src/pretix/presale/templates/pretixpresale/event/order_modify.html

ad Postion Name by Additional Products the Variant should missing. added it with the prefix "-"

Add product variation to addon-label when modifying order

---

src/pretix/control/forms/item.py
src/pretix/control/forms/subevents.py
src/pretix/control/forms/widgets.py
src/pretix/control/urls.py
src/pretix/control/views/subevents.py
src/pretix/control/views/typeahead.py
src/pretix/static/pretixcontrol/js/ui/main.js

Change the quota forms item checkbox selection to a multiselect widget if it is displayed within a date (subevent) form so it loads better in some browers

Quota form: Change item selection field per context

---

src/pretix/static/pretixpresale/js/ui/main.js

Fix UI-state of automatically unchecked button-checkboxes in addon-step

---

src/tests/base/test_orders.py
src/tests/plugins/sendmail/test_rules.py

Fix tests that failed between 0:00 and 4:00 / 4:30 AM

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/strings.yml
.github/workflows/style.yml
.github/workflows/tests.yml

Github started nagging about outdated actions in our workflows, this should make it happy again.
According to a quick check of the changelogs, this shouldn't break anything, but it's hard to test.

Update github action versions

---

doc/admin/config.rst
src/pretix/settings.py

Add database.disable_server_side_cursors option

---

src/pretix/base/services/waitinglist.py
src/tests/base/test_waitinglist.py

The waiting list algorithm has had major issues on event series with seating plans and a large number ob subevents, leading to frequent out-of-memory bugs and very long runtime.
The exact source of the out-of-memory error is not entirely clear to me, it was somewhere in this loop:
```
for m in SeatCategoryMapping.objects.filter(event=event).select_related('subevent'):
num_free_seets_for_product = (m.subevent or event).free_seats().filter(product_id=m.product_id).count()
num_valid_vouchers_for_product = event.vouchers.filter(
Q(valid_until__isnull=True) | Q(valid_until__gte=now()),
block_quota=True,
item_id=m.product_id,
subevent_id=m.subevent_id,
waitinglistentries__isnull=False
).aggregate(free=Sum(F('max_usages') - F('redeemed')))['free'] or 0
seats_available[(m.product_id, …
```

Waiting list: Fix pathological performance on large series with seating

---

src/pretix/base/models/orders.py

When getting an order through `OrderQuerySet::get_with_secret_check`, if the order was found, but the secret was wrong, two hash-compares were executed which could potentially lead to timing attacks – basically if the response takes twice as long, it is a correct order-code, but a wrong hash.

Harden timing when getting order with secret check

---

src/pretix/plugins/checkinlists/exporters.py

New column and sort options for check-in-list export  (Z#23158159)

---

src/pretix/plugins/stripe/payment.py
src/pretix/plugins/stripe/signals.py

Untested, as our account is not in the Revolut Pay Europe beta (I requested it, though)

Stripe: Add Revolut Pay

---

src/pretix/control/views/auth.py
src/tests/control/test_auth.py

Fix reauth loops with redirect style authentication plugins

---

src/pretix/control/templates/pretixcontrol/items/question.html
src/pretix/control/views/item.py

The magic™ is really just in the subevent-filter - but while I was at it, I also updated the filter to look more like our other filter boxes...

Questions: Add SubEvent-Filter; Renew Filter-Form Layout (Z#23168996)

---

.github/workflows/tests.yml
.gitlab-ci.yml
pyproject.toml
src/setup.cfg

see also https://github.com/pytest-dev/pytest-rerunfailures/issues/277

Tests: Remove pytest-rerunfailures

---

src/pretix/control/templates/pretixcontrol/item/base.html
src/pretix/control/templates/pretixcontrol/item/include_variations.html
src/pretix/control/views/item.py
src/pretix/static/pretixcontrol/js/ui/quota.js

Add action buttons to "missing quota" warnings

---

src/pretix/control/forms/orders.py
src/pretix/control/templates/pretixcontrol/order/change.html
src/pretix/control/views/orders.py
src/tests/control/test_orders.py
src/tests/presale/test_event.py

Allow organizers to manually add fees to an existing order

---

pyproject.toml
src/pretix/base/invoice.py
src/pretix/base/settings.py
src/pretix/base/templatetags/rich_text.py
src/pretix/control/logdisplay.py
src/pretix/plugins/checkinlists/exporters.py
src/pretix/plugins/sendmail/views.py
src/tests/base/test_rich_text.py

Parameter type changes (use sets instead of lists for allowed tags and protocols)
See dependabot PR #4591 and [bleach Changelog](https://github.com/mozilla/bleach/blob/main/CHANGES)

Bleach 6 update

---

src/pretix/base/email.py
src/pretix/base/services/mail.py
src/pretix/base/services/placeholders.py
src/pretix/base/templates/pretixbase/email/base.html
src/pretix/base/templatetags/rich_text.py
src/pretix/control/forms/event.py
src/pretix/control/views/event.py
src/pretix/control/views/orders.py
src/pretix/control/views/organizer.py
src/pretix/control/views/vouchers.py
src/pretix/helpers/format.py
src/pretix/plugins/sendmail/forms.py
src/pretix/plugins/sendmail/views.py
src/pretix/static/pretixcontrol/scss/_forms.scss
src/pretix/static/pretixcontrol/scss/_mail_preview.scss
src/pretix/static/pretixcontrol/scss/main.scss
src/tests/helpers/test_format.py

Add the option to introduce rich-text placeholders

---

src/pretix/static/pretixpresale/js/widget/widget.js

Widget: add span around currency for easier styling

---

src/pretix/control/forms/event.py
src/pretix/control/views/main.py

(still warn if tax rate is not filled at all)

Allow 0% tax rate on event creation

---

src/pretix/presale/views/cart.py

Handle free price input in the cross-selling step in an event series

---

src/pretix/base/forms/questions.py

I'm not fully convinced it's an improvement, but if enough people think so, I don't hold a strong opinion :shrug:

Add a label for empty salutation option (Z#23183319)

---

src/pretix/presale/templates/pretixpresale/event/fragment_addon_choice.html
src/pretix/presale/templates/pretixpresale/event/fragment_availability.html
src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html
src/pretix/presale/templates/pretixpresale/event/voucher.html

… even if a voucher gives 100% off

Show SOLD OUT instead of FULLY BOOKED if ticket is not free of charge (Z#23187802)

---

src/pretix/presale/templates/pretixpresale/event/fragment_product_list.html

The checkbox button did not reflect the disabled-state of its checkbox.

Fix missing checkbox-button disabled-state

---

src/pretix/static/pretixpresale/scss/_forms.scss

Fix double-thick line between inputs in input-group

---

src/pretix/presale/templates/pretixpresale/event/fragment_cart.html

Service fee in cart was not marked up correctly as a reachable table-row

[A11y] Fix service fee HTML-structure

---

src/pretix/presale/templates/pretixpresale/organizers/customer_memberships.html
src/pretix/presale/templates/pretixpresale/organizers/customer_orders.html
src/pretix/static/pretixpresale/scss/main.scss

[A11y] change customer-pages dl to list of article

---

src/pretix/presale/templates/pretixpresale/event/fragment_event_info.html
src/pretix/static/pretixpresale/scss/main.scss

This is suggestion nr. 5 from a11y-review

[A11y] make location & time icons role=img with labels

---

src/pretix/presale/templates/pretixpresale/event/index.html
src/pretix/presale/templates/pretixpresale/event/voucher.html

They are not used anymore, and in voucher.html, the if-condition is broken (only works if not in an event-series).
alternative: #5180

Remove unused form.has-seating classes

---

doc/api/resources/orders.rst
src/pretix/api/serializers/order.py
src/tests/api/test_order_create.py

API: Fix crash on distributing a fee over tax rates with zero value (Z#23196669)

---

src/pretix/static/pretixcontrol/js/ui/question.js

The statistical graphs were not displayed. This is due to `#question-chart-data` having changed format. I made the parsing more robust.

Control: fix question graphs UI

---

src/pretix/static/pretixcontrol/js/ui/main.js

Demoed on https://jsfiddle.net/fyqnz0L7/3/

Support transitive dependencies on data-checkbox-dependency

---

src/pretix/presale/templates/pretixpresale/event/checkout_customer.html
src/pretix/presale/templates/pretixpresale/event/checkout_payment.html
src/pretix/presale/templates/pretixpresale/event/index.html

[A11y] Presale: improve heading levels for better document outline

---

src/pretix/base/models/orders.py

I have updated the race condition check of the method `OrderPayment.fail()` (inside `pretix/base/models/orders.py`) from:
```py=
if locked_instance.state not in (OrderPayment.PAYMENT_STATE_CREATED, OrderPayment.PAYMENT_STATE_PENDING):
```
to:
```py=
if locked_instance.state in (OrderPayment.PAYMENT_STATE_CONFIRMED, OrderPayment.PAYMENT_STATE_FAILED, OrderPayment.PAYMENT_STATE_REFUNDED):
```
This enables the state transition from `PAYMENT_STATE_CANCELED` to `PAYMENT_STATE_FAILED` (which was previously forbidden).
I personally have no idea if it was intended to forbid passing from canceled to failed, but from the description of the method (_[...] since we do not want to report a failure for an order that has just been marked as paid._) it seems acceptable
I'm requesting this change for a …

OrderPayment.fail: Change race condition detection condition

---

src/pretix/base/pdf.py

PDFs have this neat/annoying (delete as appropriate) feature where the origin point of content for each page can be adjusted by one of several boxes, e.g. the media box.
Pretix uses `pypdf` to merge backgrounds into generated PDFs for ticket output. `pypdf`'s docs states than when merging pages "the mediabox, cropbox, etc of this page are not altered"; [1] thus Pretix needs to handle these itself.
All pages Pretix generates have content boxes at the `(0,0)` origin, but not all source PDFs for the background will have such origins. Without correct handling, the background is misplaced, resulting in elements being in the wrong location, white bars appearing on coloured backgrounds, and some of the backgrounds being cut off; e.g.:
[1]: …

Fix incorrect placement of background when merging PDFs

---

src/pretix/base/models/event.py
src/tests/base/test_models.py

Event calendar: Only show "waiting list" if products allow it (Z#23205941)

---

src/pretix/static/pretixbase/js/asynctask.js

Fix waitingDialog being shown on browser history back

---

src/pretix/helpers/daterange.py
src/pretix/helpers/formats/en_NZ/__init__.py
src/pretix/helpers/formats/en_NZ/formats.py

- Implement en-NZ specific formatting in daterange.py
- Create en_NZ/formats.py with NZ-compliant formats

Add support for New Zealand (en-nz) date/time formats

---

src/pretix/control/views/user.py

Fix logging when changing user notifications
